# values.yaml
replicaCount: 1
image:
  repository: nats
  tag: "2.10.4" # Thay thế bằng tag NATS mong muốn
  pullPolicy: IfNotPresent
service:
  type: NodePort
  ports:
    client:
      port: 4222
      nodePort: 30002 # Thay đổi NodePort theo ý muốn
    cluster:
      port: 6222
      nodePort: 30003
    monitoring:
      port: 8222
      nodePort: 30004