apiVersion: v2
name: app-cluster
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - alias: consul
    name: consul
    version: "0.1.0"
    repository: file://consul
  - alias: nginx
    name: nginx
    version: "0.1.0"
    repository: file://nginx
  - alias: mysql
    name: mysql
    version: "0.1.0"
    repository: file://mysql
  - alias: redis
    name: redis
    version: "0.1.0"
    repository: file://redis
  - alias: mongo
    name: mongo
    version: "0.1.0"
    repository: file://mongo
  - alias: postgres
    name: postgres
    version: "0.1.0"
    repository: file://postgres
  - alias: minio
    name: minio
    version: "0.1.0"
    repository: file://minio
  - alias: loki
    name: loki
    version: "0.1.0"
    repository: file://loki
  - alias: promtail
    name: promtail
    version: "0.1.0"
    repository: file://promtail
  - alias: prometheus
    name: prometheus
    version: "0.1.0"
    repository: file://prometheus
  - alias: kibana
    name: kibana
    version: "0.1.0"
    repository: file://kibana
  - alias: elasticsearch
    name: elasticsearch
    version: "0.1.0"
    repository: file://elasticsearch
  - alias: grafana
    name: grafana
    version: "0.1.0"
    repository: file://grafana
  - alias: keycloak
    name: keycloak
    version: "0.1.0"
    repository: file://keycloak
  - alias: kafka
    name: kafka
    version: "0.1.0"
    repository: file://kafka
  - alias: zookeeper
    name: zookeeper
    version: "0.1.0"
    repository: file://zookeeper
  - alias: kafka-ui
    name: kafka-ui
    version: "0.1.0"
    repository: file://kafka-ui
  - alias: kafkaConnect
    name: kafka-connect
    version: "0.1.0"
    repository: file://kafka-connect
  - alias: kafkaConnectMongo
    name: kafka-connect-mongo
    version: "0.1.0"
    repository: file://kafka-connect-mongo
  - alias: mysqlRiver
    name: mysql-river
    version: "0.1.0"
    repository: file://mysql-river
  - alias: rabbitmq
    name: rabbitmq
    version: "0.1.0"
    repository: file://rabbitmq
  - alias: cassandra
    name: cassandra
    version: "0.1.0"
    repository: file://cassandra
  - alias: nats
    name: nats
    version: "0.1.0"
    repository: file://nats
  - alias: ollama
    name: ollama
    version: "0.1.0"
    repository: file://ollama
  - alias: qdrant
    name: qdrant
    version: "0.1.0"
    repository: file://qdrant
  - alias: temporal
    name: temporal
    version: "0.1.0"
    repository: file://temporal
  - alias: admanagement
    name: admanagement
    version: "0.2.0"
    repository: file://admanagement
    condition: admanagement.enabled
  - alias: account-transaction
    name: account-transaction
    version: "0.2.0"
    repository: file://account-transaction
    condition: account-transaction.enabled
  - alias: user
    name: user
    version: "0.2.0"
    repository: file://user
    condition: user.enabled
  - alias: address-country
    name: address-country
    version: "0.2.0"
    repository: file://address-country
    condition: address-country.enabled
  - alias: airflow-service
    name: airflow-service
    version: "0.2.0"
    repository: file://airflow-service
    condition: airflow-service.enabled
  - alias: airflowServer
    name: airflow-server
    version: "0.2.0"
    repository: file://airflow-server
    condition: airflowServer.enabled
  - alias: arrange
    name: arrange-service
    version: "0.2.0"
    repository: file://arrange-service
    condition: arrange.enabled
  - alias: authorize
    name: authorize-service
    version: "0.2.0"
    repository: file://authorize-service
    condition: authorize.enabled
  - alias: automaticPayment
    name: automatic-payment-service
    version: "0.2.0"
    repository: file://automatic-payment-service
    condition: automaticPayment.enabled
  - alias: bankingService
    name: banking-service
    version: "0.2.0"
    repository: file://banking-service
    condition: bankingService.enabled
  - alias: basketService
    name: basket-service
    version: "0.2.0"
    repository: file://basket-service
    condition: basketService.enabled
  - alias: billingService
    name: billing-service
    version: "0.2.0"
    repository: file://billing-service
    condition: billingService.enabled
  - alias: notificationService
    name: notification-service
    version: "0.2.0"
    repository: file://notification-service
    condition: notificationService.enabled
  - alias: bookingMiniService
    name: booking-mini-service
    version: "0.2.0"
    repository: file://booking-mini-service
    condition: bookingMiniService.enabled
  - alias: bookStoreService
    name: book-store-service
    version: "0.2.0"
    repository: file://book-store-service
    condition: bookStoreService.enabled
  - alias: cdnService
    name: cdn-service
    version: "0.2.0"
    repository: file://cdn-service
    condition: cdnService.enabled
  - alias: botService
    name: bot-service
    version: "0.2.0"
    repository: file://bot-service
    condition: botService.enabled
  - alias: livestreamService
    name: livestream-service
    version: "0.2.0"
    repository: file://livestream-service
    condition: livestreamService.enabled
  - alias: livestreamWeb
    name: livestream-web
    version: "0.2.0"
    repository: file://livestream-web
    condition: livestreamWeb.enabled
  - alias: calculate
    name: calculate-service
    version: "0.2.0"
    repository: file://calculate-service
    condition: calculate.enabled
  - alias: geoservice
    name: geoservice
    version: "0.2.0"
    repository: file://geoservice
    condition: geoservice.enabled
  - alias: geoservicePostgres
    name: geoservice-postgres
    version: "0.2.0"
    repository: file://geoservice-postgres
    condition: geoservicePostgres.enabled
  - alias: shortlinkService
    name: shortlink-service
    version: "0.2.0"
    repository: file://shortlink-service
    condition: shortlinkService.enabled
  - alias: lottery
    name: lottery-service
    version: "0.2.0"
    repository: file://lottery-service
    condition: lottery.enabled
  - alias: gatewayService
    name: gateway-service
    version: "0.2.0"
    repository: file://gateway-service
    condition: gatewayService.enabled
  - alias: consumerService
    name: consumer-service
    version: "0.2.0"
    repository: file://consumer-service
    condition: consumerService.enabled
  - alias: accountingService
    name: accounting-service
    version: "0.2.0"
    repository: file://accounting-service
    condition: accountingService.enabled
  - alias: orderService
    name: order-service
    version: "0.2.0"
    repository: file://order-service
    condition: orderService.enabled
  - alias: kitchenService
    name: kitchen-service
    version: "0.2.0"
    repository: file://kitchen-service
    condition: kitchenService.enabled
  - alias: deliveryService
    name: delivery-service
    version: "0.2.0"
    repository: file://delivery-service
    condition: deliveryService.enabled
  - alias: threadsService
    name: threads-service
    version: "0.2.0"
    repository: file://threads-service
    condition: threadsService.enabled
  - alias: postService
    name: post-service
    version: "0.2.0"
    repository: file://post-service
    condition: postService.enabled
  - alias: parkingLotService
    name: parking-lot-service
    version: "0.2.0"
    repository: file://parking-lot-service
    condition: parkingLotService.enabled
  - alias: couponService
    name: coupon-service
    version: "0.2.0"
    repository: file://coupon-service
    condition: couponService.enabled
  - alias: doordashService
    name: doordash-service
    version: "0.2.0"
    repository: file://doordash-service
    condition: doordashService.enabled
  - alias: ekycService
    name: ekyc-service
    version: "0.2.0"
    repository: file://ekyc-service
    condition: ekycService.enabled
  - alias: partnerService
    name: partner-service
    version: "0.2.0"
    repository: file://partner-service
    condition: partnerService.enabled
  - alias: paymentService
    name: payment-service
    version: "0.2.0"
    repository: file://payment-service
    condition: paymentService.enabled
  - alias: polymarketService
    name: polymarket-service
    version: "0.2.0"
    repository: file://polymarket-service
    condition: polymarketService.enabled
  - alias: referralService
    name: referral-service
    version: "0.2.0"
    repository: file://referral-service
    condition: referralService.enabled
  - alias: customerRelationshipService
    name: customer-relationship-service
    version: "0.2.0"
    repository: file://customer-relationship-service
    condition: customerRelationshipService.enabled
  - alias: clamav
    name: clamav
    version: "0.1.0"
    repository: file://clamav
  - alias: bonuslinkService
    name: bonuslink-service
    version: "0.2.0"
    repository: file://bonuslink-service
    condition: bonuslinkService.enabled
  - alias: paymentWalletService
    name: payment-wallet-service
    version: "0.2.0"
    repository: file://payment-wallet-service
    condition: paymentWalletService.enabled
  - alias: videoService
    name: video-service
    version: "0.2.0"
    repository: file://video-service
    condition: videoService.enabled
  - alias: videoWeb
    name: video-web
    version: "0.2.0"
    repository: file://video-web
    condition: videoWeb.enabled
  - alias: roomService
    name: room-service
    version: "0.2.0"
    repository: file://room-service
    condition: roomService.enabled
  - alias: roomWeb
    name: room-web
    version: "0.2.0"
    repository: file://room-web
    condition: roomWeb.enabled
  - alias: hospitalPatientManagementService
    name: hospital-patient-management-service
    version: "0.2.0"
    repository: file://hospital-patient-management-service
    condition: hospitalPatientManagementService.enabled
  - alias: uploadService
    name: upload-service
    version: "0.2.0"
    repository: file://upload-service
    condition: uploadService.enabled
  - alias: carRentalService
    name: car-rental-service
    version: "0.2.0"
    repository: file://car-rental-service
    condition: carRentalService.enabled
  - alias: cataloguesService
    name: catalogues-service
    version: "0.2.0"
    repository: file://catalogues-service
    condition: cataloguesService.enabled
  - alias: movieRecommendationService
    name: movie-recommendation-service
    version: "0.2.0"
    repository: file://movie-recommendation-service
    condition: movieRecommendationService.enabled
  - alias: recompenseService
    name: recompense-service
    version: "0.2.0"
    repository: file://recompense-service
    condition: recompenseService.enabled
  - alias: rentHouseService
    name: rent-house-service
    version: "0.2.0"
    repository: file://rent-house-service
    condition: rentHouseService.enabled
  - alias: reservationService
    name: reservation-service
    version: "0.2.0"
    repository: file://reservation-service
    condition: reservationService.enabled
  - alias: ticketService
    name: ticket-service
    version: "0.2.0"
    repository: file://ticket-service
    condition: ticketService.enabled
  - alias: toolService
    name: tool-service
    version: "0.2.0"
    repository: file://tool-service
    condition: toolService.enabled
  - alias: shopifyService
    name: shopify-service
    version: "0.2.0"
    repository: file://shopify-service
    condition: shopifyService.enabled
  - alias: medicalService
    name: medical-service
    version: "0.2.0"
    repository: file://medical-service
    condition: medicalService.enabled
  - alias: shippingService
    name: shipping-service
    version: "0.2.0"
    repository: file://shipping-service
    condition: shippingService.enabled
  - alias: manageService
    name: manage-service
    version: "0.2.0"
    repository: file://manage-service
    condition: manageService.enabled
  - alias: drawImageService
    name: draw-image-service
    version: "0.2.0"
    repository: file://draw-image-service
    condition: drawImageService.enabled
  - alias: vendingMachineService
    name: vending-machine-service
    version: "0.2.0"
    repository: file://vending-machine-service
    condition: vendingMachineService.enabled
  - alias: webrtcService
    name: webrtc-service
    version: "0.2.0"
    repository: file://webrtc-service
    condition: webrtcService.enabled
  - alias: filterService
    name: filter-service
    version: "0.2.0"
    repository: file://filter-service
    condition: filterService.enabled
  - alias: networkingService
    name: networking-service
    version: "0.2.0"
    repository: file://networking-service
    condition: networkingService.enabled
  - alias: serpapiService
    name: serpapi-service
    version: "0.2.0"
    repository: file://serpapi-service
    condition: serpapiService.enabled
  - alias: aiAgentSystem
    name: ai-agent-system
    version: "0.2.0"
    repository: file://ai-agent-system
    condition: aiAgentSystem.enabled
  - alias: goflowService
    name: goflow-service
    version: "0.2.0"
    repository: file://goflow-service
    condition: goflowService.enabled
  - alias: kmsService
    name: kms-service
    version: "0.2.0"
    repository: file://kms-service
    condition: kmsService.enabled
  - alias: mediaService
    name: media-service
    version: "0.2.0"
    repository: file://media-service
    condition: mediaService.enabled
  - alias: messageService
    name: message-service
    version: "0.2.0"
    repository: file://message-service
    condition: messageService.enabled
  - alias: notifyhubService
    name: notifyhub-service
    version: "0.2.0"
    repository: file://notifyhub-service
    condition: notifyhubService.enabled
  - alias: offerRangeService
    name: offer-range-service
    version: "0.2.0"
    repository: file://offer-range-service
    condition: offerRangeService.enabled
  - alias: ollamaGateway
    name: ollama-gateway
    version: "0.2.0"
    repository: file://ollama-gateway
    condition: ollamaGateway.enabled
  - alias: orderProcessingService
    name: order-processing-service
    version: "0.2.0"
    repository: file://order-processing-service
    condition: orderProcessingService.enabled
  - alias: payerService
    name: payer-service
    version: "0.2.0"
    repository: file://payer-service
    condition: payerService.enabled
  - alias: pointService
    name: point-service
    version: "0.2.0"
    repository: file://point-service
    condition: pointService.enabled
  - alias: realTimeService
    name: real-time-service
    version: "0.2.0"
    repository: file://real-time-service
    condition: realTimeService.enabled
  - alias: searchService
    name: search-service
    version: "0.2.0"
    repository: file://search-service
    condition: searchService.enabled
  - alias: solanaService
    name: solana-service
    version: "0.2.0"
    repository: file://solana-service
    condition: solanaService.enabled
  - alias: ssoService
    name: sso-service
    version: "0.2.0"
    repository: file://sso-service
    condition: ssoService.enabled
  - alias: wishlistsService
    name: wishlists-service
    version: "0.2.0"
    repository: file://wishlists-service
    condition: wishlistsService.enabled
  - alias: sardAuthService
    name: sard-auth-service
    version: "0.2.0"
    repository: file://sard-auth-service
    condition: sardAuthService.enabled
  - alias: sardCustomerInfoService
    name: sard-customer-info-service
    version: "0.2.0"
    repository: file://sard-customer-info-service
    condition: sardCustomerInfoService.enabled
  - alias: sardCardService
    name: sard-card-service
    version: "0.2.0"
    repository: file://sard-card-service
    condition: sardCardService.enabled
  - alias: ollamaModelPy
    name: ollama-model-py
    version: "0.2.0"
    repository: file://ollama-model-py
    condition: ollamaModelPy.enabled
  - alias: identifiedService
    name: identified-service
    version: "0.2.0"
    repository: file://identified-service
    condition: identifiedService.enabled
  - alias: faceRecognitionService
    name: face-recognition-service
    version: "0.2.0"
    repository: file://face-recognition-service
    condition: faceRecognitionService.enabled
  - alias: shareService
    name: share-service
    version: "0.2.0"
    repository: file://share-service
    condition: shareService.enabled
  - alias: foodService
    name: food-service
    version: "0.2.0"
    repository: file://food-service
    condition: foodService.enabled
