airflowServer:
  name: airflow-server

  image:
    name: apache/airflow
    tag: 2.8.1-python3.11

  executor: LocalExecutor

  auth:
    username: airflow
    password: airflow
    firstName: Admin
    lastName: Admin
    email: admin@example.com

  fernetKey: ""

  webserver:
    replicas: 1
    port: 8080
    service:
      name: airflow-webserver-svc
      type: LoadBalancer

  scheduler:
    replicas: 1

  postgres:
    name: airflow-postgres
    db: airflow
    user: airflow
    password: airflow
    port: 5432
    image:
      name: postgres
      tag: "13"
    service:
      name: airflow-postgres-svc

  ingress:
    enabled: false
    className: nginx
    annotations: {}
    host: airflow.local
    path: /
    pathType: Prefix

arrange:
  name: arrange-service
  replicas: 1

  image:
    name: ghcr.io/jieeirosst/arrange-service
    tag: latest
    port: 8080

  service:
    name: arrange-service-svc
    type: LoadBalancer

  ingress:
    enabled: false
    className: nginx
    annotations: {}
    host: arrange-service.local
    path: /
    pathType: Prefix

authorize:
  name: authorize-service
  replicas: 1

  image:
    name: ghcr.io/jieeirosst/authorize-service
    tag: latest
    httpPort: 8080
    grpcPort: 9090

  service:
    httpName: authorize-service-api-svc
    grpcName: authorize-service-grpc-svc
    type: LoadBalancer

  ingress:
    enabled: false
    className: nginx
    annotations: {}
    http:
      host: authorize-service.local
      path: /
      pathType: Prefix
    grpc:
      enabled: false
      host: authorize-service-grpc.local
      path: /
      pathType: Prefix
      annotations: {}

automaticPayment:
  name: automatic-payment-service
  replicas: 1

  image:
    name: ghcr.io/jieeirosst/automatic-payment-service
    tag: latest
    port: 8080

  service:
    name: automatic-payment-service-svc
    type: LoadBalancer

  ingress:
    enabled: false
    className: nginx
    annotations: {}
    host: automatic-payment-service.local
    path: /
    pathType: Prefix

bankingService:
  name: banking-service
  replicas: 1

  image:
    name: ghcr.io/jieeirosst/banking-service
    tag: latest
    port: 3000

  service:
    name: banking-service-svc
    type: LoadBalancer

  ingress:
    enabled: false
    className: nginx
    annotations: {}
    host: banking-service.local
    path: /
    pathType: Prefix
