airflowServer:
  name: airflow-server

  image:
    name: apache/airflow
    tag: 2.8.1-python3.11

  executor: LocalExecutor

  auth:
    username: airflow
    password: airflow
    firstName: Admin
    lastName: Admin
    email: admin@example.com

  fernetKey: ""

  webserver:
    replicas: 1
    port: 8080
    service:
      name: airflow-webserver-svc
      type: LoadBalancer

  scheduler:
    replicas: 1

  postgres:
    name: airflow-postgres
    db: airflow
    user: airflow
    password: airflow
    port: 5432
    image:
      name: postgres
      tag: "13"
    service:
      name: airflow-postgres-svc

  ingress:
    enabled: false
    className: nginx
    annotations: {}
    host: airflow.local
    path: /
    pathType: Prefix

arrange:
  name: arrange-service
  replicas: 1

  image:
    name: ghcr.io/jieeirosst/arrange-service
    tag: latest
    port: 8080

  service:
    name: arrange-service-svc
    type: LoadBalancer

  ingress:
    enabled: false
    className: nginx
    annotations: {}
    host: arrange-service.local
    path: /
    pathType: Prefix
