nginx:
  name: app-nginx
  replicas: 1

  image:
    name: app-nginx
    tag: v1
    port: 80

  service:
    name: app-nginx-loadbalancer-service
    type: LoadBalancer

authorize:
  name: authorize-service
  replicas: 3

  image:
    name: authorize-service
    tag: v1
    port:
      server_port: 1234
      grpc_port: 1231

  service:
    name: authorize-service-clusterip-service
    type: ClusterIP

consul:
  name: consul-service
  replicas: 1

  image:
    name: app-nginx
    tag: v0.6.4 
    port: 
      - tcp_port: 8500 
      - udp_portL: 8600

  service:
    name: consul-clusterip-service
    type: LoadBalancer