nginx:
  name: app-nginx
  replicas: 1

  image:
    name: app-nginx
    tag: v1
    port: 80

  service:
    name: app-nginx-loadbalancer-service
    type: LoadBalancer

authorize:
  name: authorize-service
  replicas: 3

  image:
    name: authorize-service
    tag: v1
    port:
      server_port: 1234
      grpc_port: 1231

  service:
    name: authorize-service-clusterip-service
    type: ClusterIP

consul:
  name: consul-service
  replicas: 1

  image:
    name: app-nginx
    tag: v0.6.4 
    port: 
      - tcp_port: 8500 
      - udp_portL: 8600

  service:
    name: consul-clusterip-service
    type: LoadBalancer

user:
  name: user-service
  replicas: 3

  image:
    name: user-service
    tag: v1
    port:
      server_port: 1235
      grpc_port: 1232

  service:
    name: user-service-clusterip-service
    type: ClusterIP

shop:
  name: shop-service
  replicas: 3

  image:
    name: shop-service
    tag: v1
    port:
      server_port: 1236
      grpc_port: 1233

  service:
    name: user-service-clusterip-service
    type: ClusterIP

book:
  name: book-service
  replicas: 3

  image:
    name: book-service
    tag: v1
    port:
      server_port: 1235
      grpc_port: 1232

  service:
    name: book-service-clusterip-service
    type: ClusterIP

book-store:
  name: book-store-service
  replicas: 3

  image:
    name: book-store-service
    tag: v1
    port:
      server_port: 1236
      grpc_port: 1334

  service:
    name: book-store-service-clusterip-service
    type: ClusterIP

identified:
  name: book-store-service
  replicas: 3

  image:
    name: identified-service
    tag: v1
    port:
      server_port: 1237
      grpc_port: 1335

  service:
    name: identified-service-clusterip-service
    type: ClusterIP
  
notification:
  name: notification-service
  replicas: 3

  image:
    name: notification-service
    tag: v1
    port:
      server_port: 1236
      grpc_port: 1334

  service:
    name: notification-service-clusterip-service
    type: ClusterIP

payment:
  name: payment-service
  replicas: 3

  image:
    name: payment-service
    tag: v1
    port:
      server_port: 1237
      grpc_port: 1335

  service:
    name: payment-service-clusterip-service
    type: ClusterIP

post:
  name: post-service
  replicas: 3

  image:
    name: post-service
    tag: v1
    port:
      server_port: 1238
      grpc_port: 1336

  service:
    name: post-service-clusterip-service
    type: ClusterIP

purchase:
  name: purchase-service
  replicas: 3

  image:
    name: purchase-service
    tag: v1
    port:
      server_port: 1239
      grpc_port: 1337

  service:
    name: purchase-service-clusterip-service
    type: ClusterIP

transaction:
  name: transation-service
  replicas: 3

  image:
    name: transaction-service
    tag: v1
    port:
      server_port: 1240
      grpc_port: 1338

  service:
    name: transaction-service-clusterip-service
    type: ClusterIP

worker:
  name: worker-service
  replicas: 3

  image:
    name: worker-service
    tag: v1
    port:
      server_port: 1241
      grpc_port: 1339

  service:
    name: worker-service-clusterip-service
    type: ClusterIP

namespace: monitoring

prometheus:
  k8-api-server: https://kubernetes.default
  service:
    name: prometheus-svc
    port: 9090
  spec:
    image: prom/prometheus:v2.0.0
    
grafana:
  service:
    name: grafana
  spec:
    image: grafana/grafana:5.2.0
  prometheus:
    endpoint: http://prometheus-svc:9090