apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loki.name }}
  labels:
    app: {{ .Values.loki.name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.loki.service.port | quote }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.loki.service.port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: {{ .Values.loki.name }}
