apiVersion: v1
kind: Service
metadata:
  name: {{.Values.grafana.name}}-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  ports:
  - name: {{.Values.grafana.name}}-service
    port: 80
    targetPort: {{.Values.grafana.image.port}}
  selector:
    app: {{.Values.grafana.name}}-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.grafana.name}}-nodeport
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  type: NodePort
  ports:
  - name: {{.Values.grafana.name}}-nodeport
    port: 80
    targetPort: {{.Values.grafana.image.port}}
    nodePort: {{.Values.grafana.service.nodeport}}
  selector:
    app: {{.Values.grafana.name}}-deployment