package model

import (
	"encoding/json"

	"github.com/JIeeiroSst/workflow-service/pkg/excel"
)

type BestSellingPlayStation struct {
	Game        string
	CopiesSold  string
	ReleaseDate string
	Genre       string
	Developer   string
	Publisher   string
}

func (bestSellingPlayStation BestSellingPlayStation) Format(generated []excel.AutoGenerated) []byte {
	for _, value := range generated {
		for i := 0; i < len(value.Values); i++ {
			switch i {
			case 1:
				bestSellingPlayStation.Game = value.Values[i].UserEnteredValue.StringValue
			case 2:
				bestSellingPlayStation.CopiesSold = value.Values[i].UserEnteredValue.StringValue
			case 3:
				bestSellingPlayStation.ReleaseDate = value.Values[i].UserEnteredValue.StringValue
			case 4:
				bestSellingPlayStation.ReleaseDate = value.Values[i].UserEnteredValue.StringValue
			case 5:
				bestSellingPlayStation.Developer = value.Values[i].UserEnteredValue.StringValue
			case 6:
				bestSellingPlayStation.Publisher = value.Values[i].UserEnteredValue.StringValue
			}
		}
	}
	bestSellingPlayStationJson, err := json.Marshal(&bestSellingPlayStation)
	if err != nil {
		return nil
	}
	return bestSellingPlayStationJson
}
