package model

import (
	"encoding/json"

	"github.com/JIeeiroSst/workflow-service/pkg/excel"
)

type SeattleWeather struct {
	Date          string
	Precipitation string
	TempMax       string
	TempMin       string
	Wind          string
	Weather       string
}

func (seattleWeather SeattleWeather) Format(generated []excel.AutoGenerated) []byte {
	for _, value := range generated {
		for i := 0; i < len(value.Values); i++ {
			switch i {
			case 1:
				seattleWeather.Date = value.Values[i].UserEnteredValue.StringValue
			case 2:
				seattleWeather.Precipitation = value.Values[i].UserEnteredValue.StringValue
			case 3:
				seattleWeather.TempMax = value.Values[i].UserEnteredValue.StringValue
			case 4:
				seattleWeather.TempMin = value.Values[i].UserEnteredValue.StringValue
			case 5:
				seattleWeather.Wind = value.Values[i].UserEnteredValue.StringValue
			case 6:
				seattleWeather.Weather = value.Values[i].UserEnteredValue.StringValue
			}
		}
	}
	seattleWeatherJson, err := json.Marshal(&seattleWeather)
	if err != nil {
		return nil
	}
	return seattleWeatherJson
}
