package model

import (
	"encoding/json"

	"github.com/JIeeiroSst/workflow-service/pkg/excel"
)

type SpotifyQuarterly struct {
	Date                       string
	TotalRevenue               int
	CostOfRevenue              int
	GrossProfit                int
	PremiumRevenue             int
	PremiumCostRevenue         int
	PremiumGrossProfit         int
	AdRevenue                  int
	AdCostOfRevenue            int
	AdGrossProfit              int
	MAUs                       int
	PremiumMAUs                int
	AdMAUs                     int
	PremiumARPU                string
	SalesAndMarketingCost      int
	ResearchAndDevelopmentCost int
	GenrealAndAdminstraiveCost int
}

func (spotifyQuarterly SpotifyQuarterly) Format(generated []excel.AutoGenerated) []byte {

	spotifyQuarterlyJson, err := json.Marshal(&spotifyQuarterly)
	if err != nil {
		return nil
	}
	return spotifyQuarterlyJson
}
