package model

import (
	"github.com/JIeeiroSst/workflow-service/internal/activities/approve/common"
	"github.com/JIeeiroSst/workflow-service/pkg/excel"
)

func Format(generated []excel.AutoGenerated, types string) []byte {
	var bytes []byte
	switch types {
	case common.SpotifyQuarterlyType:
		var spotifyQuarterly SpotifyQuarterly
		bytes = spotifyQuarterly.Format(generated)
	case common.SeattleWeatherType:
		var seattleWeather SeattleWeather
		bytes = seattleWeather.Format(generated)
	case common.BestSellingPlayStationType:
		var bestSellingPlayStation BestSellingPlayStation
		bytes = bestSellingPlayStation.Format(generated)
	case common.GamesType:
		var game Game
		bytes = game.Format(generated)
	}

	return bytes
}
