apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  ports:
  - port: 80
    targetPort: 5432
  selector:
    app: postgresql-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5432
    nodePort: 31000
  selector:
    app: postgresql-deployment