apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.ports.targetPort }}
  selector:
    app: postgresql-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: {{ .Values.ports.targetPort }}
    nodePort: {{ .Values.ports.nodePort }}
  selector:
    app: postgresql-deployment