apiVersion: v2
name: app-cluster
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - alias: consul
    name: consul
    version: "0.1.0"
    repository: file://consul
  - alias: nats
    name: nats
    version: "0.1.0"
    repository: file://nats