apiVersion: v1
kind: ConfigMap
metadata:
  name: db-secret-credentials
  labels:
    app: {{ .Values.postgres.name }}
data:
  POSTGRES_DB: {{ .Values.postgres.credentials.database }}
  POSTGRES_USER: {{ .Values.postgres.credentials.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password }}
