apiVersion: v1
kind: Service
metadata:
  name: {{.Values.consul.name}}-service
spec:
  ports:
  - port: 80
    targetPort: {{.Values.consul.image.port}}
  selector:
    app: {{.Values.consul.name}}-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.consul.name}}-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: {{.Values.consul.image.port}}
    nodePort: {{.Values.consul.service.nodeport}}
  selector:
    app: {{.Values.consul.name}}-deployment