apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.mysql.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.mysql.name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.mysql.name}}
    spec:
      containers:
        - image: {{.Values.mysql.image.name}}:{{.Values.mysql.image.tag}}
          name: {{.Values.mysql.name}}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{.Values.mysql.env.password}}
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: {{.Values.mysql.image.port}}
              name: mysql   