apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mysql.service.name}}
spec:
  ports:
    - port: 80
      targetPort: {{.Values.mysql.image.port}}
  selector:
    app: {{.Values.mysql.name}}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3306
    nodePort: 32003
  selector:
    app: {{.Values.mysql.name}}