apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 80
    targetPort: 3306
  selector:
    app: mysql-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3306
    nodePort: 32003
  selector:
    app: mysql-deployment