apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafkaUi.name }}
  labels:
    app: {{ .Values.kafkaUi.name }}
spec:
  replicas: {{ .Values.kafkaUi.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.kafkaUi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafkaUi.name }}
    spec:
      containers:
      - name: {{ .Values.kafkaUi.name }}
        image: {{ .Values.kafkaUi.image.repository }}:{{ .Values.kafkaUi.image.tag }}
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: {{ .Values.kafkaUi.clusterName | quote }}
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: {{ .Values.kafkaUi.bootstrapServers }}
        imagePullPolicy: {{ .Values.kafkaUi.image.pullPolicy }}
        resources:
          {{- toYaml .Values.kafkaUi.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.kafkaUi.service.targetPort }}
          protocol: TCP
