apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: kafka-ui-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
  selector:
    app: kafka-ui-deployment
