apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 8080
  selector:
    app: kafka-ui-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
spec:
  type: NodePort
  ports:
    - port: 80
    targetPort: 8080
    nodePort: 8080
  selector:
    app: kafka-ui-deployment
