apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafkaUi.service.name }}
spec:
  ports:
    - port: {{ .Values.kafkaUi.service.port }}
      targetPort: {{ .Values.kafkaUi.service.targetPort }}
  selector:
    app: {{ .Values.kafkaUi.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafkaUi.service.nodeportName }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.kafkaUi.service.port }}
      targetPort: {{ .Values.kafkaUi.service.targetPort }}
      nodePort: {{ .Values.kafkaUi.service.nodePort }}
  selector:
    app: {{ .Values.kafkaUi.name }}
