apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-deployment
  template:
    metadata:
      labels:
        app: consul-deployment
    spec:
      containers:
      - name: consul-deployment
        image: hashicorp/consul:1.11.2
        ports:
        - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: consul-svc
spec:
  ports:
  - port: 80
    targetPort: 8500
  selector:
    app: consul-deployment
