apiVersion: v1
kind: Pod
metadata:
  name: consul-example
spec:
  containers:
    - name: example
      image: 'consul:latest'
          env:
            - name: NODE_ENV
              value: production
  restartPolicy: Never

