apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.consul.name }}
spec:
  containers:
    - name: {{ .Values.consul.containers }}
      image: {{ .Values.consul.image }}
      env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      command: 
            - '/bin/sh'
            - '-ec'
            - |
              export CONSUL_HTTP_ADDR="${HOST_IP}:8500"
  restartPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.consul.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.consul.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.consul.name }}
    spec:
      containers:
        - name: {{ .Values.consul.containers }}
          image: {{ .Values.consul.image }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          command: 
            - '/bin/sh'
            - '-ec'
            - |
              export CONSUL_HTTP_ADDR="${HOST_IP}:8500"          
