apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-service
  template:
    metadata:
      labels:
        app: consul-service
    spec:
      containers:
        - name: consul-service
          image: consul:latest
          env:
            - name: NODE_ENV
              value: production

