apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.consul.name}}-deployment
spec:
  replicas: {{.Values.consul.replicas}}
  selector:
    matchLabels:
      app: {{.Values.consul.name}}-deployment
  template:
    metadata:
      labels:
        app: {{.Values.consul.name}}-deployment
    spec:
      containers:
      - name: {{.Values.consul.name}}-deployment
        image: {{.Values.consul.image.name}}:{{.Values.consul.image.tag}}
        ports:
        - containerPort: {{.Values.consul.image.port}}
        env:
            - name: NODE_ENV
              value: production
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.consul.service.name}}
spec:
  ports:
  - port: 80
    targetPort: {{.Values.consul.image.port}}
  selector:
    app: {{.Values.consul.name}}-deployment
