apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
        app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsGroup: 65534
        runAsUser: 65534
      containers:
      - name: grafana
        image: docker.io/grafana/grafana:9.3.2
        imagePullPolicy: IfNotPresent
        env:
        - name: GF_EXPLORE_ENABLED
          value: "true"
        - name: LOKI_ADDR
          value: "http://loki:3100"
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: "512Mi"
          limits:
            cpu: 200m
            memory: "1Gi"
        volumeMounts:
          - name: grafana-storage
            mountPath: /var/lib/grafana
          - name: grafana-datastore
            mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
            subPath: datasource.yaml
            readOnly: false
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
      volumes:
        - name: grafana-datastore
          configMap:
            name: grafana-datasource
        - name: grafana-storage
          emptyDir:
            sizeLimit: "1Gi"
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: grafana-datasource
    labels:
      app.kubernetes.io/name: grafana
      grafana_datasource: '1'
data:
    datasource.yaml: |-
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus:9090
  
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          maxLines: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana