apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.mongo.name}}-deployment   
spec:
  selector:
    matchLabels:
      app: {{.Values.mongo.name}}-deployment   
  template:  
    metadata:
      labels:
        app: {{.Values.mongo.name}}-deployment   
    spec:
      containers:     
      - image: {{.Values.mongo.image.name}}
        name: mongodb
        ports:
        - containerPort: {{.Values.mongo.image.port}}      
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            value: production
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mongo.service.name}}
spec:
  ports:
    - port: 80
      targetPort: {{.Values.mongo.image.port}}
  selector:
    app: {{.Values.mongo.name}}-deployment   
