apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      app: mongo-deployment
  template:  
    metadata:
      labels:
        app: mongo-deployment   
    spec:
      containers:     
      - image: mongo
        name: mongodb       
        ports:
        - containerPort: 27017      
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  ports:
    - port: 80
      targetPort: 27017
  selector:
    app: mongo-deployment    