apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:  
    metadata:
      labels:
        app: mongodb        
    spec:
      containers:     
      - image: mongo
        name: mongodb       
        ports:
        - containerPort: 27017      
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
  type: LoadBalancer  
  selector:
    app: mongodb      