apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
spec:
  ports:
  - port: {{ .Values.mysql.port }}
  selector:
    app: {{ .Values.mysql.name }}
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
      - image: {{ .Values.mysql.image }}
        name: {{ .Values.mysql.name }}
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.password }}
        ports:
        - containerPort: {{ .Values.mysql.port }}
          name: {{ .Values.mysql.name }}
        volumeMounts:
        - name: {{ .Values.mysql.name }}-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: {{ .Values.mysql.name }}-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mysql.name }}-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.name }}-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi