apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.nginx.name}}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      server: {{ .Values.nginx.name }}
  template:
    metadata:
      labels:
        server: {{ .Values.nginx.name }}
    spec:
      containers:
        - name: {{ .Values.nginx.name }}
          image: {{ .Values.nginx.image.name }}:{{ .Values.nginx.image.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.nginx.image.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.service.name }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.nginx.image.port }}
  selector:
    server: {{ .Values.nginx.name }}