apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.name }}-config
  labels:
    app: {{ .Values.postgres.name }}
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: psltest
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.postgres.name }}-pv-volume  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: {{ .Values.postgres.name }}
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.postgres.name }}-pv-claim  # Sets name of PVC
  labels:
    app: {{ .Values.postgres.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
        - name: {{ .Values.postgres.name }}
          image: {{ .Values.postgres.image }} # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: {{ .Values.postgres.port }}  # Exposes container port
          envFrom:
            - configMapRef:
                name: {{ .Values.postgres.name }}-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }} # Sets service name
  labels:
    app: {{ .Values.postgres.name }} # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: {{ .Values.postgres.port }}
     # Sets port to run the postgres application
  selector:
    app: {{ .Values.postgres.name }}