apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.userApi.name}}-deployment
spec:
  replicas: {{.Values.userApi.replicas}}
  selector:
    matchLabels:
      app: {{.Values.userApi.name}}-deployment
  template:
    metadata:
      labels:
        app: {{.Values.userApi.name}}-deployment
    spec:
      containers:
      - name: {{.Values.userApi.name}}-deployment
        image: {{.Values.userApi.image.name}}:{{.Values.userApi.image.tag}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{.Values.userApi.image.port}}
        env:
          - name: NODE_ENV
            value: production
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.userApi.service.name}}
spec:
  ports:
  - port: 80
    targetPort: {{.Values.userApi.image.port}}
  selector:
    app: {{.Values.userApi.name}}-deployment
