apiVersion: v1
kind: Secret
metadata:
  name: user-service-config
type: Opaque
stringData:
  HostConsul: {{ .Values.env.hostConsul | quote }}
  KeyConsul: {{ .Values.env.keyConsul | quote }}
  ServiceConsul: {{ .Values.env.serviceConsul | quote }}
  JwtSecretKey: {{ .Values.env.jwtSecretKey | quote }}
