apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.userGrpc.name}}-deployment
spec:
  replicas: {{.Values.userGrpc.replicas}}
  selector:
    matchLabels:
      app: {{.Values.userGrpc.name}}-deployment
  template:
    metadata:
      labels:
        app: {{.Values.userGrpc.name}}-deployment
    spec:
      containers:
      - name: {{.Values.userGrpc.name}}-deployment
        image: {{.Values.userGrpc.image.name}}:{{.Values.userGrpc.image.tag}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{.Values.userGrpc.image.port}}
        envFrom:
          - secretRef:
              name: user-service-config
        volumeMounts:
        - name: env-file
          mountPath: /app/.env
          subPath: user-service.env
        livenessProbe:
          tcpSocket:
            port: {{.Values.userGrpc.image.port}}
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: {{.Values.userGrpc.image.port}}
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.userGrpc.resources | nindent 10 }}
      volumes:
      - name: env-file
        secret:
          secretName: service-env-files
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.userGrpc.service.name}}
spec:
  ports:
  - port: 80
    targetPort: {{.Values.userGrpc.image.port}}
  selector:
    app: {{.Values.userGrpc.name}}-deployment
