apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.name }}
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.name }}
    spec:
      containers:
      - name: {{ .Values.rabbitmq.name }}
        image: {{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}
        ports:
          - name: http
            protocol: TCP
            containerPort: {{ .Values.rabbitmq.service.httpPort }}
          - name: amqp
            protocol: TCP
            containerPort: {{ .Values.rabbitmq.service.amqpPort }}
        imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
        env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-config
                key: RABBIT_USERNAME
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: rabbitmq-config
                key: RABBIT_PASSWORD
