kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.rabbitmq.service.name }}
spec:
  type: NodePort
  ports:
   - name: http
     protocol: TCP
     port: {{ .Values.rabbitmq.service.httpPort }}
     targetPort: {{ .Values.rabbitmq.service.httpPort }}
     nodePort: {{ .Values.rabbitmq.service.httpNodePort }}
   - name: amqp
     protocol: TCP
     port: {{ .Values.rabbitmq.service.amqpPort }}
     targetPort: {{ .Values.rabbitmq.service.amqpPort }}
     nodePort: {{ .Values.rabbitmq.service.amqpNodePort }}
  selector:
    app: {{ .Values.rabbitmq.name }}
