apiVersion: v2
name: kafka-connect-mongo
description: Kafka Connect (Debezium MongoDB source + Elasticsearch sink) for syncing MongoDB to Elasticsearch

type: application
version: 0.1.0
appVersion: "2.6.0"
