# Books schema
#
# Written for PostgreSQL (the cluster database) and kept to syntax H2 also
# accepts, so tests and `sbt run` work without a server. Play splits
# statements on semicolons, even inside comments and strings: never use one
# except to end a statement.

# --- !Ups

CREATE TABLE books (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title              VARCHAR(255)  NOT NULL,
  author             VARCHAR(255)  NOT NULL,
  isbn               VARCHAR(13),
  description        VARCHAR(4000),
  published_year     INT,
  -- Cover image object in MinIO, NULL when the book has no cover.
  cover_key          VARCHAR(512),
  cover_content_type VARCHAR(100),
  created_at         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_books_isbn UNIQUE (isbn)
);

CREATE INDEX ix_books_author ON books (author);
CREATE INDEX ix_books_published_year ON books (published_year);

CREATE TABLE categories (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(64)  NOT NULL,
  name VARCHAR(128) NOT NULL,
  CONSTRAINT uq_categories_slug UNIQUE (slug)
);

CREATE TABLE book_categories (
  book_id     BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  PRIMARY KEY (book_id, category_id),
  CONSTRAINT fk_book_categories_book FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE,
  CONSTRAINT fk_book_categories_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
);

-- Serves "books in category X, newest first" with the cursor on book_id.
CREATE INDEX ix_book_categories_category ON book_categories (category_id, book_id);

-- Chapter text is an object in MinIO (content_key) and only metadata lives
-- here. (book_id, chapter_number) is the cursor key for content pagination.
CREATE TABLE book_chapters (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id        BIGINT       NOT NULL,
  chapter_number INT          NOT NULL,
  title          VARCHAR(255) NOT NULL,
  content_key    VARCHAR(512) NOT NULL,
  content_type   VARCHAR(100) NOT NULL DEFAULT 'text/plain',
  size_bytes     BIGINT,
  updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_book_chapters_book FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE,
  CONSTRAINT uq_book_chapters_book_number UNIQUE (book_id, chapter_number)
);

# --- !Downs

DROP TABLE IF EXISTS book_chapters;
DROP TABLE IF EXISTS book_categories;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS books;
