rabbitmq:
  name: rabbitmq-deployment
  replicas: 1

  image:
    repository: rabbitmq
    tag: "3.8"
    pullPolicy: Always

  auth:
    username: admin
    password: admin

  service:
    name: rabbitmq-service
    httpPort: 15672
    httpNodePort: 31673
    amqpPort: 5672
    amqpNodePort: 30673
