// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: proto/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CouponService_CreateCoupon_FullMethodName                                = "/coupon.CouponService/CreateCoupon"
	CouponService_GetCoupon_FullMethodName                                   = "/coupon.CouponService/GetCoupon"
	CouponService_UpdateCoupon_FullMethodName                                = "/coupon.CouponService/UpdateCoupon"
	CouponService_DeleteCoupon_FullMethodName                                = "/coupon.CouponService/DeleteCoupon"
	CouponService_ListCoupons_FullMethodName                                 = "/coupon.CouponService/ListCoupons"
	CouponService_CreateCouponRestriction_FullMethodName                     = "/coupon.CouponService/CreateCouponRestriction"
	CouponService_GetCouponRestriction_FullMethodName                        = "/coupon.CouponService/GetCouponRestriction"
	CouponService_UpdateCouponRestriction_FullMethodName                     = "/coupon.CouponService/UpdateCouponRestriction"
	CouponService_DeleteCouponRestriction_FullMethodName                     = "/coupon.CouponService/DeleteCouponRestriction"
	CouponService_ListCouponRestrictions_FullMethodName                      = "/coupon.CouponService/ListCouponRestrictions"
	CouponService_CreateUserCoupon_FullMethodName                            = "/coupon.CouponService/CreateUserCoupon"
	CouponService_GetUserCoupon_FullMethodName                               = "/coupon.CouponService/GetUserCoupon"
	CouponService_ListUserCoupons_FullMethodName                             = "/coupon.CouponService/ListUserCoupons"
	CouponService_UseUserCoupon_FullMethodName                               = "/coupon.CouponService/UseUserCoupon"
	CouponService_UnuseUserCoupon_FullMethodName                             = "/coupon.CouponService/UnuseUserCoupon"
	CouponService_ListCouponUsages_FullMethodName                            = "/coupon.CouponService/ListCouponUsages"
	CouponService_ListUserCouponUsages_FullMethodName                        = "/coupon.CouponService/ListUserCouponUsages"
	CouponService_ListUserCouponUsagesByOrder_FullMethodName                 = "/coupon.CouponService/ListUserCouponUsagesByOrder"
	CouponService_ListUserCouponUsagesByCoupon_FullMethodName                = "/coupon.CouponService/ListUserCouponUsagesByCoupon"
	CouponService_ListUserCouponUsagesByOrderAndCoupon_FullMethodName        = "/coupon.CouponService/ListUserCouponUsagesByOrderAndCoupon"
	CouponService_ListUserCouponUsagesByOrderAndCouponAndUser_FullMethodName = "/coupon.CouponService/ListUserCouponUsagesByOrderAndCouponAndUser"
	CouponService_ListUserCouponUsagesByOrderAndUser_FullMethodName          = "/coupon.CouponService/ListUserCouponUsagesByOrderAndUser"
	CouponService_ListUserCouponUsagesByCouponAndUser_FullMethodName         = "/coupon.CouponService/ListUserCouponUsagesByCouponAndUser"
	CouponService_ListUserCouponUsagesByUser_FullMethodName                  = "/coupon.CouponService/ListUserCouponUsagesByUser"
	CouponService_ListUserCouponUsagesByOrderAndUserAndCoupon_FullMethodName = "/coupon.CouponService/ListUserCouponUsagesByOrderAndUserAndCoupon"
)

// CouponServiceClient is the client API for CouponService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CouponServiceClient interface {
	CreateCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*Coupon, error)
	GetCoupon(ctx context.Context, in *GetCouponRequest, opts ...grpc.CallOption) (*Coupon, error)
	UpdateCoupon(ctx context.Context, in *UpdateCouponRequest, opts ...grpc.CallOption) (*Coupon, error)
	DeleteCoupon(ctx context.Context, in *DeleteCouponRequest, opts ...grpc.CallOption) (*DeleteCouponResponse, error)
	ListCoupons(ctx context.Context, in *ListCouponsRequest, opts ...grpc.CallOption) (*ListCouponsResponse, error)
	CreateCouponRestriction(ctx context.Context, in *CreateCouponRestrictionRequest, opts ...grpc.CallOption) (*CouponRestriction, error)
	GetCouponRestriction(ctx context.Context, in *GetCouponRestrictionRequest, opts ...grpc.CallOption) (*CouponRestriction, error)
	UpdateCouponRestriction(ctx context.Context, in *UpdateCouponRestrictionRequest, opts ...grpc.CallOption) (*CouponRestriction, error)
	DeleteCouponRestriction(ctx context.Context, in *DeleteCouponRestrictionRequest, opts ...grpc.CallOption) (*DeleteCouponRestrictionResponse, error)
	ListCouponRestrictions(ctx context.Context, in *ListCouponRestrictionsRequest, opts ...grpc.CallOption) (*ListCouponRestrictionsResponse, error)
	CreateUserCoupon(ctx context.Context, in *CreateUserCouponRequest, opts ...grpc.CallOption) (*UserCoupon, error)
	GetUserCoupon(ctx context.Context, in *GetUserCouponRequest, opts ...grpc.CallOption) (*UserCoupon, error)
	ListUserCoupons(ctx context.Context, in *ListUserCouponsRequest, opts ...grpc.CallOption) (*ListUserCouponsResponse, error)
	UseUserCoupon(ctx context.Context, in *UseUserCouponRequest, opts ...grpc.CallOption) (*UserCoupon, error)
	UnuseUserCoupon(ctx context.Context, in *UnuseUserCouponRequest, opts ...grpc.CallOption) (*UserCoupon, error)
	ListCouponUsages(ctx context.Context, in *ListCouponUsagesRequest, opts ...grpc.CallOption) (*ListCouponUsagesResponse, error)
	ListUserCouponUsages(ctx context.Context, in *ListUserCouponUsagesRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesResponse, error)
	ListUserCouponUsagesByOrder(ctx context.Context, in *ListUserCouponUsagesByOrderRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByOrderResponse, error)
	ListUserCouponUsagesByCoupon(ctx context.Context, in *ListUserCouponUsagesByCouponRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByCouponResponse, error)
	ListUserCouponUsagesByOrderAndCoupon(ctx context.Context, in *ListUserCouponUsagesByOrderAndCouponRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByOrderAndCouponResponse, error)
	ListUserCouponUsagesByOrderAndCouponAndUser(ctx context.Context, in *ListUserCouponUsagesByOrderAndCouponAndUserRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByOrderAndCouponAndUserResponse, error)
	ListUserCouponUsagesByOrderAndUser(ctx context.Context, in *ListUserCouponUsagesByOrderAndUserRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByOrderAndUserResponse, error)
	ListUserCouponUsagesByCouponAndUser(ctx context.Context, in *ListUserCouponUsagesByCouponAndUserRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByCouponAndUserResponse, error)
	ListUserCouponUsagesByUser(ctx context.Context, in *ListUserCouponUsagesByUserRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByUserResponse, error)
	ListUserCouponUsagesByOrderAndUserAndCoupon(ctx context.Context, in *ListUserCouponUsagesByOrderAndUserAndCouponRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByOrderAndUserAndCouponResponse, error)
}

type couponServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCouponServiceClient(cc grpc.ClientConnInterface) CouponServiceClient {
	return &couponServiceClient{cc}
}

func (c *couponServiceClient) CreateCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*Coupon, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Coupon)
	err := c.cc.Invoke(ctx, CouponService_CreateCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) GetCoupon(ctx context.Context, in *GetCouponRequest, opts ...grpc.CallOption) (*Coupon, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Coupon)
	err := c.cc.Invoke(ctx, CouponService_GetCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) UpdateCoupon(ctx context.Context, in *UpdateCouponRequest, opts ...grpc.CallOption) (*Coupon, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Coupon)
	err := c.cc.Invoke(ctx, CouponService_UpdateCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) DeleteCoupon(ctx context.Context, in *DeleteCouponRequest, opts ...grpc.CallOption) (*DeleteCouponResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCouponResponse)
	err := c.cc.Invoke(ctx, CouponService_DeleteCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListCoupons(ctx context.Context, in *ListCouponsRequest, opts ...grpc.CallOption) (*ListCouponsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCouponsResponse)
	err := c.cc.Invoke(ctx, CouponService_ListCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) CreateCouponRestriction(ctx context.Context, in *CreateCouponRestrictionRequest, opts ...grpc.CallOption) (*CouponRestriction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponRestriction)
	err := c.cc.Invoke(ctx, CouponService_CreateCouponRestriction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) GetCouponRestriction(ctx context.Context, in *GetCouponRestrictionRequest, opts ...grpc.CallOption) (*CouponRestriction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponRestriction)
	err := c.cc.Invoke(ctx, CouponService_GetCouponRestriction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) UpdateCouponRestriction(ctx context.Context, in *UpdateCouponRestrictionRequest, opts ...grpc.CallOption) (*CouponRestriction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponRestriction)
	err := c.cc.Invoke(ctx, CouponService_UpdateCouponRestriction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) DeleteCouponRestriction(ctx context.Context, in *DeleteCouponRestrictionRequest, opts ...grpc.CallOption) (*DeleteCouponRestrictionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCouponRestrictionResponse)
	err := c.cc.Invoke(ctx, CouponService_DeleteCouponRestriction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListCouponRestrictions(ctx context.Context, in *ListCouponRestrictionsRequest, opts ...grpc.CallOption) (*ListCouponRestrictionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCouponRestrictionsResponse)
	err := c.cc.Invoke(ctx, CouponService_ListCouponRestrictions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) CreateUserCoupon(ctx context.Context, in *CreateUserCouponRequest, opts ...grpc.CallOption) (*UserCoupon, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCoupon)
	err := c.cc.Invoke(ctx, CouponService_CreateUserCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) GetUserCoupon(ctx context.Context, in *GetUserCouponRequest, opts ...grpc.CallOption) (*UserCoupon, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCoupon)
	err := c.cc.Invoke(ctx, CouponService_GetUserCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListUserCoupons(ctx context.Context, in *ListUserCouponsRequest, opts ...grpc.CallOption) (*ListUserCouponsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserCouponsResponse)
	err := c.cc.Invoke(ctx, CouponService_ListUserCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) UseUserCoupon(ctx context.Context, in *UseUserCouponRequest, opts ...grpc.CallOption) (*UserCoupon, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCoupon)
	err := c.cc.Invoke(ctx, CouponService_UseUserCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) UnuseUserCoupon(ctx context.Context, in *UnuseUserCouponRequest, opts ...grpc.CallOption) (*UserCoupon, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCoupon)
	err := c.cc.Invoke(ctx, CouponService_UnuseUserCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListCouponUsages(ctx context.Context, in *ListCouponUsagesRequest, opts ...grpc.CallOption) (*ListCouponUsagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCouponUsagesResponse)
	err := c.cc.Invoke(ctx, CouponService_ListCouponUsages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListUserCouponUsages(ctx context.Context, in *ListUserCouponUsagesRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserCouponUsagesResponse)
	err := c.cc.Invoke(ctx, CouponService_ListUserCouponUsages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListUserCouponUsagesByOrder(ctx context.Context, in *ListUserCouponUsagesByOrderRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserCouponUsagesByOrderResponse)
	err := c.cc.Invoke(ctx, CouponService_ListUserCouponUsagesByOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListUserCouponUsagesByCoupon(ctx context.Context, in *ListUserCouponUsagesByCouponRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByCouponResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserCouponUsagesByCouponResponse)
	err := c.cc.Invoke(ctx, CouponService_ListUserCouponUsagesByCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListUserCouponUsagesByOrderAndCoupon(ctx context.Context, in *ListUserCouponUsagesByOrderAndCouponRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByOrderAndCouponResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserCouponUsagesByOrderAndCouponResponse)
	err := c.cc.Invoke(ctx, CouponService_ListUserCouponUsagesByOrderAndCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListUserCouponUsagesByOrderAndCouponAndUser(ctx context.Context, in *ListUserCouponUsagesByOrderAndCouponAndUserRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByOrderAndCouponAndUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserCouponUsagesByOrderAndCouponAndUserResponse)
	err := c.cc.Invoke(ctx, CouponService_ListUserCouponUsagesByOrderAndCouponAndUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListUserCouponUsagesByOrderAndUser(ctx context.Context, in *ListUserCouponUsagesByOrderAndUserRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByOrderAndUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserCouponUsagesByOrderAndUserResponse)
	err := c.cc.Invoke(ctx, CouponService_ListUserCouponUsagesByOrderAndUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListUserCouponUsagesByCouponAndUser(ctx context.Context, in *ListUserCouponUsagesByCouponAndUserRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByCouponAndUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserCouponUsagesByCouponAndUserResponse)
	err := c.cc.Invoke(ctx, CouponService_ListUserCouponUsagesByCouponAndUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListUserCouponUsagesByUser(ctx context.Context, in *ListUserCouponUsagesByUserRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserCouponUsagesByUserResponse)
	err := c.cc.Invoke(ctx, CouponService_ListUserCouponUsagesByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListUserCouponUsagesByOrderAndUserAndCoupon(ctx context.Context, in *ListUserCouponUsagesByOrderAndUserAndCouponRequest, opts ...grpc.CallOption) (*ListUserCouponUsagesByOrderAndUserAndCouponResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserCouponUsagesByOrderAndUserAndCouponResponse)
	err := c.cc.Invoke(ctx, CouponService_ListUserCouponUsagesByOrderAndUserAndCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CouponServiceServer is the server API for CouponService service.
// All implementations must embed UnimplementedCouponServiceServer
// for forward compatibility.
type CouponServiceServer interface {
	CreateCoupon(context.Context, *CreateCouponRequest) (*Coupon, error)
	GetCoupon(context.Context, *GetCouponRequest) (*Coupon, error)
	UpdateCoupon(context.Context, *UpdateCouponRequest) (*Coupon, error)
	DeleteCoupon(context.Context, *DeleteCouponRequest) (*DeleteCouponResponse, error)
	ListCoupons(context.Context, *ListCouponsRequest) (*ListCouponsResponse, error)
	CreateCouponRestriction(context.Context, *CreateCouponRestrictionRequest) (*CouponRestriction, error)
	GetCouponRestriction(context.Context, *GetCouponRestrictionRequest) (*CouponRestriction, error)
	UpdateCouponRestriction(context.Context, *UpdateCouponRestrictionRequest) (*CouponRestriction, error)
	DeleteCouponRestriction(context.Context, *DeleteCouponRestrictionRequest) (*DeleteCouponRestrictionResponse, error)
	ListCouponRestrictions(context.Context, *ListCouponRestrictionsRequest) (*ListCouponRestrictionsResponse, error)
	CreateUserCoupon(context.Context, *CreateUserCouponRequest) (*UserCoupon, error)
	GetUserCoupon(context.Context, *GetUserCouponRequest) (*UserCoupon, error)
	ListUserCoupons(context.Context, *ListUserCouponsRequest) (*ListUserCouponsResponse, error)
	UseUserCoupon(context.Context, *UseUserCouponRequest) (*UserCoupon, error)
	UnuseUserCoupon(context.Context, *UnuseUserCouponRequest) (*UserCoupon, error)
	ListCouponUsages(context.Context, *ListCouponUsagesRequest) (*ListCouponUsagesResponse, error)
	ListUserCouponUsages(context.Context, *ListUserCouponUsagesRequest) (*ListUserCouponUsagesResponse, error)
	ListUserCouponUsagesByOrder(context.Context, *ListUserCouponUsagesByOrderRequest) (*ListUserCouponUsagesByOrderResponse, error)
	ListUserCouponUsagesByCoupon(context.Context, *ListUserCouponUsagesByCouponRequest) (*ListUserCouponUsagesByCouponResponse, error)
	ListUserCouponUsagesByOrderAndCoupon(context.Context, *ListUserCouponUsagesByOrderAndCouponRequest) (*ListUserCouponUsagesByOrderAndCouponResponse, error)
	ListUserCouponUsagesByOrderAndCouponAndUser(context.Context, *ListUserCouponUsagesByOrderAndCouponAndUserRequest) (*ListUserCouponUsagesByOrderAndCouponAndUserResponse, error)
	ListUserCouponUsagesByOrderAndUser(context.Context, *ListUserCouponUsagesByOrderAndUserRequest) (*ListUserCouponUsagesByOrderAndUserResponse, error)
	ListUserCouponUsagesByCouponAndUser(context.Context, *ListUserCouponUsagesByCouponAndUserRequest) (*ListUserCouponUsagesByCouponAndUserResponse, error)
	ListUserCouponUsagesByUser(context.Context, *ListUserCouponUsagesByUserRequest) (*ListUserCouponUsagesByUserResponse, error)
	ListUserCouponUsagesByOrderAndUserAndCoupon(context.Context, *ListUserCouponUsagesByOrderAndUserAndCouponRequest) (*ListUserCouponUsagesByOrderAndUserAndCouponResponse, error)
	mustEmbedUnimplementedCouponServiceServer()
}

// UnimplementedCouponServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCouponServiceServer struct{}

func (UnimplementedCouponServiceServer) CreateCoupon(context.Context, *CreateCouponRequest) (*Coupon, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCoupon not implemented")
}
func (UnimplementedCouponServiceServer) GetCoupon(context.Context, *GetCouponRequest) (*Coupon, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoupon not implemented")
}
func (UnimplementedCouponServiceServer) UpdateCoupon(context.Context, *UpdateCouponRequest) (*Coupon, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCoupon not implemented")
}
func (UnimplementedCouponServiceServer) DeleteCoupon(context.Context, *DeleteCouponRequest) (*DeleteCouponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCoupon not implemented")
}
func (UnimplementedCouponServiceServer) ListCoupons(context.Context, *ListCouponsRequest) (*ListCouponsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCoupons not implemented")
}
func (UnimplementedCouponServiceServer) CreateCouponRestriction(context.Context, *CreateCouponRestrictionRequest) (*CouponRestriction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCouponRestriction not implemented")
}
func (UnimplementedCouponServiceServer) GetCouponRestriction(context.Context, *GetCouponRestrictionRequest) (*CouponRestriction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCouponRestriction not implemented")
}
func (UnimplementedCouponServiceServer) UpdateCouponRestriction(context.Context, *UpdateCouponRestrictionRequest) (*CouponRestriction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCouponRestriction not implemented")
}
func (UnimplementedCouponServiceServer) DeleteCouponRestriction(context.Context, *DeleteCouponRestrictionRequest) (*DeleteCouponRestrictionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCouponRestriction not implemented")
}
func (UnimplementedCouponServiceServer) ListCouponRestrictions(context.Context, *ListCouponRestrictionsRequest) (*ListCouponRestrictionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCouponRestrictions not implemented")
}
func (UnimplementedCouponServiceServer) CreateUserCoupon(context.Context, *CreateUserCouponRequest) (*UserCoupon, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserCoupon not implemented")
}
func (UnimplementedCouponServiceServer) GetUserCoupon(context.Context, *GetUserCouponRequest) (*UserCoupon, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCoupon not implemented")
}
func (UnimplementedCouponServiceServer) ListUserCoupons(context.Context, *ListUserCouponsRequest) (*ListUserCouponsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserCoupons not implemented")
}
func (UnimplementedCouponServiceServer) UseUserCoupon(context.Context, *UseUserCouponRequest) (*UserCoupon, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseUserCoupon not implemented")
}
func (UnimplementedCouponServiceServer) UnuseUserCoupon(context.Context, *UnuseUserCouponRequest) (*UserCoupon, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnuseUserCoupon not implemented")
}
func (UnimplementedCouponServiceServer) ListCouponUsages(context.Context, *ListCouponUsagesRequest) (*ListCouponUsagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCouponUsages not implemented")
}
func (UnimplementedCouponServiceServer) ListUserCouponUsages(context.Context, *ListUserCouponUsagesRequest) (*ListUserCouponUsagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserCouponUsages not implemented")
}
func (UnimplementedCouponServiceServer) ListUserCouponUsagesByOrder(context.Context, *ListUserCouponUsagesByOrderRequest) (*ListUserCouponUsagesByOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserCouponUsagesByOrder not implemented")
}
func (UnimplementedCouponServiceServer) ListUserCouponUsagesByCoupon(context.Context, *ListUserCouponUsagesByCouponRequest) (*ListUserCouponUsagesByCouponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserCouponUsagesByCoupon not implemented")
}
func (UnimplementedCouponServiceServer) ListUserCouponUsagesByOrderAndCoupon(context.Context, *ListUserCouponUsagesByOrderAndCouponRequest) (*ListUserCouponUsagesByOrderAndCouponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserCouponUsagesByOrderAndCoupon not implemented")
}
func (UnimplementedCouponServiceServer) ListUserCouponUsagesByOrderAndCouponAndUser(context.Context, *ListUserCouponUsagesByOrderAndCouponAndUserRequest) (*ListUserCouponUsagesByOrderAndCouponAndUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserCouponUsagesByOrderAndCouponAndUser not implemented")
}
func (UnimplementedCouponServiceServer) ListUserCouponUsagesByOrderAndUser(context.Context, *ListUserCouponUsagesByOrderAndUserRequest) (*ListUserCouponUsagesByOrderAndUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserCouponUsagesByOrderAndUser not implemented")
}
func (UnimplementedCouponServiceServer) ListUserCouponUsagesByCouponAndUser(context.Context, *ListUserCouponUsagesByCouponAndUserRequest) (*ListUserCouponUsagesByCouponAndUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserCouponUsagesByCouponAndUser not implemented")
}
func (UnimplementedCouponServiceServer) ListUserCouponUsagesByUser(context.Context, *ListUserCouponUsagesByUserRequest) (*ListUserCouponUsagesByUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserCouponUsagesByUser not implemented")
}
func (UnimplementedCouponServiceServer) ListUserCouponUsagesByOrderAndUserAndCoupon(context.Context, *ListUserCouponUsagesByOrderAndUserAndCouponRequest) (*ListUserCouponUsagesByOrderAndUserAndCouponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserCouponUsagesByOrderAndUserAndCoupon not implemented")
}
func (UnimplementedCouponServiceServer) mustEmbedUnimplementedCouponServiceServer() {}
func (UnimplementedCouponServiceServer) testEmbeddedByValue()                       {}

// UnsafeCouponServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CouponServiceServer will
// result in compilation errors.
type UnsafeCouponServiceServer interface {
	mustEmbedUnimplementedCouponServiceServer()
}

func RegisterCouponServiceServer(s grpc.ServiceRegistrar, srv CouponServiceServer) {
	// If the following call pancis, it indicates UnimplementedCouponServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CouponService_ServiceDesc, srv)
}

func _CouponService_CreateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).CreateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_CreateCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).CreateCoupon(ctx, req.(*CreateCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_GetCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).GetCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_GetCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).GetCoupon(ctx, req.(*GetCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_UpdateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).UpdateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_UpdateCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).UpdateCoupon(ctx, req.(*UpdateCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_DeleteCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).DeleteCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_DeleteCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).DeleteCoupon(ctx, req.(*DeleteCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListCoupons(ctx, req.(*ListCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_CreateCouponRestriction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCouponRestrictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).CreateCouponRestriction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_CreateCouponRestriction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).CreateCouponRestriction(ctx, req.(*CreateCouponRestrictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_GetCouponRestriction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCouponRestrictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).GetCouponRestriction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_GetCouponRestriction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).GetCouponRestriction(ctx, req.(*GetCouponRestrictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_UpdateCouponRestriction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCouponRestrictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).UpdateCouponRestriction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_UpdateCouponRestriction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).UpdateCouponRestriction(ctx, req.(*UpdateCouponRestrictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_DeleteCouponRestriction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCouponRestrictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).DeleteCouponRestriction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_DeleteCouponRestriction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).DeleteCouponRestriction(ctx, req.(*DeleteCouponRestrictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListCouponRestrictions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCouponRestrictionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListCouponRestrictions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListCouponRestrictions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListCouponRestrictions(ctx, req.(*ListCouponRestrictionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_CreateUserCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).CreateUserCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_CreateUserCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).CreateUserCoupon(ctx, req.(*CreateUserCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_GetUserCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).GetUserCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_GetUserCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).GetUserCoupon(ctx, req.(*GetUserCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListUserCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListUserCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListUserCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListUserCoupons(ctx, req.(*ListUserCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_UseUserCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseUserCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).UseUserCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_UseUserCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).UseUserCoupon(ctx, req.(*UseUserCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_UnuseUserCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnuseUserCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).UnuseUserCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_UnuseUserCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).UnuseUserCoupon(ctx, req.(*UnuseUserCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListCouponUsages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCouponUsagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListCouponUsages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListCouponUsages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListCouponUsages(ctx, req.(*ListCouponUsagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListUserCouponUsages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCouponUsagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListUserCouponUsages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListUserCouponUsages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListUserCouponUsages(ctx, req.(*ListUserCouponUsagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListUserCouponUsagesByOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCouponUsagesByOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListUserCouponUsagesByOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListUserCouponUsagesByOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListUserCouponUsagesByOrder(ctx, req.(*ListUserCouponUsagesByOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListUserCouponUsagesByCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCouponUsagesByCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListUserCouponUsagesByCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListUserCouponUsagesByCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListUserCouponUsagesByCoupon(ctx, req.(*ListUserCouponUsagesByCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListUserCouponUsagesByOrderAndCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCouponUsagesByOrderAndCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListUserCouponUsagesByOrderAndCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListUserCouponUsagesByOrderAndCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListUserCouponUsagesByOrderAndCoupon(ctx, req.(*ListUserCouponUsagesByOrderAndCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListUserCouponUsagesByOrderAndCouponAndUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCouponUsagesByOrderAndCouponAndUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListUserCouponUsagesByOrderAndCouponAndUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListUserCouponUsagesByOrderAndCouponAndUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListUserCouponUsagesByOrderAndCouponAndUser(ctx, req.(*ListUserCouponUsagesByOrderAndCouponAndUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListUserCouponUsagesByOrderAndUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCouponUsagesByOrderAndUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListUserCouponUsagesByOrderAndUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListUserCouponUsagesByOrderAndUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListUserCouponUsagesByOrderAndUser(ctx, req.(*ListUserCouponUsagesByOrderAndUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListUserCouponUsagesByCouponAndUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCouponUsagesByCouponAndUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListUserCouponUsagesByCouponAndUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListUserCouponUsagesByCouponAndUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListUserCouponUsagesByCouponAndUser(ctx, req.(*ListUserCouponUsagesByCouponAndUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListUserCouponUsagesByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCouponUsagesByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListUserCouponUsagesByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListUserCouponUsagesByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListUserCouponUsagesByUser(ctx, req.(*ListUserCouponUsagesByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListUserCouponUsagesByOrderAndUserAndCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCouponUsagesByOrderAndUserAndCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListUserCouponUsagesByOrderAndUserAndCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListUserCouponUsagesByOrderAndUserAndCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListUserCouponUsagesByOrderAndUserAndCoupon(ctx, req.(*ListUserCouponUsagesByOrderAndUserAndCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CouponService_ServiceDesc is the grpc.ServiceDesc for CouponService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CouponService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coupon.CouponService",
	HandlerType: (*CouponServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCoupon",
			Handler:    _CouponService_CreateCoupon_Handler,
		},
		{
			MethodName: "GetCoupon",
			Handler:    _CouponService_GetCoupon_Handler,
		},
		{
			MethodName: "UpdateCoupon",
			Handler:    _CouponService_UpdateCoupon_Handler,
		},
		{
			MethodName: "DeleteCoupon",
			Handler:    _CouponService_DeleteCoupon_Handler,
		},
		{
			MethodName: "ListCoupons",
			Handler:    _CouponService_ListCoupons_Handler,
		},
		{
			MethodName: "CreateCouponRestriction",
			Handler:    _CouponService_CreateCouponRestriction_Handler,
		},
		{
			MethodName: "GetCouponRestriction",
			Handler:    _CouponService_GetCouponRestriction_Handler,
		},
		{
			MethodName: "UpdateCouponRestriction",
			Handler:    _CouponService_UpdateCouponRestriction_Handler,
		},
		{
			MethodName: "DeleteCouponRestriction",
			Handler:    _CouponService_DeleteCouponRestriction_Handler,
		},
		{
			MethodName: "ListCouponRestrictions",
			Handler:    _CouponService_ListCouponRestrictions_Handler,
		},
		{
			MethodName: "CreateUserCoupon",
			Handler:    _CouponService_CreateUserCoupon_Handler,
		},
		{
			MethodName: "GetUserCoupon",
			Handler:    _CouponService_GetUserCoupon_Handler,
		},
		{
			MethodName: "ListUserCoupons",
			Handler:    _CouponService_ListUserCoupons_Handler,
		},
		{
			MethodName: "UseUserCoupon",
			Handler:    _CouponService_UseUserCoupon_Handler,
		},
		{
			MethodName: "UnuseUserCoupon",
			Handler:    _CouponService_UnuseUserCoupon_Handler,
		},
		{
			MethodName: "ListCouponUsages",
			Handler:    _CouponService_ListCouponUsages_Handler,
		},
		{
			MethodName: "ListUserCouponUsages",
			Handler:    _CouponService_ListUserCouponUsages_Handler,
		},
		{
			MethodName: "ListUserCouponUsagesByOrder",
			Handler:    _CouponService_ListUserCouponUsagesByOrder_Handler,
		},
		{
			MethodName: "ListUserCouponUsagesByCoupon",
			Handler:    _CouponService_ListUserCouponUsagesByCoupon_Handler,
		},
		{
			MethodName: "ListUserCouponUsagesByOrderAndCoupon",
			Handler:    _CouponService_ListUserCouponUsagesByOrderAndCoupon_Handler,
		},
		{
			MethodName: "ListUserCouponUsagesByOrderAndCouponAndUser",
			Handler:    _CouponService_ListUserCouponUsagesByOrderAndCouponAndUser_Handler,
		},
		{
			MethodName: "ListUserCouponUsagesByOrderAndUser",
			Handler:    _CouponService_ListUserCouponUsagesByOrderAndUser_Handler,
		},
		{
			MethodName: "ListUserCouponUsagesByCouponAndUser",
			Handler:    _CouponService_ListUserCouponUsagesByCouponAndUser_Handler,
		},
		{
			MethodName: "ListUserCouponUsagesByUser",
			Handler:    _CouponService_ListUserCouponUsagesByUser_Handler,
		},
		{
			MethodName: "ListUserCouponUsagesByOrderAndUserAndCoupon",
			Handler:    _CouponService_ListUserCouponUsagesByOrderAndUserAndCoupon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
