postgresql:
  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce
  image: postgres:15.1
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  service:
    type: ClusterIP
  port: 5432
  adminPassword: my-admin-password
  databaseName: my-database