cassandra:
  name: cassandra
  replicas: 1

  image:
    name: cassandra
    tag: latest
    port: 9042

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  service:
    name: cassandra-svc
    type: LoadBalancer
    nodeport: 30019
