prometheus:
  name: prometheus

  image:
    repository: docker.io/prom/prometheus
    tag: v2.41.0
    pullPolicy: IfNotPresent

  retention: 24h

  service:
    port: 9090

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi

  dataVolumeSize: 5Gi
