apiVersion: v2
name: goflow-service
description: A Helm chart for goflow-service, goflow job scheduler and its web UI

type: application

version: 0.2.0
appVersion: "1.0.0"

dependencies:
  - name: common
    version: "0.1.0"
    repository: file://../common
