#!/usr/bin/env python3
"""Regenerate deploy/ci/image-updater.yaml from deploy/ci/services.yaml.

  python3 deploy/ci/scripts/gen-image-updater.py
"""
import os

import yaml

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
services = yaml.safe_load(open(os.path.join(HERE, "services.yaml")))["services"]

refs = []
for s in services:
    images = []
    for key in s["helmKeys"]:
        images.append({
            "alias": key,
            "imageName": f"localhost:5000/{s['image']}",
            "manifestTargets": {"helm": {"name": f"{key}.image.name", "tag": f"{key}.image.tag"}},
        })
    refs.append({"namePattern": f"{s['name']}-dev", "images": images})

doc = {
    "apiVersion": "argocd-image-updater.argoproj.io/v1alpha1",
    "kind": "ImageUpdater",
    "metadata": {
        "name": "store-dev",
        "namespace": "argocd",
        "annotations": {"argocd.argoproj.io/sync-options": "SkipDryRunOnMissingResource=true"},
    },
    "spec": {
        # Tags are <commit time UTC>-<sha7>, so the alphabetically last one is
        # the newest commit. forceUpdate switches an app from its ghcr.io image
        # to the local registry the first time a local build exists.
        "commonUpdateSettings": {
            "updateStrategy": "alphabetical",
            "allowTags": r"regexp:^[0-9]{8}T[0-9]{6}-[0-9a-f]{7}$",
            "forceUpdate": True,
        },
        # Parameter overrides on the Application, no commit back to git: dev
        # image tags are cluster state; staging/prod are promoted through git.
        "writeBackConfig": {"method": "argocd"},
        "applicationRefs": refs,
    },
}
header = ("# Generated by deploy/ci/scripts/gen-image-updater.py from services.yaml - do not edit.\n"
          "# Rolls every new local build (localhost:5000/<image>:<tag>) out to the\n"
          "# matching <service>-dev Application.\n")
with open(os.path.join(HERE, "image-updater.yaml"), "w") as f:
    f.write(header + yaml.safe_dump(doc, sort_keys=False, width=200))
print(f"{len(refs)} applications")
