
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.zookeeper.name }}
spec:
  replicas: {{ .Values.zookeeper.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.zookeeper.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.zookeeper.name }}
    spec:
      containers:
      - name: {{ .Values.zookeeper.name }}
        image: {{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: {{ .Values.zookeeper.service.port }}
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  echo $(( $(cat /etc/hosts | grep zookeeper | awk '{print($3)}' | awk '{split($0,array,"-")} END{print array[3]}') + 1 )) > /bitnami/zookeeper/data/myid
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
