apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "keycloak-development-ingress"
  namespace: default
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: "demo.pf9.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: "keycloak-development"
            port:
              number: 8080