apiVersion: "v1"
kind: "Service"
metadata:
    name: {{ .Values.keycloak.service.name | quote }}
spec:
    ports:
      - port: {{ .Values.keycloak.service.port }}
        targetPort: {{ .Values.keycloak.service.targetPort }}
    selector:
      app: {{ .Values.keycloak.name | quote }}
---
apiVersion: "v1"
kind: "Service"
metadata:
    name: {{ .Values.keycloak.service.nodeportName | quote }}
spec:
    type: NodePort
    ports:
      - port: {{ .Values.keycloak.service.port }}
        targetPort: {{ .Values.keycloak.service.targetPort }}
        nodePort: {{ .Values.keycloak.service.nodePort }}
    selector:
      app: {{ .Values.keycloak.name | quote }}
