apiVersion: "v1"
kind: "Service"
metadata: 
    name: "keycloak-service"
spec: 
    ports: 
      - port: 8080
        targetPort: 8080
    selector: 
      app: "keycloak-development"
# ---
# apiVersion: "v1"
# kind: "Service"
# metadata: 
#     name: "keycloak-nodeport"
# spec: 
#     ports: 
#       - port: 8080
#         targetPort: 8080
#         nodePort: 30001
#     selector: 
#       app: "keycloak-development"