apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name:  ollama-web-ingress
spec:
  rules:
    - host: kekibook.uk
      http:
        paths:
          - path: /ollama
            pathType: Prefix
            backend:
              service:
                name: ollama
                port:
                  name: http