apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ollama
  labels:
    app: ollama
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: ollama
    release: {{ .Release.Name }}
{{- if .Values.service.createNodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ollama-nodeport
  labels:
    app: ollama
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: ollama
    release: {{ .Release.Name }}
{{- end }}
