apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  serviceName: kafka-deployment
  selector:
    matchLabels:
        app: kafka-deployment
  template:
    metadata:
      labels:
        app: kafka-deployment
    spec:
      containers:
      - name: kafka-deployment
        image: bitnami/kafka:2.6.0  
        securityContext:
          runAsUser: 0
        resources:
          requests:
            memory: "1G"
            cpu: "1"             
        ports:
         - containerPort: 9092
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes" 