apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.service.name }}
spec:
  ports:
  - port: {{ .Values.kafka.service.port }}
    targetPort: {{ .Values.kafka.service.port }}
  selector:
    app: {{ .Values.kafka.name }}
