{{/*
Syncs a Secret from the cluster's secret manager (Vault, AWS Secrets Manager,
GCP Secret Manager, ...) through External Secrets Operator, so no credential
is stored in git or generated by Helm at render time.
*/}}
{{- define "common.externalsecret" -}}
{{- $es := .svc.externalSecret | default dict -}}
{{- if $es.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $es.targetName | default (include "common.name" .) }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    # Argo CD: create the Secret before the Deployment that consumes it.
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ $es.refreshInterval | default "1h" }}
  secretStoreRef:
    kind: {{ ($es.secretStoreRef | default dict).kind | default "ClusterSecretStore" }}
    name: {{ required "externalSecret.secretStoreRef.name is required" ($es.secretStoreRef | default dict).name }}
  target:
    name: {{ $es.targetName | default (include "common.name" .) }}
    creationPolicy: Owner
  data:
    {{- range $es.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        {{- with .property }}
        property: {{ . }}
        {{- end }}
    {{- end }}
{{- end -}}
{{- end -}}
