apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.basketService.name }}-deployment
spec:
{{- if not .Values.basketService.autoscaling.enabled }}
  replicas: {{ .Values.basketService.replicas }}
{{- end }}
  selector:
    matchLabels:
      app: {{ .Values.basketService.name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Values.basketService.name }}-deployment
    spec:
      containers:
      - name: {{ .Values.basketService.name }}-deployment
        image: {{ .Values.basketService.image.name }}:{{ .Values.basketService.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.basketService.image.port }}
        env:
          - name: PORT
            value: "{{ .Values.basketService.image.port }}"
        resources:
          {{- toYaml .Values.basketService.resources | nindent 10 }}
        volumeMounts:
        - name: env-file
          mountPath: /app/.env
          subPath: basket-service.env
      volumes:
      - name: env-file
        secret:
          secretName: service-env-files
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.basketService.service.name }}
spec:
  type: {{ .Values.basketService.service.type }}
  ports:
  - port: 80
    targetPort: {{ .Values.basketService.image.port }}
  selector:
    app: {{ .Values.basketService.name }}-deployment
