apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  labels:
    app: kibana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-deployment
  template:
    metadata:
      labels:
        app: kibana-deployment
    spec:
      containers:
      - name: kibana-deployment
        image: kibana:7.17.5
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2000m
            memory: "2048Mi"
          requests:
            cpu: 500m
            memory: "1024Mi"
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch-service:9200
        ports:
        - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
spec:
  ports:
  - port: 80
    targetPort: 5601
  selector:
    app: kibana-deployment
  type: LoadBalancer