apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.elasticsearch.name }}
  labels:
    app: {{ .Values.elasticsearch.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.elasticsearch.name }}
  replicas: {{ .Values.elasticsearch.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.elasticsearch.name }}
    spec:
      containers:
      - name: {{ .Values.elasticsearch.name }}
        image: {{ .Values.elasticsearch.image.name }}:{{ .Values.elasticsearch.image.tag }}
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: {{ .Values.elasticsearch.javaOpts | quote }}
        resources:
          {{- toYaml .Values.elasticsearch.resources | nindent 10 }}
