apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.toolService.name }}-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.toolService.learning.storage }}
