apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  labels:
    app: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8083
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2500Mi"
          env:
            - name: BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: GROUP_ID
              value: "pg-es-sync"
            - name: CONFIG_STORAGE_TOPIC
              value: pg-es-sync-connect-configs
            - name: OFFSET_STORAGE_TOPIC
              value: pg-es-sync-connect-offsets
            - name: STATUS_STORAGE_TOPIC
              value: pg-es-sync-connect-status
            - name: CONNECT_ADMIN_REQUEST_TIMEOUT_MS
              value: "90000"
            - name: CONNECT_PRODUCER_REQUEST_TIMEOUT_MS
              value: "90000"
            - name: CONNECT_CONSUMER_REQUEST_TIMEOUT_MS
              value: "90000"
            - name: CONNECT_CONSUMER_DEFAULT_API_TIMEOUT_MS
              value: "90000"
