apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-service
spec:
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: {{ .Values.nodePort }}
  type: NodePort
  selector:
    app: kafka-connect
