{{- if not .Values.manageService.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.manageService.name }}-secret
type: Opaque
stringData:
  keycloakAdminPassword: {{ .Values.manageService.env.keycloakAdminPassword | quote }}
  authorizeKey: {{ .Values.manageService.env.authorizeKey | quote }}
{{- end }}
