keycloak:
  name: keycloak-development
  replicas: 1

  image:
    repository: quay.io/keycloak/keycloak
    tag: "8.0.2"
    pullPolicy: Always

  admin:
    user: admin
    password: admin

  frontendUrl: https://keycloak-development/auth/
  adminUrl: https://keycloak-development/auth/realms/master/admin/

  service:
    name: keycloak-service
    nodeportName: keycloak-nodeport
    port: 80
    targetPort: 8080
    nodePort: 30005
