apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: airflow-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31002
  selector:
    app: airflow-deployment