addressCountry:
  name: address-country
  replicas: 1

  image:
    name: ghcr.io/jieeirosst/address-country-service
    tag: latest
    port: 8000

  service:
    name: address-country-svc
    type: LoadBalancer

  ingress:
    enabled: false
    className: nginx
    annotations: {}
    host: address-country.local
    path: /
    pathType: Prefix

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
