kibana:
  name: kibana-deployment
  replicas: 1

  image:
    repository: kibana
    tag: "7.17.5"
    pullPolicy: Always

  elasticsearchHosts: http://elasticsearch-service:9200

  service:
    name: kibana-svc
    port: 80
    targetPort: 5601
    nodePort: 31225

  resources:
    limits:
      cpu: 2000m
      memory: "2048Mi"
    requests:
      cpu: 500m
      memory: "1024Mi"
