apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8500
        volumeMounts:
        - name: consul-data
          mountPath: /data
      volumes:
      - name: consul-data
        persistentVolumeClaim:
          claimName: consul-data