apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: consul
spec:
  rules:
  - host: {{ index .Values.ingress.hosts 0 | default "" }}
    http:
      paths:
      - path: {{ index .Values.ingress.hosts 0 .paths 0 | default "/" }}
        pathType: {{ index .Values.ingress.hosts 0 .paths 0 .pathType | default "Prefix" }}
        backend:
          service:
            name: consul
            port:
              number: 8500