apiVersion: v1
kind: Pod
metadata:
  name: consul-pod
spec:
  containers:
  - name: consul
    image: "hashicorp/consul:1.12.0"
    args: ["agent", "-server", "-bootstrap-expect=1", "-ui"] 
    ports:
    - containerPort: 8500
    volumeMounts:
    - name: consul-data
      mountPath: /data
  volumes:
  - name: consul-data
    persistentVolumeClaim:
      claimName: consul-data