apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-pv
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: consul-storage-class
  hostPath:
    path: /tmp/consul-data