apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-data
spec:
  storageClassName: consul-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi