apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
  - port: 80
    targetPort: 6379
  selector:
    app: redis-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 6379
    nodePort: 31001
  selector:
    app: redis-deployment