apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-credentials
  labels:
    app: {{ .Values.minio.name }}
data:
  MINIO_ROOT_USER: {{ .Values.minio.credentials.rootUser }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.credentials.rootPassword }}
