apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  ports:
  - port: 80
    targetPort: 27017
  selector:
    app: mongo-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 27017
    nodePort: 32002
  selector:
    app: mongo-deployment