server:
  PortServer: 1235
  PortServerGrpc: 1236

secret:
  JwtSecretKey: secretkey
  AuthorizeKey: cao_hoang_mai_phuong

mysql:
  MysqlHost:     localhost
  MysqlPort:     3307
  MysqlUser:     root
  MysqlPassword: 1234
  MysqlDbname:   user
  MysqlDriver:   mysql


rabbitmq:
  Host: localhost
  Port: 5672
  User: guest
  Password: guest
  Exchange: emails-exchange
  Queue: emails-queue
  RoutingKey: emails-routing-key
  ConsumerTag: emails-consumer
  WorkerPoolSize: 24

redis:
  dns: "localhost:7002"

email:
  NameEmail: chmp.7399@gmail.com
  PasswordEmail: "#############"
  Port: 587
  Host: "smtp.gmail.com"

postgres:
  PostgresqlHost: kesavan.db.elephantsql.com
  PostgresqlPort: 5432
  PostgresqlUser: kekxrkco
  PostgresqlPassword: 61zIfY1T1lbg9A_xsJMYxetluLZyvuit
  PostgresqlDbname: kekxrkco
  PgDriver: pgx