apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.arrange.name }}-deployment
spec:
{{- if not .Values.arrange.autoscaling.enabled }}
  replicas: {{ .Values.arrange.replicas }}
{{- end }}
  selector:
    matchLabels:
      app: {{ .Values.arrange.name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Values.arrange.name }}-deployment
    spec:
      containers:
      - name: {{ .Values.arrange.name }}-deployment
        image: {{ .Values.arrange.image.name }}:{{ .Values.arrange.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.arrange.image.port }}
        resources:
          {{- toYaml .Values.arrange.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.arrange.service.name }}
spec:
  type: {{ .Values.arrange.service.type }}
  ports:
  - port: 80
    targetPort: {{ .Values.arrange.image.port }}
  selector:
    app: {{ .Values.arrange.name }}-deployment
