-- 0002_seed_provinces.sql : 63 tỉnh/thành (mã GSO). Auto-generated.
INSERT INTO provinces (code, name, name_full, name_en, type, region, slug) VALUES
  ('01','Hà Nội','Thành phố Hà Nội','Ha Noi','thanh-pho','Bắc','ha-noi'),
  ('02','Hà Giang','Tỉnh Hà Giang','Ha Giang','tinh','Bắc','ha-giang'),
  ('04','Cao Bằng','Tỉnh Cao Bằng','Cao Bang','tinh','Bắc','cao-bang'),
  ('06','Bắc Kạn','Tỉnh Bắc Kạn','Bac Kan','tinh','Bắc','bac-kan'),
  ('08','Tuyên Quang','Tỉnh Tuyên Quang','Tuyen Quang','tinh','Bắc','tuyen-quang'),
  ('10','Lào Cai','Tỉnh Lào Cai','Lao Cai','tinh','Bắc','lao-cai'),
  ('11','Điện Biên','Tỉnh Điện Biên','Dien Bien','tinh','Bắc','dien-bien'),
  ('12','Lai Châu','Tỉnh Lai Châu','Lai Chau','tinh','Bắc','lai-chau'),
  ('14','Sơn La','Tỉnh Sơn La','Son La','tinh','Bắc','son-la'),
  ('15','Yên Bái','Tỉnh Yên Bái','Yen Bai','tinh','Bắc','yen-bai'),
  ('17','Hoà Bình','Tỉnh Hoà Bình','Hoa Binh','tinh','Bắc','hoa-binh'),
  ('19','Thái Nguyên','Tỉnh Thái Nguyên','Thai Nguyen','tinh','Bắc','thai-nguyen'),
  ('20','Lạng Sơn','Tỉnh Lạng Sơn','Lang Son','tinh','Bắc','lang-son'),
  ('22','Quảng Ninh','Tỉnh Quảng Ninh','Quang Ninh','tinh','Bắc','quang-ninh'),
  ('24','Bắc Giang','Tỉnh Bắc Giang','Bac Giang','tinh','Bắc','bac-giang'),
  ('25','Phú Thọ','Tỉnh Phú Thọ','Phu Tho','tinh','Bắc','phu-tho'),
  ('26','Vĩnh Phúc','Tỉnh Vĩnh Phúc','Vinh Phuc','tinh','Bắc','vinh-phuc'),
  ('27','Bắc Ninh','Tỉnh Bắc Ninh','Bac Ninh','tinh','Bắc','bac-ninh'),
  ('30','Hải Dương','Tỉnh Hải Dương','Hai Duong','tinh','Bắc','hai-duong'),
  ('31','Hải Phòng','Thành phố Hải Phòng','Hai Phong','thanh-pho','Bắc','hai-phong'),
  ('33','Hưng Yên','Tỉnh Hưng Yên','Hung Yen','tinh','Bắc','hung-yen'),
  ('34','Thái Bình','Tỉnh Thái Bình','Thai Binh','tinh','Bắc','thai-binh'),
  ('35','Hà Nam','Tỉnh Hà Nam','Ha Nam','tinh','Bắc','ha-nam'),
  ('36','Nam Định','Tỉnh Nam Định','Nam Dinh','tinh','Bắc','nam-dinh'),
  ('37','Ninh Bình','Tỉnh Ninh Bình','Ninh Binh','tinh','Bắc','ninh-binh'),
  ('38','Thanh Hóa','Tỉnh Thanh Hóa','Thanh Hoa','tinh','Trung','thanh-hoa'),
  ('40','Nghệ An','Tỉnh Nghệ An','Nghe An','tinh','Trung','nghe-an'),
  ('42','Hà Tĩnh','Tỉnh Hà Tĩnh','Ha Tinh','tinh','Trung','ha-tinh'),
  ('44','Quảng Bình','Tỉnh Quảng Bình','Quang Binh','tinh','Trung','quang-binh'),
  ('45','Quảng Trị','Tỉnh Quảng Trị','Quang Tri','tinh','Trung','quang-tri'),
  ('46','Thừa Thiên Huế','Tỉnh Thừa Thiên Huế','Thua Thien Hue','tinh','Trung','thua-thien-hue'),
  ('48','Đà Nẵng','Thành phố Đà Nẵng','Da Nang','thanh-pho','Trung','da-nang'),
  ('49','Quảng Nam','Tỉnh Quảng Nam','Quang Nam','tinh','Trung','quang-nam'),
  ('51','Quảng Ngãi','Tỉnh Quảng Ngãi','Quang Ngai','tinh','Trung','quang-ngai'),
  ('52','Bình Định','Tỉnh Bình Định','Binh Dinh','tinh','Trung','binh-dinh'),
  ('54','Phú Yên','Tỉnh Phú Yên','Phu Yen','tinh','Trung','phu-yen'),
  ('56','Khánh Hòa','Tỉnh Khánh Hòa','Khanh Hoa','tinh','Trung','khanh-hoa'),
  ('58','Ninh Thuận','Tỉnh Ninh Thuận','Ninh Thuan','tinh','Trung','ninh-thuan'),
  ('60','Bình Thuận','Tỉnh Bình Thuận','Binh Thuan','tinh','Trung','binh-thuan'),
  ('62','Kon Tum','Tỉnh Kon Tum','Kon Tum','tinh','Trung','kon-tum'),
  ('64','Gia Lai','Tỉnh Gia Lai','Gia Lai','tinh','Trung','gia-lai'),
  ('66','Đắk Lắk','Tỉnh Đắk Lắk','Dak Lak','tinh','Trung','dak-lak'),
  ('67','Đắk Nông','Tỉnh Đắk Nông','Dak Nong','tinh','Trung','dak-nong'),
  ('68','Lâm Đồng','Tỉnh Lâm Đồng','Lam Dong','tinh','Trung','lam-dong'),
  ('70','Bình Phước','Tỉnh Bình Phước','Binh Phuoc','tinh','Nam','binh-phuoc'),
  ('72','Tây Ninh','Tỉnh Tây Ninh','Tay Ninh','tinh','Nam','tay-ninh'),
  ('74','Bình Dương','Tỉnh Bình Dương','Binh Duong','tinh','Nam','binh-duong'),
  ('75','Đồng Nai','Tỉnh Đồng Nai','Dong Nai','tinh','Nam','dong-nai'),
  ('77','Bà Rịa - Vũng Tàu','Tỉnh Bà Rịa - Vũng Tàu','Ba Ria - Vung Tau','tinh','Nam','ba-ria-vung-tau'),
  ('79','Hồ Chí Minh','Thành phố Hồ Chí Minh','Ho Chi Minh','thanh-pho','Nam','ho-chi-minh'),
  ('80','Long An','Tỉnh Long An','Long An','tinh','Nam','long-an'),
  ('82','Tiền Giang','Tỉnh Tiền Giang','Tien Giang','tinh','Nam','tien-giang'),
  ('83','Bến Tre','Tỉnh Bến Tre','Ben Tre','tinh','Nam','ben-tre'),
  ('84','Trà Vinh','Tỉnh Trà Vinh','Tra Vinh','tinh','Nam','tra-vinh'),
  ('86','Vĩnh Long','Tỉnh Vĩnh Long','Vinh Long','tinh','Nam','vinh-long'),
  ('87','Đồng Tháp','Tỉnh Đồng Tháp','Dong Thap','tinh','Nam','dong-thap'),
  ('89','An Giang','Tỉnh An Giang','An Giang','tinh','Nam','an-giang'),
  ('91','Kiên Giang','Tỉnh Kiên Giang','Kien Giang','tinh','Nam','kien-giang'),
  ('92','Cần Thơ','Thành phố Cần Thơ','Can Tho','thanh-pho','Nam','can-tho'),
  ('93','Hậu Giang','Tỉnh Hậu Giang','Hau Giang','tinh','Nam','hau-giang'),
  ('94','Sóc Trăng','Tỉnh Sóc Trăng','Soc Trang','tinh','Nam','soc-trang'),
  ('95','Bạc Liêu','Tỉnh Bạc Liêu','Bac Lieu','tinh','Nam','bac-lieu'),
  ('96','Cà Mau','Tỉnh Cà Mau','Ca Mau','tinh','Nam','ca-mau')
ON CONFLICT (code) DO UPDATE SET
  name=EXCLUDED.name, name_full=EXCLUDED.name_full, name_en=EXCLUDED.name_en,
  type=EXCLUDED.type, region=EXCLUDED.region, slug=EXCLUDED.slug;
