-- 0003_seed_districts.sql : quận/huyện/thị xã (mã GSO). Auto-generated.
INSERT INTO districts (code, province_code, name, name_full, name_en, type, slug) VALUES
  ('001','01','Ba Đình','Quận Ba Đình','Ba Dinh','quan','ba-dinh'),
  ('002','01','Hoàn Kiếm','Quận Hoàn Kiếm','Hoan Kiem','quan','hoan-kiem'),
  ('003','01','Tây Hồ','Quận Tây Hồ','Tay Ho','quan','tay-ho'),
  ('004','01','Long Biên','Quận Long Biên','Long Bien','quan','long-bien'),
  ('005','01','Cầu Giấy','Quận Cầu Giấy','Cau Giay','quan','cau-giay'),
  ('006','01','Đống Đa','Quận Đống Đa','Dong Da','quan','dong-da'),
  ('007','01','Hai Bà Trưng','Quận Hai Bà Trưng','Hai Ba Trung','quan','hai-ba-trung'),
  ('008','01','Hoàng Mai','Quận Hoàng Mai','Hoang Mai','quan','hoang-mai'),
  ('009','01','Thanh Xuân','Quận Thanh Xuân','Thanh Xuan','quan','thanh-xuan'),
  ('016','01','Sóc Sơn','Huyện Sóc Sơn','Soc Son','huyen','soc-son'),
  ('017','01','Đông Anh','Huyện Đông Anh','Dong Anh','huyen','dong-anh'),
  ('018','01','Gia Lâm','Huyện Gia Lâm','Gia Lam','huyen','gia-lam'),
  ('019','01','Nam Từ Liêm','Quận Nam Từ Liêm','Nam Tu Liem','quan','nam-tu-liem'),
  ('020','01','Thanh Trì','Huyện Thanh Trì','Thanh Tri','huyen','thanh-tri'),
  ('021','01','Bắc Từ Liêm','Quận Bắc Từ Liêm','Bac Tu Liem','quan','bac-tu-liem'),
  ('024','02','Hà Giang','Thành phố Hà Giang','Ha Giang','thanh-pho','ha-giang'),
  ('026','02','Đồng Văn','Huyện Đồng Văn','Dong Van','huyen','dong-van'),
  ('027','02','Mèo Vạc','Huyện Mèo Vạc','Meo Vac','huyen','meo-vac'),
  ('028','02','Yên Minh','Huyện Yên Minh','Yen Minh','huyen','yen-minh'),
  ('029','02','Quản Bạ','Huyện Quản Bạ','Quan Ba','huyen','quan-ba'),
  ('030','02','Vị Xuyên','Huyện Vị Xuyên','Vi Xuyen','huyen','vi-xuyen'),
  ('031','02','Bắc Mê','Huyện Bắc Mê','Bac Me','huyen','bac-me'),
  ('032','02','Hoàng Su Phì','Huyện Hoàng Su Phì','Hoang Su Phi','huyen','hoang-su-phi'),
  ('033','02','Xín Mần','Huyện Xín Mần','Xin Man','huyen','xin-man'),
  ('034','02','Bắc Quang','Huyện Bắc Quang','Bac Quang','huyen','bac-quang'),
  ('035','02','Quang Bình','Huyện Quang Bình','Quang Binh','huyen','quang-binh'),
  ('040','04','Cao Bằng','Thành phố Cao Bằng','Cao Bang','thanh-pho','cao-bang'),
  ('042','04','Bảo Lâm','Huyện Bảo Lâm','Bao Lam','huyen','bao-lam'),
  ('043','04','Bảo Lạc','Huyện Bảo Lạc','Bao Lac','huyen','bao-lac'),
  ('045','04','Hà Quảng','Huyện Hà Quảng','Ha Quang','huyen','ha-quang'),
  ('047','04','Trùng Khánh','Huyện Trùng Khánh','Trung Khanh','huyen','trung-khanh'),
  ('048','04','Hạ Lang','Huyện Hạ Lang','Ha Lang','huyen','ha-lang'),
  ('049','04','Quảng Hòa','Huyện Quảng Hòa','Quang Hoa','huyen','quang-hoa'),
  ('051','04','Hoà An','Huyện Hoà An','Hoa An','huyen','hoa-an'),
  ('052','04','Nguyên Bình','Huyện Nguyên Bình','Nguyen Binh','huyen','nguyen-binh'),
  ('053','04','Thạch An','Huyện Thạch An','Thach An','huyen','thach-an'),
  ('058','06','Bắc Kạn','Thành Phố Bắc Kạn','Bac Kan','thanh-pho','bac-kan'),
  ('060','06','Pác Nặm','Huyện Pác Nặm','Pac Nam','huyen','pac-nam'),
  ('061','06','Ba Bể','Huyện Ba Bể','Ba Be','huyen','ba-be'),
  ('062','06','Ngân Sơn','Huyện Ngân Sơn','Ngan Son','huyen','ngan-son'),
  ('063','06','Bạch Thông','Huyện Bạch Thông','Bach Thong','huyen','bach-thong'),
  ('064','06','Chợ Đồn','Huyện Chợ Đồn','Cho Don','huyen','cho-don'),
  ('065','06','Chợ Mới','Huyện Chợ Mới','Cho Moi','huyen','cho-moi'),
  ('066','06','Na Rì','Huyện Na Rì','Na Ri','huyen','na-ri'),
  ('070','08','Tuyên Quang','Thành phố Tuyên Quang','Tuyen Quang','thanh-pho','tuyen-quang'),
  ('071','08','Lâm Bình','Huyện Lâm Bình','Lam Binh','huyen','lam-binh'),
  ('072','08','Na Hang','Huyện Na Hang','Na Hang','huyen','na-hang'),
  ('073','08','Chiêm Hóa','Huyện Chiêm Hóa','Chiem Hoa','huyen','chiem-hoa'),
  ('074','08','Hàm Yên','Huyện Hàm Yên','Ham Yen','huyen','ham-yen'),
  ('075','08','Yên Sơn','Huyện Yên Sơn','Yen Son','huyen','yen-son'),
  ('076','08','Sơn Dương','Huyện Sơn Dương','Son Duong','huyen','son-duong'),
  ('080','10','Lào Cai','Thành phố Lào Cai','Lao Cai','thanh-pho','lao-cai'),
  ('082','10','Bát Xát','Huyện Bát Xát','Bat Xat','huyen','bat-xat'),
  ('083','10','Mường Khương','Huyện Mường Khương','Muong Khuong','huyen','muong-khuong'),
  ('084','10','Si Ma Cai','Huyện Si Ma Cai','Si Ma Cai','huyen','si-ma-cai'),
  ('085','10','Bắc Hà','Huyện Bắc Hà','Bac Ha','huyen','bac-ha'),
  ('086','10','Bảo Thắng','Huyện Bảo Thắng','Bao Thang','huyen','bao-thang'),
  ('087','10','Bảo Yên','Huyện Bảo Yên','Bao Yen','huyen','bao-yen'),
  ('088','10','Sa Pa','Thị xã Sa Pa','Sa Pa','thi-xa','sa-pa'),
  ('089','10','Văn Bàn','Huyện Văn Bàn','Van Ban','huyen','van-ban'),
  ('094','11','Điện Biên Phủ','Thành phố Điện Biên Phủ','Dien Bien Phu','thanh-pho','dien-bien-phu'),
  ('095','11','Mường Lay','Thị xã Mường Lay','Muong Lay','thi-xa','muong-lay'),
  ('096','11','Mường Nhé','Huyện Mường Nhé','Muong Nhe','huyen','muong-nhe'),
  ('097','11','Mường Chà','Huyện Mường Chà','Muong Cha','huyen','muong-cha'),
  ('098','11','Tủa Chùa','Huyện Tủa Chùa','Tua Chua','huyen','tua-chua'),
  ('099','11','Tuần Giáo','Huyện Tuần Giáo','Tuan Giao','huyen','tuan-giao'),
  ('100','11','Điện Biên','Huyện Điện Biên','Dien Bien','huyen','dien-bien'),
  ('101','11','Điện Biên Đông','Huyện Điện Biên Đông','Dien Bien Dong','huyen','dien-bien-dong'),
  ('102','11','Mường Ảng','Huyện Mường Ảng','Muong Ang','huyen','muong-ang'),
  ('103','11','Nậm Pồ','Huyện Nậm Pồ','Nam Po','huyen','nam-po'),
  ('105','12','Lai Châu','Thành phố Lai Châu','Lai Chau','thanh-pho','lai-chau'),
  ('106','12','Tam Đường','Huyện Tam Đường','Tam Duong','huyen','tam-duong'),
  ('107','12','Mường Tè','Huyện Mường Tè','Muong Te','huyen','muong-te'),
  ('108','12','Sìn Hồ','Huyện Sìn Hồ','Sin Ho','huyen','sin-ho'),
  ('109','12','Phong Thổ','Huyện Phong Thổ','Phong Tho','huyen','phong-tho'),
  ('110','12','Than Uyên','Huyện Than Uyên','Than Uyen','huyen','than-uyen'),
  ('111','12','Tân Uyên','Huyện Tân Uyên','Tan Uyen','huyen','tan-uyen'),
  ('112','12','Nậm Nhùn','Huyện Nậm Nhùn','Nam Nhun','huyen','nam-nhun'),
  ('116','14','Sơn La','Thành phố Sơn La','Son La','thanh-pho','son-la'),
  ('118','14','Quỳnh Nhai','Huyện Quỳnh Nhai','Quynh Nhai','huyen','quynh-nhai'),
  ('119','14','Thuận Châu','Huyện Thuận Châu','Thuan Chau','huyen','thuan-chau'),
  ('120','14','Mường La','Huyện Mường La','Muong La','huyen','muong-la'),
  ('121','14','Bắc Yên','Huyện Bắc Yên','Bac Yen','huyen','bac-yen'),
  ('122','14','Phù Yên','Huyện Phù Yên','Phu Yen','huyen','phu-yen'),
  ('123','14','Mộc Châu','Huyện Mộc Châu','Moc Chau','huyen','moc-chau'),
  ('124','14','Yên Châu','Huyện Yên Châu','Yen Chau','huyen','yen-chau'),
  ('125','14','Mai Sơn','Huyện Mai Sơn','Mai Son','huyen','mai-son'),
  ('126','14','Sông Mã','Huyện Sông Mã','Song Ma','huyen','song-ma'),
  ('127','14','Sốp Cộp','Huyện Sốp Cộp','Sop Cop','huyen','sop-cop'),
  ('128','14','Vân Hồ','Huyện Vân Hồ','Van Ho','huyen','van-ho'),
  ('132','15','Yên Bái','Thành phố Yên Bái','Yen Bai','thanh-pho','yen-bai'),
  ('133','15','Nghĩa Lộ','Thị xã Nghĩa Lộ','Nghia Lo','thi-xa','nghia-lo'),
  ('135','15','Lục Yên','Huyện Lục Yên','Luc Yen','huyen','luc-yen'),
  ('136','15','Văn Yên','Huyện Văn Yên','Van Yen','huyen','van-yen'),
  ('137','15','Mù Căng Chải','Huyện Mù Căng Chải','Mu Cang Chai','huyen','mu-cang-chai'),
  ('138','15','Trấn Yên','Huyện Trấn Yên','Tran Yen','huyen','tran-yen'),
  ('139','15','Trạm Tấu','Huyện Trạm Tấu','Tram Tau','huyen','tram-tau'),
  ('140','15','Văn Chấn','Huyện Văn Chấn','Van Chan','huyen','van-chan'),
  ('141','15','Yên Bình','Huyện Yên Bình','Yen Binh','huyen','yen-binh'),
  ('148','17','Hòa Bình','Thành phố Hòa Bình','Hoa Binh','thanh-pho','hoa-binh'),
  ('150','17','Đà Bắc','Huyện Đà Bắc','Da Bac','huyen','da-bac'),
  ('152','17','Lương Sơn','Huyện Lương Sơn','Luong Son','huyen','luong-son'),
  ('153','17','Kim Bôi','Huyện Kim Bôi','Kim Boi','huyen','kim-boi'),
  ('154','17','Cao Phong','Huyện Cao Phong','Cao Phong','huyen','cao-phong'),
  ('155','17','Tân Lạc','Huyện Tân Lạc','Tan Lac','huyen','tan-lac'),
  ('156','17','Mai Châu','Huyện Mai Châu','Mai Chau','huyen','mai-chau'),
  ('157','17','Lạc Sơn','Huyện Lạc Sơn','Lac Son','huyen','lac-son'),
  ('158','17','Yên Thủy','Huyện Yên Thủy','Yen Thuy','huyen','yen-thuy'),
  ('159','17','Lạc Thủy','Huyện Lạc Thủy','Lac Thuy','huyen','lac-thuy'),
  ('164','19','Thái Nguyên','Thành phố Thái Nguyên','Thai Nguyen','thanh-pho','thai-nguyen'),
  ('165','19','Sông Công','Thành phố Sông Công','Song Cong','thanh-pho','song-cong'),
  ('167','19','Định Hóa','Huyện Định Hóa','Dinh Hoa','huyen','dinh-hoa'),
  ('168','19','Phú Lương','Huyện Phú Lương','Phu Luong','huyen','phu-luong'),
  ('169','19','Đồng Hỷ','Huyện Đồng Hỷ','Dong Hy','huyen','dong-hy'),
  ('170','19','Võ Nhai','Huyện Võ Nhai','Vo Nhai','huyen','vo-nhai'),
  ('171','19','Đại Từ','Huyện Đại Từ','Dai Tu','huyen','dai-tu'),
  ('172','19','Phổ Yên','Thành phố Phổ Yên','Pho Yen','thanh-pho','pho-yen'),
  ('173','19','Phú Bình','Huyện Phú Bình','Phu Binh','huyen','phu-binh'),
  ('178','20','Lạng Sơn','Thành phố Lạng Sơn','Lang Son','thanh-pho','lang-son'),
  ('180','20','Tràng Định','Huyện Tràng Định','Trang Dinh','huyen','trang-dinh'),
  ('181','20','Bình Gia','Huyện Bình Gia','Binh Gia','huyen','binh-gia'),
  ('182','20','Văn Lãng','Huyện Văn Lãng','Van Lang','huyen','van-lang'),
  ('183','20','Cao Lộc','Huyện Cao Lộc','Cao Loc','huyen','cao-loc'),
  ('184','20','Văn Quan','Huyện Văn Quan','Van Quan','huyen','van-quan'),
  ('185','20','Bắc Sơn','Huyện Bắc Sơn','Bac Son','huyen','bac-son'),
  ('186','20','Hữu Lũng','Huyện Hữu Lũng','Huu Lung','huyen','huu-lung'),
  ('187','20','Chi Lăng','Huyện Chi Lăng','Chi Lang','huyen','chi-lang'),
  ('188','20','Lộc Bình','Huyện Lộc Bình','Loc Binh','huyen','loc-binh'),
  ('189','20','Đình Lập','Huyện Đình Lập','Dinh Lap','huyen','dinh-lap'),
  ('193','22','Hạ Long','Thành phố Hạ Long','Ha Long','thanh-pho','ha-long'),
  ('194','22','Móng Cái','Thành phố Móng Cái','Mong Cai','thanh-pho','mong-cai'),
  ('195','22','Cẩm Phả','Thành phố Cẩm Phả','Cam Pha','thanh-pho','cam-pha'),
  ('196','22','Uông Bí','Thành phố Uông Bí','Uong Bi','thanh-pho','uong-bi'),
  ('198','22','Bình Liêu','Huyện Bình Liêu','Binh Lieu','huyen','binh-lieu'),
  ('199','22','Tiên Yên','Huyện Tiên Yên','Tien Yen','huyen','tien-yen'),
  ('200','22','Đầm Hà','Huyện Đầm Hà','Dam Ha','huyen','dam-ha'),
  ('201','22','Hải Hà','Huyện Hải Hà','Hai Ha','huyen','hai-ha'),
  ('202','22','Ba Chẽ','Huyện Ba Chẽ','Ba Che','huyen','ba-che'),
  ('203','22','Vân Đồn','Huyện Vân Đồn','Van Don','huyen','van-don'),
  ('205','22','Đông Triều','Thị xã Đông Triều','Dong Trieu','thi-xa','dong-trieu'),
  ('206','22','Quảng Yên','Thị xã Quảng Yên','Quang Yen','thi-xa','quang-yen'),
  ('207','22','Cô Tô','Huyện Cô Tô','Co To','huyen','co-to'),
  ('213','24','Bắc Giang','Thành phố Bắc Giang','Bac Giang','thanh-pho','bac-giang'),
  ('215','24','Yên Thế','Huyện Yên Thế','Yen The','huyen','yen-the'),
  ('216','24','Tân Yên','Huyện Tân Yên','Tan Yen','huyen','tan-yen'),
  ('217','24','Lạng Giang','Huyện Lạng Giang','Lang Giang','huyen','lang-giang'),
  ('218','24','Lục Nam','Huyện Lục Nam','Luc Nam','huyen','luc-nam'),
  ('219','24','Lục Ngạn','Huyện Lục Ngạn','Luc Ngan','huyen','luc-ngan'),
  ('220','24','Sơn Động','Huyện Sơn Động','Son Dong','huyen','son-dong'),
  ('221','24','Yên Dũng','Huyện Yên Dũng','Yen Dung','huyen','yen-dung'),
  ('222','24','Việt Yên','Huyện Việt Yên','Viet Yen','huyen','viet-yen'),
  ('223','24','Hiệp Hòa','Huyện Hiệp Hòa','Hiep Hoa','huyen','hiep-hoa'),
  ('227','25','Việt Trì','Thành phố Việt Trì','Viet Tri','thanh-pho','viet-tri'),
  ('228','25','Phú Thọ','Thị xã Phú Thọ','Phu Tho','thi-xa','phu-tho'),
  ('230','25','Đoan Hùng','Huyện Đoan Hùng','Doan Hung','huyen','doan-hung'),
  ('231','25','Hạ Hoà','Huyện Hạ Hoà','Ha Hoa','huyen','ha-hoa'),
  ('232','25','Thanh Ba','Huyện Thanh Ba','Thanh Ba','huyen','thanh-ba'),
  ('233','25','Phù Ninh','Huyện Phù Ninh','Phu Ninh','huyen','phu-ninh'),
  ('234','25','Yên Lập','Huyện Yên Lập','Yen Lap','huyen','yen-lap'),
  ('235','25','Cẩm Khê','Huyện Cẩm Khê','Cam Khe','huyen','cam-khe'),
  ('236','25','Tam Nông','Huyện Tam Nông','Tam Nong','huyen','tam-nong'),
  ('237','25','Lâm Thao','Huyện Lâm Thao','Lam Thao','huyen','lam-thao'),
  ('238','25','Thanh Sơn','Huyện Thanh Sơn','Thanh Son','huyen','thanh-son'),
  ('239','25','Thanh Thuỷ','Huyện Thanh Thuỷ','Thanh Thuy','huyen','thanh-thuy'),
  ('240','25','Tân Sơn','Huyện Tân Sơn','Tan Son','huyen','tan-son'),
  ('243','26','Vĩnh Yên','Thành phố Vĩnh Yên','Vinh Yen','thanh-pho','vinh-yen'),
  ('244','26','Phúc Yên','Thành phố Phúc Yên','Phuc Yen','thanh-pho','phuc-yen'),
  ('246','26','Lập Thạch','Huyện Lập Thạch','Lap Thach','huyen','lap-thach'),
  ('247','26','Tam Dương','Huyện Tam Dương','Tam Duong','huyen','tam-duong'),
  ('248','26','Tam Đảo','Huyện Tam Đảo','Tam Dao','huyen','tam-dao'),
  ('249','26','Bình Xuyên','Huyện Bình Xuyên','Binh Xuyen','huyen','binh-xuyen'),
  ('250','01','Mê Linh','Huyện Mê Linh','Me Linh','huyen','me-linh'),
  ('251','26','Yên Lạc','Huyện Yên Lạc','Yen Lac','huyen','yen-lac'),
  ('252','26','Vĩnh Tường','Huyện Vĩnh Tường','Vinh Tuong','huyen','vinh-tuong'),
  ('253','26','Sông Lô','Huyện Sông Lô','Song Lo','huyen','song-lo'),
  ('256','27','Bắc Ninh','Thành phố Bắc Ninh','Bac Ninh','thanh-pho','bac-ninh'),
  ('258','27','Yên Phong','Huyện Yên Phong','Yen Phong','huyen','yen-phong'),
  ('259','27','Quế Võ','Thị xã Quế Võ','Que Vo','thi-xa','que-vo'),
  ('260','27','Tiên Du','Huyện Tiên Du','Tien Du','huyen','tien-du'),
  ('261','27','Từ Sơn','Thành phố Từ Sơn','Tu Son','thanh-pho','tu-son'),
  ('262','27','Thuận Thành','Thị xã Thuận Thành','Thuan Thanh','thi-xa','thuan-thanh'),
  ('263','27','Gia Bình','Huyện Gia Bình','Gia Binh','huyen','gia-binh'),
  ('264','27','Lương Tài','Huyện Lương Tài','Luong Tai','huyen','luong-tai'),
  ('268','01','Hà Đông','Quận Hà Đông','Ha Dong','quan','ha-dong'),
  ('269','01','Sơn Tây','Thị xã Sơn Tây','Son Tay','thi-xa','son-tay'),
  ('271','01','Ba Vì','Huyện Ba Vì','Ba Vi','huyen','ba-vi'),
  ('272','01','Phúc Thọ','Huyện Phúc Thọ','Phuc Tho','huyen','phuc-tho'),
  ('273','01','Đan Phượng','Huyện Đan Phượng','Dan Phuong','huyen','dan-phuong'),
  ('274','01','Hoài Đức','Huyện Hoài Đức','Hoai Duc','huyen','hoai-duc'),
  ('275','01','Quốc Oai','Huyện Quốc Oai','Quoc Oai','huyen','quoc-oai'),
  ('276','01','Thạch Thất','Huyện Thạch Thất','Thach That','huyen','thach-that'),
  ('277','01','Chương Mỹ','Huyện Chương Mỹ','Chuong My','huyen','chuong-my'),
  ('278','01','Thanh Oai','Huyện Thanh Oai','Thanh Oai','huyen','thanh-oai'),
  ('279','01','Thường Tín','Huyện Thường Tín','Thuong Tin','huyen','thuong-tin'),
  ('280','01','Phú Xuyên','Huyện Phú Xuyên','Phu Xuyen','huyen','phu-xuyen'),
  ('281','01','Ứng Hòa','Huyện Ứng Hòa','Ung Hoa','huyen','ung-hoa'),
  ('282','01','Mỹ Đức','Huyện Mỹ Đức','My Duc','huyen','my-duc'),
  ('288','30','Hải Dương','Thành phố Hải Dương','Hai Duong','thanh-pho','hai-duong'),
  ('290','30','Chí Linh','Thành phố Chí Linh','Chi Linh','thanh-pho','chi-linh'),
  ('291','30','Nam Sách','Huyện Nam Sách','Nam Sach','huyen','nam-sach'),
  ('292','30','Kinh Môn','Thị xã Kinh Môn','Kinh Mon','thi-xa','kinh-mon'),
  ('293','30','Kim Thành','Huyện Kim Thành','Kim Thanh','huyen','kim-thanh'),
  ('294','30','Thanh Hà','Huyện Thanh Hà','Thanh Ha','huyen','thanh-ha'),
  ('295','30','Cẩm Giàng','Huyện Cẩm Giàng','Cam Giang','huyen','cam-giang'),
  ('296','30','Bình Giang','Huyện Bình Giang','Binh Giang','huyen','binh-giang'),
  ('297','30','Gia Lộc','Huyện Gia Lộc','Gia Loc','huyen','gia-loc'),
  ('298','30','Tứ Kỳ','Huyện Tứ Kỳ','Tu Ky','huyen','tu-ky'),
  ('299','30','Ninh Giang','Huyện Ninh Giang','Ninh Giang','huyen','ninh-giang'),
  ('300','30','Thanh Miện','Huyện Thanh Miện','Thanh Mien','huyen','thanh-mien'),
  ('303','31','Hồng Bàng','Quận Hồng Bàng','Hong Bang','quan','hong-bang'),
  ('304','31','Ngô Quyền','Quận Ngô Quyền','Ngo Quyen','quan','ngo-quyen'),
  ('305','31','Lê Chân','Quận Lê Chân','Le Chan','quan','le-chan'),
  ('306','31','Hải An','Quận Hải An','Hai An','quan','hai-an'),
  ('307','31','Kiến An','Quận Kiến An','Kien An','quan','kien-an'),
  ('308','31','Đồ Sơn','Quận Đồ Sơn','Do Son','quan','do-son'),
  ('309','31','Dương Kinh','Quận Dương Kinh','Duong Kinh','quan','duong-kinh'),
  ('311','31','Thuỷ Nguyên','Huyện Thuỷ Nguyên','Thuy Nguyen','huyen','thuy-nguyen'),
  ('312','31','An Dương','Huyện An Dương','An Duong','huyen','an-duong'),
  ('313','31','An Lão','Huyện An Lão','An Lao','huyen','an-lao'),
  ('314','31','Kiến Thuỵ','Huyện Kiến Thuỵ','Kien Thuy','huyen','kien-thuy'),
  ('315','31','Tiên Lãng','Huyện Tiên Lãng','Tien Lang','huyen','tien-lang'),
  ('316','31','Vĩnh Bảo','Huyện Vĩnh Bảo','Vinh Bao','huyen','vinh-bao'),
  ('317','31','Cát Hải','Huyện Cát Hải','Cat Hai','huyen','cat-hai'),
  ('318','31','Bạch Long Vĩ','Huyện Bạch Long Vĩ','Bach Long Vi','huyen','bach-long-vi'),
  ('323','33','Hưng Yên','Thành phố Hưng Yên','Hung Yen','thanh-pho','hung-yen'),
  ('325','33','Văn Lâm','Huyện Văn Lâm','Van Lam','huyen','van-lam'),
  ('326','33','Văn Giang','Huyện Văn Giang','Van Giang','huyen','van-giang'),
  ('327','33','Yên Mỹ','Huyện Yên Mỹ','Yen My','huyen','yen-my'),
  ('328','33','Mỹ Hào','Thị xã Mỹ Hào','My Hao','thi-xa','my-hao'),
  ('329','33','Ân Thi','Huyện Ân Thi','An Thi','huyen','an-thi'),
  ('330','33','Khoái Châu','Huyện Khoái Châu','Khoai Chau','huyen','khoai-chau'),
  ('331','33','Kim Động','Huyện Kim Động','Kim Dong','huyen','kim-dong'),
  ('332','33','Tiên Lữ','Huyện Tiên Lữ','Tien Lu','huyen','tien-lu'),
  ('333','33','Phù Cừ','Huyện Phù Cừ','Phu Cu','huyen','phu-cu'),
  ('336','34','Thái Bình','Thành phố Thái Bình','Thai Binh','thanh-pho','thai-binh'),
  ('338','34','Quỳnh Phụ','Huyện Quỳnh Phụ','Quynh Phu','huyen','quynh-phu'),
  ('339','34','Hưng Hà','Huyện Hưng Hà','Hung Ha','huyen','hung-ha'),
  ('340','34','Đông Hưng','Huyện Đông Hưng','Dong Hung','huyen','dong-hung'),
  ('341','34','Thái Thụy','Huyện Thái Thụy','Thai Thuy','huyen','thai-thuy'),
  ('342','34','Tiền Hải','Huyện Tiền Hải','Tien Hai','huyen','tien-hai'),
  ('343','34','Kiến Xương','Huyện Kiến Xương','Kien Xuong','huyen','kien-xuong'),
  ('344','34','Vũ Thư','Huyện Vũ Thư','Vu Thu','huyen','vu-thu'),
  ('347','35','Phủ Lý','Thành phố Phủ Lý','Phu Ly','thanh-pho','phu-ly'),
  ('349','35','Duy Tiên','Thị xã Duy Tiên','Duy Tien','thi-xa','duy-tien'),
  ('350','35','Kim Bảng','Huyện Kim Bảng','Kim Bang','huyen','kim-bang'),
  ('351','35','Thanh Liêm','Huyện Thanh Liêm','Thanh Liem','huyen','thanh-liem'),
  ('352','35','Bình Lục','Huyện Bình Lục','Binh Luc','huyen','binh-luc'),
  ('353','35','Lý Nhân','Huyện Lý Nhân','Ly Nhan','huyen','ly-nhan'),
  ('356','36','Nam Định','Thành phố Nam Định','Nam Dinh','thanh-pho','nam-dinh'),
  ('358','36','Mỹ Lộc','Huyện Mỹ Lộc','My Loc','huyen','my-loc'),
  ('359','36','Vụ Bản','Huyện Vụ Bản','Vu Ban','huyen','vu-ban'),
  ('360','36','Ý Yên','Huyện Ý Yên','Y Yen','huyen','y-yen'),
  ('361','36','Nghĩa Hưng','Huyện Nghĩa Hưng','Nghia Hung','huyen','nghia-hung'),
  ('362','36','Nam Trực','Huyện Nam Trực','Nam Truc','huyen','nam-truc'),
  ('363','36','Trực Ninh','Huyện Trực Ninh','Truc Ninh','huyen','truc-ninh'),
  ('364','36','Xuân Trường','Huyện Xuân Trường','Xuan Truong','huyen','xuan-truong'),
  ('365','36','Giao Thủy','Huyện Giao Thủy','Giao Thuy','huyen','giao-thuy'),
  ('366','36','Hải Hậu','Huyện Hải Hậu','Hai Hau','huyen','hai-hau'),
  ('369','37','Ninh Bình','Thành phố Ninh Bình','Ninh Binh','thanh-pho','ninh-binh'),
  ('370','37','Tam Điệp','Thành phố Tam Điệp','Tam Diep','thanh-pho','tam-diep'),
  ('372','37','Nho Quan','Huyện Nho Quan','Nho Quan','huyen','nho-quan'),
  ('373','37','Gia Viễn','Huyện Gia Viễn','Gia Vien','huyen','gia-vien'),
  ('374','37','Hoa Lư','Huyện Hoa Lư','Hoa Lu','huyen','hoa-lu'),
  ('375','37','Yên Khánh','Huyện Yên Khánh','Yen Khanh','huyen','yen-khanh'),
  ('376','37','Kim Sơn','Huyện Kim Sơn','Kim Son','huyen','kim-son'),
  ('377','37','Yên Mô','Huyện Yên Mô','Yen Mo','huyen','yen-mo'),
  ('380','38','Thanh Hóa','Thành phố Thanh Hóa','Thanh Hoa','thanh-pho','thanh-hoa'),
  ('381','38','Bỉm Sơn','Thị xã Bỉm Sơn','Bim Son','thi-xa','bim-son'),
  ('382','38','Sầm Sơn','Thành phố Sầm Sơn','Sam Son','thanh-pho','sam-son'),
  ('384','38','Mường Lát','Huyện Mường Lát','Muong Lat','huyen','muong-lat'),
  ('385','38','Quan Hóa','Huyện Quan Hóa','Quan Hoa','huyen','quan-hoa'),
  ('386','38','Bá Thước','Huyện Bá Thước','Ba Thuoc','huyen','ba-thuoc'),
  ('387','38','Quan Sơn','Huyện Quan Sơn','Quan Son','huyen','quan-son'),
  ('388','38','Lang Chánh','Huyện Lang Chánh','Lang Chanh','huyen','lang-chanh'),
  ('389','38','Ngọc Lặc','Huyện Ngọc Lặc','Ngoc Lac','huyen','ngoc-lac'),
  ('390','38','Cẩm Thủy','Huyện Cẩm Thủy','Cam Thuy','huyen','cam-thuy'),
  ('391','38','Thạch Thành','Huyện Thạch Thành','Thach Thanh','huyen','thach-thanh'),
  ('392','38','Hà Trung','Huyện Hà Trung','Ha Trung','huyen','ha-trung'),
  ('393','38','Vĩnh Lộc','Huyện Vĩnh Lộc','Vinh Loc','huyen','vinh-loc'),
  ('394','38','Yên Định','Huyện Yên Định','Yen Dinh','huyen','yen-dinh'),
  ('395','38','Thọ Xuân','Huyện Thọ Xuân','Tho Xuan','huyen','tho-xuan'),
  ('396','38','Thường Xuân','Huyện Thường Xuân','Thuong Xuan','huyen','thuong-xuan'),
  ('397','38','Triệu Sơn','Huyện Triệu Sơn','Trieu Son','huyen','trieu-son'),
  ('398','38','Thiệu Hóa','Huyện Thiệu Hóa','Thieu Hoa','huyen','thieu-hoa'),
  ('399','38','Hoằng Hóa','Huyện Hoằng Hóa','Hoang Hoa','huyen','hoang-hoa'),
  ('400','38','Hậu Lộc','Huyện Hậu Lộc','Hau Loc','huyen','hau-loc'),
  ('401','38','Nga Sơn','Huyện Nga Sơn','Nga Son','huyen','nga-son'),
  ('402','38','Như Xuân','Huyện Như Xuân','Nhu Xuan','huyen','nhu-xuan'),
  ('403','38','Như Thanh','Huyện Như Thanh','Nhu Thanh','huyen','nhu-thanh'),
  ('404','38','Nông Cống','Huyện Nông Cống','Nong Cong','huyen','nong-cong'),
  ('405','38','Đông Sơn','Huyện Đông Sơn','Dong Son','huyen','dong-son'),
  ('406','38','Quảng Xương','Huyện Quảng Xương','Quang Xuong','huyen','quang-xuong'),
  ('407','38','Nghi Sơn','Thị xã Nghi Sơn','Nghi Son','thi-xa','nghi-son'),
  ('412','40','Vinh','Thành phố Vinh','Vinh','thanh-pho','vinh'),
  ('413','40','Cửa Lò','Thị xã Cửa Lò','Cua Lo','thi-xa','cua-lo'),
  ('414','40','Thái Hoà','Thị xã Thái Hoà','Thai Hoa','thi-xa','thai-hoa'),
  ('415','40','Quế Phong','Huyện Quế Phong','Que Phong','huyen','que-phong'),
  ('416','40','Quỳ Châu','Huyện Quỳ Châu','Quy Chau','huyen','quy-chau'),
  ('417','40','Kỳ Sơn','Huyện Kỳ Sơn','Ky Son','huyen','ky-son'),
  ('418','40','Tương Dương','Huyện Tương Dương','Tuong Duong','huyen','tuong-duong'),
  ('419','40','Nghĩa Đàn','Huyện Nghĩa Đàn','Nghia Dan','huyen','nghia-dan'),
  ('420','40','Quỳ Hợp','Huyện Quỳ Hợp','Quy Hop','huyen','quy-hop'),
  ('421','40','Quỳnh Lưu','Huyện Quỳnh Lưu','Quynh Luu','huyen','quynh-luu'),
  ('422','40','Con Cuông','Huyện Con Cuông','Con Cuong','huyen','con-cuong'),
  ('423','40','Tân Kỳ','Huyện Tân Kỳ','Tan Ky','huyen','tan-ky'),
  ('424','40','Anh Sơn','Huyện Anh Sơn','Anh Son','huyen','anh-son'),
  ('425','40','Diễn Châu','Huyện Diễn Châu','Dien Chau','huyen','dien-chau'),
  ('426','40','Yên Thành','Huyện Yên Thành','Yen Thanh','huyen','yen-thanh'),
  ('427','40','Đô Lương','Huyện Đô Lương','Do Luong','huyen','do-luong'),
  ('428','40','Thanh Chương','Huyện Thanh Chương','Thanh Chuong','huyen','thanh-chuong'),
  ('429','40','Nghi Lộc','Huyện Nghi Lộc','Nghi Loc','huyen','nghi-loc'),
  ('430','40','Nam Đàn','Huyện Nam Đàn','Nam Dan','huyen','nam-dan'),
  ('431','40','Hưng Nguyên','Huyện Hưng Nguyên','Hung Nguyen','huyen','hung-nguyen'),
  ('432','40','Hoàng Mai','Thị xã Hoàng Mai','Hoang Mai','thi-xa','hoang-mai'),
  ('436','42','Hà Tĩnh','Thành phố Hà Tĩnh','Ha Tinh','thanh-pho','ha-tinh'),
  ('437','42','Hồng Lĩnh','Thị xã Hồng Lĩnh','Hong Linh','thi-xa','hong-linh'),
  ('439','42','Hương Sơn','Huyện Hương Sơn','Huong Son','huyen','huong-son'),
  ('440','42','Đức Thọ','Huyện Đức Thọ','Duc Tho','huyen','duc-tho'),
  ('441','42','Vũ Quang','Huyện Vũ Quang','Vu Quang','huyen','vu-quang'),
  ('442','42','Nghi Xuân','Huyện Nghi Xuân','Nghi Xuan','huyen','nghi-xuan'),
  ('443','42','Can Lộc','Huyện Can Lộc','Can Loc','huyen','can-loc'),
  ('444','42','Hương Khê','Huyện Hương Khê','Huong Khe','huyen','huong-khe'),
  ('445','42','Thạch Hà','Huyện Thạch Hà','Thach Ha','huyen','thach-ha'),
  ('446','42','Cẩm Xuyên','Huyện Cẩm Xuyên','Cam Xuyen','huyen','cam-xuyen'),
  ('447','42','Kỳ Anh','Huyện Kỳ Anh','Ky Anh','huyen','ky-anh'),
  ('448','42','Lộc Hà','Huyện Lộc Hà','Loc Ha','huyen','loc-ha'),
  ('449','42','Kỳ Anh','Thị xã Kỳ Anh','Ky Anh','thi-xa','ky-anh'),
  ('450','44','Đồng Hới','Thành Phố Đồng Hới','Dong Hoi','thanh-pho','dong-hoi'),
  ('452','44','Minh Hóa','Huyện Minh Hóa','Minh Hoa','huyen','minh-hoa'),
  ('453','44','Tuyên Hóa','Huyện Tuyên Hóa','Tuyen Hoa','huyen','tuyen-hoa'),
  ('454','44','Quảng Trạch','Huyện Quảng Trạch','Quang Trach','huyen','quang-trach'),
  ('455','44','Bố Trạch','Huyện Bố Trạch','Bo Trach','huyen','bo-trach'),
  ('456','44','Quảng Ninh','Huyện Quảng Ninh','Quang Ninh','huyen','quang-ninh'),
  ('457','44','Lệ Thủy','Huyện Lệ Thủy','Le Thuy','huyen','le-thuy'),
  ('458','44','Ba Đồn','Thị xã Ba Đồn','Ba Don','thi-xa','ba-don'),
  ('461','45','Đông Hà','Thành phố Đông Hà','Dong Ha','thanh-pho','dong-ha'),
  ('462','45','Quảng Trị','Thị xã Quảng Trị','Quang Tri','thi-xa','quang-tri'),
  ('464','45','Vĩnh Linh','Huyện Vĩnh Linh','Vinh Linh','huyen','vinh-linh'),
  ('465','45','Hướng Hóa','Huyện Hướng Hóa','Huong Hoa','huyen','huong-hoa'),
  ('466','45','Gio Linh','Huyện Gio Linh','Gio Linh','huyen','gio-linh'),
  ('467','45','Đa Krông','Huyện Đa Krông','Da Krong','huyen','da-krong'),
  ('468','45','Cam Lộ','Huyện Cam Lộ','Cam Lo','huyen','cam-lo'),
  ('469','45','Triệu Phong','Huyện Triệu Phong','Trieu Phong','huyen','trieu-phong'),
  ('470','45','Hải Lăng','Huyện Hải Lăng','Hai Lang','huyen','hai-lang'),
  ('471','45','Cồn Cỏ','Huyện Cồn Cỏ','Con Co','huyen','con-co'),
  ('474','46','Huế','Thành phố Huế','Hue','thanh-pho','hue'),
  ('476','46','Phong Điền','Huyện Phong Điền','Phong Dien','huyen','phong-dien'),
  ('477','46','Quảng Điền','Huyện Quảng Điền','Quang Dien','huyen','quang-dien'),
  ('478','46','Phú Vang','Huyện Phú Vang','Phu Vang','huyen','phu-vang'),
  ('479','46','Hương Thủy','Thị xã Hương Thủy','Huong Thuy','thi-xa','huong-thuy'),
  ('480','46','Hương Trà','Thị xã Hương Trà','Huong Tra','thi-xa','huong-tra'),
  ('481','46','A Lưới','Huyện A Lưới','A Luoi','huyen','a-luoi'),
  ('482','46','Phú Lộc','Huyện Phú Lộc','Phu Loc','huyen','phu-loc'),
  ('483','46','Nam Đông','Huyện Nam Đông','Nam Dong','huyen','nam-dong'),
  ('490','48','Liên Chiểu','Quận Liên Chiểu','Lien Chieu','quan','lien-chieu'),
  ('491','48','Thanh Khê','Quận Thanh Khê','Thanh Khe','quan','thanh-khe'),
  ('492','48','Hải Châu','Quận Hải Châu','Hai Chau','quan','hai-chau'),
  ('493','48','Sơn Trà','Quận Sơn Trà','Son Tra','quan','son-tra'),
  ('494','48','Ngũ Hành Sơn','Quận Ngũ Hành Sơn','Ngu Hanh Son','quan','ngu-hanh-son'),
  ('495','48','Cẩm Lệ','Quận Cẩm Lệ','Cam Le','quan','cam-le'),
  ('497','48','Hòa Vang','Huyện Hòa Vang','Hoa Vang','huyen','hoa-vang'),
  ('498','48','Hoàng Sa','Huyện Hoàng Sa','Hoang Sa','huyen','hoang-sa'),
  ('502','49','Tam Kỳ','Thành phố Tam Kỳ','Tam Ky','thanh-pho','tam-ky'),
  ('503','49','Hội An','Thành phố Hội An','Hoi An','thanh-pho','hoi-an'),
  ('504','49','Tây Giang','Huyện Tây Giang','Tay Giang','huyen','tay-giang'),
  ('505','49','Đông Giang','Huyện Đông Giang','Dong Giang','huyen','dong-giang'),
  ('506','49','Đại Lộc','Huyện Đại Lộc','Dai Loc','huyen','dai-loc'),
  ('507','49','Điện Bàn','Thị xã Điện Bàn','Dien Ban','thi-xa','dien-ban'),
  ('508','49','Duy Xuyên','Huyện Duy Xuyên','Duy Xuyen','huyen','duy-xuyen'),
  ('509','49','Quế Sơn','Huyện Quế Sơn','Que Son','huyen','que-son'),
  ('510','49','Nam Giang','Huyện Nam Giang','Nam Giang','huyen','nam-giang'),
  ('511','49','Phước Sơn','Huyện Phước Sơn','Phuoc Son','huyen','phuoc-son'),
  ('512','49','Hiệp Đức','Huyện Hiệp Đức','Hiep Duc','huyen','hiep-duc'),
  ('513','49','Thăng Bình','Huyện Thăng Bình','Thang Binh','huyen','thang-binh'),
  ('514','49','Tiên Phước','Huyện Tiên Phước','Tien Phuoc','huyen','tien-phuoc'),
  ('515','49','Bắc Trà My','Huyện Bắc Trà My','Bac Tra My','huyen','bac-tra-my'),
  ('516','49','Nam Trà My','Huyện Nam Trà My','Nam Tra My','huyen','nam-tra-my'),
  ('517','49','Núi Thành','Huyện Núi Thành','Nui Thanh','huyen','nui-thanh'),
  ('518','49','Phú Ninh','Huyện Phú Ninh','Phu Ninh','huyen','phu-ninh'),
  ('519','49','Nông Sơn','Huyện Nông Sơn','Nong Son','huyen','nong-son'),
  ('522','51','Quảng Ngãi','Thành phố Quảng Ngãi','Quang Ngai','thanh-pho','quang-ngai'),
  ('524','51','Bình Sơn','Huyện Bình Sơn','Binh Son','huyen','binh-son'),
  ('525','51','Trà Bồng','Huyện Trà Bồng','Tra Bong','huyen','tra-bong'),
  ('527','51','Sơn Tịnh','Huyện Sơn Tịnh','Son Tinh','huyen','son-tinh'),
  ('528','51','Tư Nghĩa','Huyện Tư Nghĩa','Tu Nghia','huyen','tu-nghia'),
  ('529','51','Sơn Hà','Huyện Sơn Hà','Son Ha','huyen','son-ha'),
  ('530','51','Sơn Tây','Huyện Sơn Tây','Son Tay','huyen','son-tay'),
  ('531','51','Minh Long','Huyện Minh Long','Minh Long','huyen','minh-long'),
  ('532','51','Nghĩa Hành','Huyện Nghĩa Hành','Nghia Hanh','huyen','nghia-hanh'),
  ('533','51','Mộ Đức','Huyện Mộ Đức','Mo Duc','huyen','mo-duc'),
  ('534','51','Đức Phổ','Thị xã Đức Phổ','Duc Pho','thi-xa','duc-pho'),
  ('535','51','Ba Tơ','Huyện Ba Tơ','Ba To','huyen','ba-to'),
  ('536','51','Lý Sơn','Huyện Lý Sơn','Ly Son','huyen','ly-son'),
  ('540','52','Quy Nhơn','Thành phố Quy Nhơn','Quy Nhon','thanh-pho','quy-nhon'),
  ('542','52','An Lão','Huyện An Lão','An Lao','huyen','an-lao'),
  ('543','52','Hoài Nhơn','Thị xã Hoài Nhơn','Hoai Nhon','thi-xa','hoai-nhon'),
  ('544','52','Hoài Ân','Huyện Hoài Ân','Hoai An','huyen','hoai-an'),
  ('545','52','Phù Mỹ','Huyện Phù Mỹ','Phu My','huyen','phu-my'),
  ('546','52','Vĩnh Thạnh','Huyện Vĩnh Thạnh','Vinh Thanh','huyen','vinh-thanh'),
  ('547','52','Tây Sơn','Huyện Tây Sơn','Tay Son','huyen','tay-son'),
  ('548','52','Phù Cát','Huyện Phù Cát','Phu Cat','huyen','phu-cat'),
  ('549','52','An Nhơn','Thị xã An Nhơn','An Nhon','thi-xa','an-nhon'),
  ('550','52','Tuy Phước','Huyện Tuy Phước','Tuy Phuoc','huyen','tuy-phuoc'),
  ('551','52','Vân Canh','Huyện Vân Canh','Van Canh','huyen','van-canh'),
  ('555','54','Tuy Hoà','Thành phố Tuy Hoà','Tuy Hoa','thanh-pho','tuy-hoa'),
  ('557','54','Sông Cầu','Thị xã Sông Cầu','Song Cau','thi-xa','song-cau'),
  ('558','54','Đồng Xuân','Huyện Đồng Xuân','Dong Xuan','huyen','dong-xuan'),
  ('559','54','Tuy An','Huyện Tuy An','Tuy An','huyen','tuy-an'),
  ('560','54','Sơn Hòa','Huyện Sơn Hòa','Son Hoa','huyen','son-hoa'),
  ('561','54','Sông Hinh','Huyện Sông Hinh','Song Hinh','huyen','song-hinh'),
  ('562','54','Tây Hoà','Huyện Tây Hoà','Tay Hoa','huyen','tay-hoa'),
  ('563','54','Phú Hoà','Huyện Phú Hoà','Phu Hoa','huyen','phu-hoa'),
  ('564','54','Đông Hòa','Thị xã Đông Hòa','Dong Hoa','thi-xa','dong-hoa'),
  ('568','56','Nha Trang','Thành phố Nha Trang','Nha Trang','thanh-pho','nha-trang'),
  ('569','56','Cam Ranh','Thành phố Cam Ranh','Cam Ranh','thanh-pho','cam-ranh'),
  ('570','56','Cam Lâm','Huyện Cam Lâm','Cam Lam','huyen','cam-lam'),
  ('571','56','Vạn Ninh','Huyện Vạn Ninh','Van Ninh','huyen','van-ninh'),
  ('572','56','Ninh Hòa','Thị xã Ninh Hòa','Ninh Hoa','thi-xa','ninh-hoa'),
  ('573','56','Khánh Vĩnh','Huyện Khánh Vĩnh','Khanh Vinh','huyen','khanh-vinh'),
  ('574','56','Diên Khánh','Huyện Diên Khánh','Dien Khanh','huyen','dien-khanh'),
  ('575','56','Khánh Sơn','Huyện Khánh Sơn','Khanh Son','huyen','khanh-son'),
  ('576','56','Trường Sa','Huyện Trường Sa','Truong Sa','huyen','truong-sa'),
  ('582','58','Phan Rang-Tháp Chàm','Thành phố Phan Rang-Tháp Chàm','Phan Rang-Thap Cham','thanh-pho','phan-rang-thap-cham'),
  ('584','58','Bác Ái','Huyện Bác Ái','Bac Ai','huyen','bac-ai'),
  ('585','58','Ninh Sơn','Huyện Ninh Sơn','Ninh Son','huyen','ninh-son'),
  ('586','58','Ninh Hải','Huyện Ninh Hải','Ninh Hai','huyen','ninh-hai'),
  ('587','58','Ninh Phước','Huyện Ninh Phước','Ninh Phuoc','huyen','ninh-phuoc'),
  ('588','58','Thuận Bắc','Huyện Thuận Bắc','Thuan Bac','huyen','thuan-bac'),
  ('589','58','Thuận Nam','Huyện Thuận Nam','Thuan Nam','huyen','thuan-nam'),
  ('593','60','Phan Thiết','Thành phố Phan Thiết','Phan Thiet','thanh-pho','phan-thiet'),
  ('594','60','La Gi','Thị xã La Gi','La Gi','thi-xa','la-gi'),
  ('595','60','Tuy Phong','Huyện Tuy Phong','Tuy Phong','huyen','tuy-phong'),
  ('596','60','Bắc Bình','Huyện Bắc Bình','Bac Binh','huyen','bac-binh'),
  ('597','60','Hàm Thuận Bắc','Huyện Hàm Thuận Bắc','Ham Thuan Bac','huyen','ham-thuan-bac'),
  ('598','60','Hàm Thuận Nam','Huyện Hàm Thuận Nam','Ham Thuan Nam','huyen','ham-thuan-nam'),
  ('599','60','Tánh Linh','Huyện Tánh Linh','Tanh Linh','huyen','tanh-linh'),
  ('600','60','Đức Linh','Huyện Đức Linh','Duc Linh','huyen','duc-linh'),
  ('601','60','Hàm Tân','Huyện Hàm Tân','Ham Tan','huyen','ham-tan'),
  ('602','60','Phú Quí','Huyện Phú Quí','Phu Qui','huyen','phu-qui'),
  ('608','62','Kon Tum','Thành phố Kon Tum','Kon Tum','thanh-pho','kon-tum'),
  ('610','62','Đắk Glei','Huyện Đắk Glei','Dak Glei','huyen','dak-glei'),
  ('611','62','Ngọc Hồi','Huyện Ngọc Hồi','Ngoc Hoi','huyen','ngoc-hoi'),
  ('612','62','Đắk Tô','Huyện Đắk Tô','Dak To','huyen','dak-to'),
  ('613','62','Kon Plông','Huyện Kon Plông','Kon Plong','huyen','kon-plong'),
  ('614','62','Kon Rẫy','Huyện Kon Rẫy','Kon Ray','huyen','kon-ray'),
  ('615','62','Đắk Hà','Huyện Đắk Hà','Dak Ha','huyen','dak-ha'),
  ('616','62','Sa Thầy','Huyện Sa Thầy','Sa Thay','huyen','sa-thay'),
  ('617','62','Tu Mơ Rông','Huyện Tu Mơ Rông','Tu Mo Rong','huyen','tu-mo-rong'),
  ('618','62','Ia H'' Drai','Huyện Ia H'' Drai','Ia H'' Drai','huyen','ia-h-drai'),
  ('622','64','Pleiku','Thành phố Pleiku','Pleiku','thanh-pho','pleiku'),
  ('623','64','An Khê','Thị xã An Khê','An Khe','thi-xa','an-khe'),
  ('624','64','Ayun Pa','Thị xã Ayun Pa','Ayun Pa','thi-xa','ayun-pa'),
  ('625','64','KBang','Huyện KBang','Kbang','huyen','kbang'),
  ('626','64','Đăk Đoa','Huyện Đăk Đoa','Dak Doa','huyen','dak-doa'),
  ('627','64','Chư Păh','Huyện Chư Păh','Chu Pah','huyen','chu-pah'),
  ('628','64','Ia Grai','Huyện Ia Grai','Ia Grai','huyen','ia-grai'),
  ('629','64','Mang Yang','Huyện Mang Yang','Mang Yang','huyen','mang-yang'),
  ('630','64','Kông Chro','Huyện Kông Chro','Kong Chro','huyen','kong-chro'),
  ('631','64','Đức Cơ','Huyện Đức Cơ','Duc Co','huyen','duc-co'),
  ('632','64','Chư Prông','Huyện Chư Prông','Chu Prong','huyen','chu-prong'),
  ('633','64','Chư Sê','Huyện Chư Sê','Chu Se','huyen','chu-se'),
  ('634','64','Đăk Pơ','Huyện Đăk Pơ','Dak Po','huyen','dak-po'),
  ('635','64','Ia Pa','Huyện Ia Pa','Ia Pa','huyen','ia-pa'),
  ('637','64','Krông Pa','Huyện Krông Pa','Krong Pa','huyen','krong-pa'),
  ('638','64','Phú Thiện','Huyện Phú Thiện','Phu Thien','huyen','phu-thien'),
  ('639','64','Chư Pưh','Huyện Chư Pưh','Chu Puh','huyen','chu-puh'),
  ('643','66','Buôn Ma Thuột','Thành phố Buôn Ma Thuột','Buon Ma Thuot','thanh-pho','buon-ma-thuot'),
  ('644','66','Buôn Hồ','Thị xã Buôn Hồ','Buon Ho','thi-xa','buon-ho'),
  ('645','66','Ea H''leo','Huyện Ea H''leo','Ea H''Leo','huyen','ea-h-leo'),
  ('646','66','Ea Súp','Huyện Ea Súp','Ea Sup','huyen','ea-sup'),
  ('647','66','Buôn Đôn','Huyện Buôn Đôn','Buon Don','huyen','buon-don'),
  ('648','66','Cư M''gar','Huyện Cư M''gar','Cu M''Gar','huyen','cu-m-gar'),
  ('649','66','Krông Búk','Huyện Krông Búk','Krong Buk','huyen','krong-buk'),
  ('650','66','Krông Năng','Huyện Krông Năng','Krong Nang','huyen','krong-nang'),
  ('651','66','Ea Kar','Huyện Ea Kar','Ea Kar','huyen','ea-kar'),
  ('652','66','M''Đrắk','Huyện M''Đrắk','M''Drak','huyen','m-drak'),
  ('653','66','Krông Bông','Huyện Krông Bông','Krong Bong','huyen','krong-bong'),
  ('654','66','Krông Pắc','Huyện Krông Pắc','Krong Pac','huyen','krong-pac'),
  ('655','66','Krông A Na','Huyện Krông A Na','Krong A Na','huyen','krong-a-na'),
  ('656','66','Lắk','Huyện Lắk','Lak','huyen','lak'),
  ('657','66','Cư Kuin','Huyện Cư Kuin','Cu Kuin','huyen','cu-kuin'),
  ('660','67','Gia Nghĩa','Thành phố Gia Nghĩa','Gia Nghia','thanh-pho','gia-nghia'),
  ('661','67','Đăk Glong','Huyện Đăk Glong','Dak Glong','huyen','dak-glong'),
  ('662','67','Cư Jút','Huyện Cư Jút','Cu Jut','huyen','cu-jut'),
  ('663','67','Đắk Mil','Huyện Đắk Mil','Dak Mil','huyen','dak-mil'),
  ('664','67','Krông Nô','Huyện Krông Nô','Krong No','huyen','krong-no'),
  ('665','67','Đắk Song','Huyện Đắk Song','Dak Song','huyen','dak-song'),
  ('666','67','Đắk R''Lấp','Huyện Đắk R''Lấp','Dak R''Lap','huyen','dak-r-lap'),
  ('667','67','Tuy Đức','Huyện Tuy Đức','Tuy Duc','huyen','tuy-duc'),
  ('672','68','Đà Lạt','Thành phố Đà Lạt','Da Lat','thanh-pho','da-lat'),
  ('673','68','Bảo Lộc','Thành phố Bảo Lộc','Bao Loc','thanh-pho','bao-loc'),
  ('674','68','Đam Rông','Huyện Đam Rông','Dam Rong','huyen','dam-rong'),
  ('675','68','Lạc Dương','Huyện Lạc Dương','Lac Duong','huyen','lac-duong'),
  ('676','68','Lâm Hà','Huyện Lâm Hà','Lam Ha','huyen','lam-ha'),
  ('677','68','Đơn Dương','Huyện Đơn Dương','Don Duong','huyen','don-duong'),
  ('678','68','Đức Trọng','Huyện Đức Trọng','Duc Trong','huyen','duc-trong'),
  ('679','68','Di Linh','Huyện Di Linh','Di Linh','huyen','di-linh'),
  ('680','68','Bảo Lâm','Huyện Bảo Lâm','Bao Lam','huyen','bao-lam'),
  ('681','68','Đạ Huoai','Huyện Đạ Huoai','Da Huoai','huyen','da-huoai'),
  ('682','68','Đạ Tẻh','Huyện Đạ Tẻh','Da Teh','huyen','da-teh'),
  ('683','68','Cát Tiên','Huyện Cát Tiên','Cat Tien','huyen','cat-tien'),
  ('688','70','Phước Long','Thị xã Phước Long','Phuoc Long','thi-xa','phuoc-long'),
  ('689','70','Đồng Xoài','Thành phố Đồng Xoài','Dong Xoai','thanh-pho','dong-xoai'),
  ('690','70','Bình Long','Thị xã Bình Long','Binh Long','thi-xa','binh-long'),
  ('691','70','Bù Gia Mập','Huyện Bù Gia Mập','Bu Gia Map','huyen','bu-gia-map'),
  ('692','70','Lộc Ninh','Huyện Lộc Ninh','Loc Ninh','huyen','loc-ninh'),
  ('693','70','Bù Đốp','Huyện Bù Đốp','Bu Dop','huyen','bu-dop'),
  ('694','70','Hớn Quản','Huyện Hớn Quản','Hon Quan','huyen','hon-quan'),
  ('695','70','Đồng Phú','Huyện Đồng Phú','Dong Phu','huyen','dong-phu'),
  ('696','70','Bù Đăng','Huyện Bù Đăng','Bu Dang','huyen','bu-dang'),
  ('697','70','Chơn Thành','Thị xã Chơn Thành','Chon Thanh','thi-xa','chon-thanh'),
  ('698','70','Phú Riềng','Huyện Phú Riềng','Phu Rieng','huyen','phu-rieng'),
  ('703','72','Tây Ninh','Thành phố Tây Ninh','Tay Ninh','thanh-pho','tay-ninh'),
  ('705','72','Tân Biên','Huyện Tân Biên','Tan Bien','huyen','tan-bien'),
  ('706','72','Tân Châu','Huyện Tân Châu','Tan Chau','huyen','tan-chau'),
  ('707','72','Dương Minh Châu','Huyện Dương Minh Châu','Duong Minh Chau','huyen','duong-minh-chau'),
  ('708','72','Châu Thành','Huyện Châu Thành','Chau Thanh','huyen','chau-thanh'),
  ('709','72','Hòa Thành','Thị xã Hòa Thành','Hoa Thanh','thi-xa','hoa-thanh'),
  ('710','72','Gò Dầu','Huyện Gò Dầu','Go Dau','huyen','go-dau'),
  ('711','72','Bến Cầu','Huyện Bến Cầu','Ben Cau','huyen','ben-cau'),
  ('712','72','Trảng Bàng','Thị xã Trảng Bàng','Trang Bang','thi-xa','trang-bang'),
  ('718','74','Thủ Dầu Một','Thành phố Thủ Dầu Một','Thu Dau Mot','thanh-pho','thu-dau-mot'),
  ('719','74','Bàu Bàng','Huyện Bàu Bàng','Bau Bang','huyen','bau-bang'),
  ('720','74','Dầu Tiếng','Huyện Dầu Tiếng','Dau Tieng','huyen','dau-tieng'),
  ('721','74','Bến Cát','Thị xã Bến Cát','Ben Cat','thi-xa','ben-cat'),
  ('722','74','Phú Giáo','Huyện Phú Giáo','Phu Giao','huyen','phu-giao'),
  ('723','74','Tân Uyên','Thành phố Tân Uyên','Tan Uyen','thanh-pho','tan-uyen'),
  ('724','74','Dĩ An','Thành phố Dĩ An','Di An','thanh-pho','di-an'),
  ('725','74','Thuận An','Thành phố Thuận An','Thuan An','thanh-pho','thuan-an'),
  ('726','74','Bắc Tân Uyên','Huyện Bắc Tân Uyên','Bac Tan Uyen','huyen','bac-tan-uyen'),
  ('731','75','Biên Hòa','Thành phố Biên Hòa','Bien Hoa','thanh-pho','bien-hoa'),
  ('732','75','Long Khánh','Thành phố Long Khánh','Long Khanh','thanh-pho','long-khanh'),
  ('734','75','Tân Phú','Huyện Tân Phú','Tan Phu','huyen','tan-phu'),
  ('735','75','Vĩnh Cửu','Huyện Vĩnh Cửu','Vinh Cuu','huyen','vinh-cuu'),
  ('736','75','Định Quán','Huyện Định Quán','Dinh Quan','huyen','dinh-quan'),
  ('737','75','Trảng Bom','Huyện Trảng Bom','Trang Bom','huyen','trang-bom'),
  ('738','75','Thống Nhất','Huyện Thống Nhất','Thong Nhat','huyen','thong-nhat'),
  ('739','75','Cẩm Mỹ','Huyện Cẩm Mỹ','Cam My','huyen','cam-my'),
  ('740','75','Long Thành','Huyện Long Thành','Long Thanh','huyen','long-thanh'),
  ('741','75','Xuân Lộc','Huyện Xuân Lộc','Xuan Loc','huyen','xuan-loc'),
  ('742','75','Nhơn Trạch','Huyện Nhơn Trạch','Nhon Trach','huyen','nhon-trach'),
  ('747','77','Vũng Tàu','Thành phố Vũng Tàu','Vung Tau','thanh-pho','vung-tau'),
  ('748','77','Bà Rịa','Thành phố Bà Rịa','Ba Ria','thanh-pho','ba-ria'),
  ('750','77','Châu Đức','Huyện Châu Đức','Chau Duc','huyen','chau-duc'),
  ('751','77','Xuyên Mộc','Huyện Xuyên Mộc','Xuyen Moc','huyen','xuyen-moc'),
  ('752','77','Long Điền','Huyện Long Điền','Long Dien','huyen','long-dien'),
  ('753','77','Đất Đỏ','Huyện Đất Đỏ','Dat Do','huyen','dat-do'),
  ('754','77','Phú Mỹ','Thị xã Phú Mỹ','Phu My','thi-xa','phu-my'),
  ('755','77','Côn Đảo','Huyện Côn Đảo','Con Dao','huyen','con-dao'),
  ('760','79','1','Quận 1','1','quan','1'),
  ('761','79','12','Quận 12','12','quan','12'),
  ('764','79','Gò Vấp','Quận Gò Vấp','Go Vap','quan','go-vap'),
  ('765','79','Bình Thạnh','Quận Bình Thạnh','Binh Thanh','quan','binh-thanh'),
  ('766','79','Tân Bình','Quận Tân Bình','Tan Binh','quan','tan-binh'),
  ('767','79','Tân Phú','Quận Tân Phú','Tan Phu','quan','tan-phu'),
  ('768','79','Phú Nhuận','Quận Phú Nhuận','Phu Nhuan','quan','phu-nhuan'),
  ('769','79','Thủ Đức','Thành phố Thủ Đức','Thu Duc','thanh-pho','thu-duc'),
  ('770','79','3','Quận 3','3','quan','3'),
  ('771','79','10','Quận 10','10','quan','10'),
  ('772','79','11','Quận 11','11','quan','11'),
  ('773','79','4','Quận 4','4','quan','4'),
  ('774','79','5','Quận 5','5','quan','5'),
  ('775','79','6','Quận 6','6','quan','6'),
  ('776','79','8','Quận 8','8','quan','8'),
  ('777','79','Bình Tân','Quận Bình Tân','Binh Tan','quan','binh-tan'),
  ('778','79','7','Quận 7','7','quan','7'),
  ('783','79','Củ Chi','Huyện Củ Chi','Cu Chi','huyen','cu-chi'),
  ('784','79','Hóc Môn','Huyện Hóc Môn','Hoc Mon','huyen','hoc-mon'),
  ('785','79','Bình Chánh','Huyện Bình Chánh','Binh Chanh','huyen','binh-chanh'),
  ('786','79','Nhà Bè','Huyện Nhà Bè','Nha Be','huyen','nha-be'),
  ('787','79','Cần Giờ','Huyện Cần Giờ','Can Gio','huyen','can-gio'),
  ('794','80','Tân An','Thành phố Tân An','Tan An','thanh-pho','tan-an'),
  ('795','80','Kiến Tường','Thị xã Kiến Tường','Kien Tuong','thi-xa','kien-tuong'),
  ('796','80','Tân Hưng','Huyện Tân Hưng','Tan Hung','huyen','tan-hung'),
  ('797','80','Vĩnh Hưng','Huyện Vĩnh Hưng','Vinh Hung','huyen','vinh-hung'),
  ('798','80','Mộc Hóa','Huyện Mộc Hóa','Moc Hoa','huyen','moc-hoa'),
  ('799','80','Tân Thạnh','Huyện Tân Thạnh','Tan Thanh','huyen','tan-thanh'),
  ('800','80','Thạnh Hóa','Huyện Thạnh Hóa','Thanh Hoa','huyen','thanh-hoa'),
  ('801','80','Đức Huệ','Huyện Đức Huệ','Duc Hue','huyen','duc-hue'),
  ('802','80','Đức Hòa','Huyện Đức Hòa','Duc Hoa','huyen','duc-hoa'),
  ('803','80','Bến Lức','Huyện Bến Lức','Ben Luc','huyen','ben-luc'),
  ('804','80','Thủ Thừa','Huyện Thủ Thừa','Thu Thua','huyen','thu-thua'),
  ('805','80','Tân Trụ','Huyện Tân Trụ','Tan Tru','huyen','tan-tru'),
  ('806','80','Cần Đước','Huyện Cần Đước','Can Duoc','huyen','can-duoc'),
  ('807','80','Cần Giuộc','Huyện Cần Giuộc','Can Giuoc','huyen','can-giuoc'),
  ('808','80','Châu Thành','Huyện Châu Thành','Chau Thanh','huyen','chau-thanh'),
  ('815','82','Mỹ Tho','Thành phố Mỹ Tho','My Tho','thanh-pho','my-tho'),
  ('816','82','Gò Công','Thị xã Gò Công','Go Cong','thi-xa','go-cong'),
  ('817','82','Cai Lậy','Thị xã Cai Lậy','Cai Lay','thi-xa','cai-lay'),
  ('818','82','Tân Phước','Huyện Tân Phước','Tan Phuoc','huyen','tan-phuoc'),
  ('819','82','Cái Bè','Huyện Cái Bè','Cai Be','huyen','cai-be'),
  ('820','82','Cai Lậy','Huyện Cai Lậy','Cai Lay','huyen','cai-lay'),
  ('821','82','Châu Thành','Huyện Châu Thành','Chau Thanh','huyen','chau-thanh'),
  ('822','82','Chợ Gạo','Huyện Chợ Gạo','Cho Gao','huyen','cho-gao'),
  ('823','82','Gò Công Tây','Huyện Gò Công Tây','Go Cong Tay','huyen','go-cong-tay'),
  ('824','82','Gò Công Đông','Huyện Gò Công Đông','Go Cong Dong','huyen','go-cong-dong'),
  ('825','82','Tân Phú Đông','Huyện Tân Phú Đông','Tan Phu Dong','huyen','tan-phu-dong'),
  ('829','83','Bến Tre','Thành phố Bến Tre','Ben Tre','thanh-pho','ben-tre'),
  ('831','83','Châu Thành','Huyện Châu Thành','Chau Thanh','huyen','chau-thanh'),
  ('832','83','Chợ Lách','Huyện Chợ Lách','Cho Lach','huyen','cho-lach'),
  ('833','83','Mỏ Cày Nam','Huyện Mỏ Cày Nam','Mo Cay Nam','huyen','mo-cay-nam'),
  ('834','83','Giồng Trôm','Huyện Giồng Trôm','Giong Trom','huyen','giong-trom'),
  ('835','83','Bình Đại','Huyện Bình Đại','Binh Dai','huyen','binh-dai'),
  ('836','83','Ba Tri','Huyện Ba Tri','Ba Tri','huyen','ba-tri'),
  ('837','83','Thạnh Phú','Huyện Thạnh Phú','Thanh Phu','huyen','thanh-phu'),
  ('838','83','Mỏ Cày Bắc','Huyện Mỏ Cày Bắc','Mo Cay Bac','huyen','mo-cay-bac'),
  ('842','84','Trà Vinh','Thành phố Trà Vinh','Tra Vinh','thanh-pho','tra-vinh'),
  ('844','84','Càng Long','Huyện Càng Long','Cang Long','huyen','cang-long'),
  ('845','84','Cầu Kè','Huyện Cầu Kè','Cau Ke','huyen','cau-ke'),
  ('846','84','Tiểu Cần','Huyện Tiểu Cần','Tieu Can','huyen','tieu-can'),
  ('847','84','Châu Thành','Huyện Châu Thành','Chau Thanh','huyen','chau-thanh'),
  ('848','84','Cầu Ngang','Huyện Cầu Ngang','Cau Ngang','huyen','cau-ngang'),
  ('849','84','Trà Cú','Huyện Trà Cú','Tra Cu','huyen','tra-cu'),
  ('850','84','Duyên Hải','Huyện Duyên Hải','Duyen Hai','huyen','duyen-hai'),
  ('851','84','Duyên Hải','Thị xã Duyên Hải','Duyen Hai','thi-xa','duyen-hai'),
  ('855','86','Vĩnh Long','Thành phố Vĩnh Long','Vinh Long','thanh-pho','vinh-long'),
  ('857','86','Long Hồ','Huyện Long Hồ','Long Ho','huyen','long-ho'),
  ('858','86','Mang Thít','Huyện Mang Thít','Mang Thit','huyen','mang-thit'),
  ('859','86','Vũng Liêm','Huyện  Vũng Liêm','Vung Liem','huyen','vung-liem'),
  ('860','86','Tam Bình','Huyện Tam Bình','Tam Binh','huyen','tam-binh'),
  ('861','86','Bình Minh','Thị xã Bình Minh','Binh Minh','thi-xa','binh-minh'),
  ('862','86','Trà Ôn','Huyện Trà Ôn','Tra On','huyen','tra-on'),
  ('863','86','Bình Tân','Huyện Bình Tân','Binh Tan','huyen','binh-tan'),
  ('866','87','Cao Lãnh','Thành phố Cao Lãnh','Cao Lanh','thanh-pho','cao-lanh'),
  ('867','87','Sa Đéc','Thành phố Sa Đéc','Sa Dec','thanh-pho','sa-dec'),
  ('868','87','Hồng Ngự','Thành phố Hồng Ngự','Hong Ngu','thanh-pho','hong-ngu'),
  ('869','87','Tân Hồng','Huyện Tân Hồng','Tan Hong','huyen','tan-hong'),
  ('870','87','Hồng Ngự','Huyện Hồng Ngự','Hong Ngu','huyen','hong-ngu'),
  ('871','87','Tam Nông','Huyện Tam Nông','Tam Nong','huyen','tam-nong'),
  ('872','87','Tháp Mười','Huyện Tháp Mười','Thap Muoi','huyen','thap-muoi'),
  ('873','87','Cao Lãnh','Huyện Cao Lãnh','Cao Lanh','huyen','cao-lanh'),
  ('874','87','Thanh Bình','Huyện Thanh Bình','Thanh Binh','huyen','thanh-binh'),
  ('875','87','Lấp Vò','Huyện Lấp Vò','Lap Vo','huyen','lap-vo'),
  ('876','87','Lai Vung','Huyện Lai Vung','Lai Vung','huyen','lai-vung'),
  ('877','87','Châu Thành','Huyện Châu Thành','Chau Thanh','huyen','chau-thanh'),
  ('883','89','Long Xuyên','Thành phố Long Xuyên','Long Xuyen','thanh-pho','long-xuyen'),
  ('884','89','Châu Đốc','Thành phố Châu Đốc','Chau Doc','thanh-pho','chau-doc'),
  ('886','89','An Phú','Huyện An Phú','An Phu','huyen','an-phu'),
  ('887','89','Tân Châu','Thị xã Tân Châu','Tan Chau','thi-xa','tan-chau'),
  ('888','89','Phú Tân','Huyện Phú Tân','Phu Tan','huyen','phu-tan'),
  ('889','89','Châu Phú','Huyện Châu Phú','Chau Phu','huyen','chau-phu'),
  ('890','89','Tịnh Biên','Thị xã Tịnh Biên','Tinh Bien','thi-xa','tinh-bien'),
  ('891','89','Tri Tôn','Huyện Tri Tôn','Tri Ton','huyen','tri-ton'),
  ('892','89','Châu Thành','Huyện Châu Thành','Chau Thanh','huyen','chau-thanh'),
  ('893','89','Chợ Mới','Huyện Chợ Mới','Cho Moi','huyen','cho-moi'),
  ('894','89','Thoại Sơn','Huyện Thoại Sơn','Thoai Son','huyen','thoai-son'),
  ('899','91','Rạch Giá','Thành phố Rạch Giá','Rach Gia','thanh-pho','rach-gia'),
  ('900','91','Hà Tiên','Thành phố Hà Tiên','Ha Tien','thanh-pho','ha-tien'),
  ('902','91','Kiên Lương','Huyện Kiên Lương','Kien Luong','huyen','kien-luong'),
  ('903','91','Hòn Đất','Huyện Hòn Đất','Hon Dat','huyen','hon-dat'),
  ('904','91','Tân Hiệp','Huyện Tân Hiệp','Tan Hiep','huyen','tan-hiep'),
  ('905','91','Châu Thành','Huyện Châu Thành','Chau Thanh','huyen','chau-thanh'),
  ('906','91','Giồng Riềng','Huyện Giồng Riềng','Giong Rieng','huyen','giong-rieng'),
  ('907','91','Gò Quao','Huyện Gò Quao','Go Quao','huyen','go-quao'),
  ('908','91','An Biên','Huyện An Biên','An Bien','huyen','an-bien'),
  ('909','91','An Minh','Huyện An Minh','An Minh','huyen','an-minh'),
  ('910','91','Vĩnh Thuận','Huyện Vĩnh Thuận','Vinh Thuan','huyen','vinh-thuan'),
  ('911','91','Phú Quốc','Thành phố Phú Quốc','Phu Quoc','thanh-pho','phu-quoc'),
  ('912','91','Kiên Hải','Huyện Kiên Hải','Kien Hai','huyen','kien-hai'),
  ('913','91','U Minh Thượng','Huyện U Minh Thượng','U Minh Thuong','huyen','u-minh-thuong'),
  ('914','91','Giang Thành','Huyện Giang Thành','Giang Thanh','huyen','giang-thanh'),
  ('916','92','Ninh Kiều','Quận Ninh Kiều','Ninh Kieu','quan','ninh-kieu'),
  ('917','92','Ô Môn','Quận Ô Môn','O Mon','quan','o-mon'),
  ('918','92','Bình Thuỷ','Quận Bình Thuỷ','Binh Thuy','quan','binh-thuy'),
  ('919','92','Cái Răng','Quận Cái Răng','Cai Rang','quan','cai-rang'),
  ('923','92','Thốt Nốt','Quận Thốt Nốt','Thot Not','quan','thot-not'),
  ('924','92','Vĩnh Thạnh','Huyện Vĩnh Thạnh','Vinh Thanh','huyen','vinh-thanh'),
  ('925','92','Cờ Đỏ','Huyện Cờ Đỏ','Co Do','huyen','co-do'),
  ('926','92','Phong Điền','Huyện Phong Điền','Phong Dien','huyen','phong-dien'),
  ('927','92','Thới Lai','Huyện Thới Lai','Thoi Lai','huyen','thoi-lai'),
  ('930','93','Vị Thanh','Thành phố Vị Thanh','Vi Thanh','thanh-pho','vi-thanh'),
  ('931','93','Ngã Bảy','Thành phố Ngã Bảy','Nga Bay','thanh-pho','nga-bay'),
  ('932','93','Châu Thành A','Huyện Châu Thành A','Chau Thanh A','huyen','chau-thanh-a'),
  ('933','93','Châu Thành','Huyện Châu Thành','Chau Thanh','huyen','chau-thanh'),
  ('934','93','Phụng Hiệp','Huyện Phụng Hiệp','Phung Hiep','huyen','phung-hiep'),
  ('935','93','Vị Thuỷ','Huyện Vị Thuỷ','Vi Thuy','huyen','vi-thuy'),
  ('936','93','Long Mỹ','Huyện Long Mỹ','Long My','huyen','long-my'),
  ('937','93','Long Mỹ','Thị xã Long Mỹ','Long My','thi-xa','long-my'),
  ('941','94','Sóc Trăng','Thành phố Sóc Trăng','Soc Trang','thanh-pho','soc-trang'),
  ('942','94','Châu Thành','Huyện Châu Thành','Chau Thanh','huyen','chau-thanh'),
  ('943','94','Kế Sách','Huyện Kế Sách','Ke Sach','huyen','ke-sach'),
  ('944','94','Mỹ Tú','Huyện Mỹ Tú','My Tu','huyen','my-tu'),
  ('945','94','Cù Lao Dung','Huyện Cù Lao Dung','Cu Lao Dung','huyen','cu-lao-dung'),
  ('946','94','Long Phú','Huyện Long Phú','Long Phu','huyen','long-phu'),
  ('947','94','Mỹ Xuyên','Huyện Mỹ Xuyên','My Xuyen','huyen','my-xuyen'),
  ('948','94','Ngã Năm','Thị xã Ngã Năm','Nga Nam','thi-xa','nga-nam'),
  ('949','94','Thạnh Trị','Huyện Thạnh Trị','Thanh Tri','huyen','thanh-tri'),
  ('950','94','Vĩnh Châu','Thị xã Vĩnh Châu','Vinh Chau','thi-xa','vinh-chau'),
  ('951','94','Trần Đề','Huyện Trần Đề','Tran De','huyen','tran-de'),
  ('954','95','Bạc Liêu','Thành phố Bạc Liêu','Bac Lieu','thanh-pho','bac-lieu'),
  ('956','95','Hồng Dân','Huyện Hồng Dân','Hong Dan','huyen','hong-dan'),
  ('957','95','Phước Long','Huyện Phước Long','Phuoc Long','huyen','phuoc-long'),
  ('958','95','Vĩnh Lợi','Huyện Vĩnh Lợi','Vinh Loi','huyen','vinh-loi'),
  ('959','95','Giá Rai','Thị xã Giá Rai','Gia Rai','thi-xa','gia-rai'),
  ('960','95','Đông Hải','Huyện Đông Hải','Dong Hai','huyen','dong-hai'),
  ('961','95','Hoà Bình','Huyện Hoà Bình','Hoa Binh','huyen','hoa-binh'),
  ('964','96','Cà Mau','Thành phố Cà Mau','Ca Mau','thanh-pho','ca-mau'),
  ('966','96','U Minh','Huyện U Minh','U Minh','huyen','u-minh'),
  ('967','96','Thới Bình','Huyện Thới Bình','Thoi Binh','huyen','thoi-binh'),
  ('968','96','Trần Văn Thời','Huyện Trần Văn Thời','Tran Van Thoi','huyen','tran-van-thoi'),
  ('969','96','Cái Nước','Huyện Cái Nước','Cai Nuoc','huyen','cai-nuoc'),
  ('970','96','Đầm Dơi','Huyện Đầm Dơi','Dam Doi','huyen','dam-doi'),
  ('971','96','Năm Căn','Huyện Năm Căn','Nam Can','huyen','nam-can'),
  ('972','96','Phú Tân','Huyện Phú Tân','Phu Tan','huyen','phu-tan'),
  ('973','96','Ngọc Hiển','Huyện Ngọc Hiển','Ngoc Hien','huyen','ngoc-hien')
ON CONFLICT (code) DO UPDATE SET
  province_code=EXCLUDED.province_code, name=EXCLUDED.name,
  name_full=EXCLUDED.name_full, name_en=EXCLUDED.name_en,
  type=EXCLUDED.type, slug=EXCLUDED.slug;
