{{- if not .Values.shippingService.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.shippingService.name }}-secret
type: Opaque
stringData:
  mysqlPassword: {{ .Values.shippingService.env.mysqlPassword | quote }}
  ghnToken: {{ .Values.shippingService.env.ghnToken | quote }}
  ghnWebhookToken: {{ .Values.shippingService.env.ghnWebhookToken | quote }}
  callbackSecret: {{ .Values.shippingService.env.callbackSecret | quote }}
  apiKeys: {{ .Values.shippingService.env.apiKeys | quote }}
{{- end }}
