apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorize-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      server: authorizeservice
  template:
    metadata:
      labels:
        server: authorizeservice
    spec:
      containers:
        - name: authorizeservice
          image: authorizeservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 1234
            - containerPort: 1231
          env:
            - name: NODE_ENV
              value: productionsẻum khủ mùi 