gen-permission:
	protoc --go_out=. --go_opt=module=github.com/JieeiroSst/authorize-service --go-grpc_out=. --go-grpc_opt=module=github.com/JieeiroSst/authorize-service ./api/permission/permission.proto
