apiVersion: v1
kind: Service
metadata:
  name: user-service-clusterip-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 1234
    - port: 80
      targetPort: 1231
  selector:
    server: authorizeservice