apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mysql.service.loadBalancer.name}}
spec:
  ports:
    - port: 80
      targetPort: {{.Values.mysql.image.port}}
  selector:
    app: {{.Values.mysql.name}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mysql.service.nodeport.name}}
spec:
  type: {{.Values.mysql.service.nodeport.type}}
  ports:
  - port: 80
    targetPort: 3306
    nodePort: 32003
  selector:
    app: {{.Values.mysql.name}}