apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cdnService.name }}-deployment
spec:
{{- if not .Values.cdnService.autoscaling.enabled }}
  replicas: {{ .Values.cdnService.replicas }}
{{- end }}
  selector:
    matchLabels:
      app: {{ .Values.cdnService.name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Values.cdnService.name }}-deployment
    spec:
      containers:
      - name: {{ .Values.cdnService.name }}-deployment
        image: {{ .Values.cdnService.image.name }}:{{ .Values.cdnService.image.tag }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: {{ .Values.cdnService.image.port }}
        env:
          - name: PORT_SERVER
            value: "{{ .Values.cdnService.image.port }}"
        resources:
          {{- toYaml .Values.cdnService.resources | nindent 10 }}
        volumeMounts:
        - name: env-file
          mountPath: /app/.env
          subPath: cdn-service.env
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: env-file
        secret:
          secretName: service-env-files
      - name: uploads
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cdnService.service.name }}
spec:
  type: {{ .Values.cdnService.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.cdnService.image.port }}
  selector:
    app: {{ .Values.cdnService.name }}-deployment
