apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 4222
        - containerPort: 6222
        - containerPort: 8222
        env:
          - name: NODE_ENV
            value: production