apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.ports.client.port }}
    targetPort: {{ .Values.service.ports.client.port }}
    nodePort: {{ .Values.service.ports.client.nodePort }}
  - protocol: TCP
    port: {{ .Values.service.ports.cluster.port }}
    targetPort: {{ .Values.service.ports.cluster.port }}
    nodePort: {{ .Values.service.ports.cluster.nodePort }}
  - protocol: TCP
    port: {{ .Values.service.ports.monitoring.port }}
    targetPort: {{ .Values.service.ports.monitoring.port }}
    nodePort: {{ .Values.service.ports.monitoring.nodePort }}
  selector:
    app: nats