apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-deployment
  template:
    metadata:
      labels:
        app: rabbitmq-deployment
    spec:
      containers:
      - name: rabbitmq-deployment
        image: rabbitmq:3.8
        ports:
          - name: http
            protocol: TCP
            containerPort: 15672
          - name: amqp
            protocol: TCP
            containerPort: 5672
        imagePullPolicy: Always
        env:
          - name: RABBIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-config
                key: RABBIT_USERNAME
          - name: RABBIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-config
                key: RABBIT_PASSWORD