consul:
  name: consul
  replicas: 1

  image:
    name: hashicorp/consul
    tag: 1.11.2
    port: 8500

  service:
    name: consul-svc
    type: LoadBalancer
    nodeport: 30009

  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClassName: ""

  backup:
    enabled: true
    schedule: "0 2 * * *"
    retention: 7
    persistence:
      size: 2Gi
      accessMode: ReadWriteOnce
      storageClassName: ""
