package domain

var Engines = []Engine{
	{ID: "google", Group: "Google", Name: "Google Search", Required: [][]string{{"q"}}},
	{ID: "google_light", Group: "Google", Name: "Google Light Search", Required: [][]string{{"q"}}},
	{ID: "google_ai_mode", Group: "Google", Name: "Google AI Mode", Required: [][]string{{"q"}}},
	{ID: "google_ai_overview", Group: "Google", Name: "Google AI Overview", Required: [][]string{{"page_token"}}},
	{ID: "google_ads", Group: "Google", Name: "Google Ads", Required: [][]string{{"q"}, {"location"}}},
	{ID: "google_ads_transparency_center", Group: "Google", Name: "Google Ads Transparency Center", Required: [][]string{{"advertiser_id", "text"}}},
	{ID: "google_ads_transparency_center_ad_details", Group: "Google", Name: "Google Ads Transparency Ad Details", Required: [][]string{{"advertiser_id"}, {"creative_id"}}},
	{ID: "google_autocomplete", Group: "Google", Name: "Google Autocomplete", Required: [][]string{{"q"}}},
	{ID: "google_events", Group: "Google", Name: "Google Events", Required: [][]string{{"q"}}},
	{ID: "google_finance", Group: "Google", Name: "Google Finance", Required: [][]string{{"q"}}},
	{ID: "google_finance_markets", Group: "Google", Name: "Google Finance Markets", Required: [][]string{{"trend"}}},
	{ID: "google_flights", Group: "Google", Name: "Google Flights"},
	{ID: "google_flights_autocomplete", Group: "Google", Name: "Google Flights Autocomplete", Required: [][]string{{"q"}}},
	{ID: "google_flights_deals", Group: "Google", Name: "Google Flights Deals"},
	{ID: "google_forums", Group: "Google", Name: "Google Forums", Required: [][]string{{"q"}}},
	{ID: "google_hotels", Group: "Google", Name: "Google Hotels", Required: [][]string{{"q"}, {"check_in_date"}, {"check_out_date"}}},
	{ID: "google_hotels_autocomplete", Group: "Google", Name: "Google Hotels Autocomplete", Required: [][]string{{"q"}}},
	{ID: "google_hotels_photos", Group: "Google", Name: "Google Hotels Photos", Required: [][]string{{"property_token"}}},
	{ID: "google_hotels_reviews", Group: "Google", Name: "Google Hotels Reviews", Required: [][]string{{"property_token"}}},
	{ID: "google_images", Group: "Google", Name: "Google Images", Required: [][]string{{"q"}}},
	{ID: "google_images_light", Group: "Google", Name: "Google Images Light", Required: [][]string{{"q"}}},
	{ID: "google_images_related_content", Group: "Google", Name: "Google Images Related Content", Required: [][]string{{"related_content_id"}}},
	{ID: "google_immersive_product", Group: "Google", Name: "Google Immersive Product", Required: [][]string{{"page_token"}}},
	{ID: "google_jobs", Group: "Google", Name: "Google Jobs", Required: [][]string{{"q"}}},
	{ID: "google_jobs_listing", Group: "Google", Name: "Google Jobs Listing", Required: [][]string{{"q"}}},
	{ID: "google_lens", Group: "Google", Name: "Google Lens", Required: [][]string{{"url", "image_id"}}},
	{ID: "google_lens_image_sources", Group: "Google", Name: "Google Lens Image Sources", Required: [][]string{{"page_token"}}, Discontinued: "use engine google_lens with type=exact_matches"},
	{ID: "google_local", Group: "Google", Name: "Google Local", Required: [][]string{{"q"}}},
	{ID: "google_local_services", Group: "Google", Name: "Google Local Services", Required: [][]string{{"q", "cid"}}},
	{ID: "google_maps", Group: "Google", Name: "Google Maps", Required: [][]string{{"q", "data", "place_id", "data_cid"}}},
	{ID: "google_maps_autocomplete", Group: "Google", Name: "Google Maps Autocomplete", Required: [][]string{{"q"}, {"ll"}}},
	{ID: "google_maps_contributor_reviews", Group: "Google", Name: "Google Maps Contributor Reviews", Required: [][]string{{"contributor_id"}}},
	{ID: "google_maps_directions", Group: "Google", Name: "Google Maps Directions", Required: [][]string{{"start_addr", "start_data_id", "start_coords"}, {"end_addr", "end_data_id", "end_coords"}}},
	{ID: "google_maps_photos", Group: "Google", Name: "Google Maps Photos", Required: [][]string{{"data_id"}}},
	{ID: "google_maps_photo_meta", Group: "Google", Name: "Google Maps Photo Meta", Required: [][]string{{"data_id"}}},
	{ID: "google_maps_posts", Group: "Google", Name: "Google Maps Posts", Required: [][]string{{"data_id"}}},
	{ID: "google_maps_reviews", Group: "Google", Name: "Google Maps Reviews", Required: [][]string{{"data_id", "place_id"}}},
	{ID: "google_news", Group: "Google", Name: "Google News"},
	{ID: "google_news_light", Group: "Google", Name: "Google News Light", Required: [][]string{{"q"}}},
	{ID: "google_patents", Group: "Google", Name: "Google Patents"},
	{ID: "google_patents_details", Group: "Google", Name: "Google Patents Details", Required: [][]string{{"patent_id"}}},
	{ID: "google_play", Group: "Google", Name: "Google Play Store"},
	{ID: "google_play_books", Group: "Google", Name: "Google Play Books"},
	{ID: "google_play_games", Group: "Google", Name: "Google Play Games"},
	{ID: "google_play_movies", Group: "Google", Name: "Google Play Movies"},
	{ID: "google_play_product", Group: "Google", Name: "Google Play Product", Required: [][]string{{"product_id"}}},
	{ID: "google_product", Group: "Google", Name: "Google Product", Required: [][]string{{"product_id", "page_token"}}},
	{ID: "google_related_questions", Group: "Google", Name: "Google Related Questions", Required: [][]string{{"next_page_token"}}},
	{ID: "google_reverse_image", Group: "Google", Name: "Google Reverse Image", Required: [][]string{{"image_url"}}},
	{ID: "google_scholar", Group: "Google", Name: "Google Scholar", Required: [][]string{{"q", "cites", "cluster"}}},
	{ID: "google_scholar_cite", Group: "Google", Name: "Google Scholar Cite", Required: [][]string{{"q"}}},
	{ID: "google_scholar_profiles", Group: "Google", Name: "Google Scholar Profiles", Required: [][]string{{"mauthors"}}, Discontinued: "use engine google_scholar_author with author_id"},
	{ID: "google_scholar_author", Group: "Google", Name: "Google Scholar Author", Required: [][]string{{"author_id"}}},
	{ID: "google_scholar_case_law", Group: "Google", Name: "Google Scholar Case Law", Required: [][]string{{"case_id"}}},
	{ID: "google_shopping", Group: "Google", Name: "Google Shopping", Required: [][]string{{"q", "shoprs"}}},
	{ID: "google_shopping_light", Group: "Google", Name: "Google Shopping Light", Required: [][]string{{"q"}}},
	{ID: "google_shopping_filters", Group: "Google", Name: "Google Shopping Filters", Required: [][]string{{"q"}}},
	{ID: "google_short_videos", Group: "Google", Name: "Google Short Videos", Required: [][]string{{"q"}}},
	{ID: "google_sports", Group: "Google", Name: "Google Sports", Required: [][]string{{"kgmid"}, {"sp"}, {"type"}}},
	{ID: "google_travel_explore", Group: "Google", Name: "Google Travel Explore", Required: [][]string{{"departure_id"}}},
	{ID: "google_trends", Group: "Google", Name: "Google Trends", Required: [][]string{{"q"}}},
	{ID: "google_trends_autocomplete", Group: "Google", Name: "Google Trends Autocomplete", Required: [][]string{{"q"}}},
	{ID: "google_trends_trending_now", Group: "Google", Name: "Google Trends Trending Now"},
	{ID: "google_trends_news", Group: "Google", Name: "Google Trends News", Required: [][]string{{"page_token"}}},
	{ID: "google_videos", Group: "Google", Name: "Google Videos", Required: [][]string{{"q"}}},
	{ID: "google_videos_light", Group: "Google", Name: "Google Videos Light", Required: [][]string{{"q"}}},
	{ID: "google_about_this_result", Group: "Google", Name: "Google About This Result", Required: [][]string{{"q", "req_token"}}},
	{ID: "bing", Group: "Bing", Name: "Bing Search", Required: [][]string{{"q"}}},
	{ID: "bing_copilot", Group: "Bing", Name: "Bing Copilot", Required: [][]string{{"q"}}},
	{ID: "bing_images", Group: "Bing", Name: "Bing Images", Required: [][]string{{"q"}}},
	{ID: "bing_maps", Group: "Bing", Name: "Bing Maps", Required: [][]string{{"q", "place_id"}}},
	{ID: "bing_news", Group: "Bing", Name: "Bing News", Required: [][]string{{"q"}}},
	{ID: "bing_product", Group: "Bing", Name: "Bing Product", Required: [][]string{{"product_token"}}},
	{ID: "bing_reverse_image", Group: "Bing", Name: "Bing Reverse Image", Required: [][]string{{"image_url"}}},
	{ID: "bing_shopping", Group: "Bing", Name: "Bing Shopping", Required: [][]string{{"q"}}},
	{ID: "bing_videos", Group: "Bing", Name: "Bing Videos", Required: [][]string{{"q"}}},
	{ID: "baidu", Group: "Baidu", Name: "Baidu Search", Required: [][]string{{"q"}}},
	{ID: "baidu_news", Group: "Baidu", Name: "Baidu News", Required: [][]string{{"q"}}},
	{ID: "yahoo", Group: "Yahoo", Name: "Yahoo! Search", Required: [][]string{{"p"}}},
	{ID: "yahoo_images", Group: "Yahoo", Name: "Yahoo! Images", Required: [][]string{{"p"}}},
	{ID: "yahoo_videos", Group: "Yahoo", Name: "Yahoo! Videos", Required: [][]string{{"p"}}},
	{ID: "yandex", Group: "Yandex", Name: "Yandex Search", Required: [][]string{{"text"}}},
	{ID: "yandex_images", Group: "Yandex", Name: "Yandex Images", Required: [][]string{{"text", "url"}}},
	{ID: "yandex_videos", Group: "Yandex", Name: "Yandex Videos", Required: [][]string{{"text"}}},
	{ID: "duckduckgo", Group: "DuckDuckGo", Name: "DuckDuckGo Search", Required: [][]string{{"q"}}},
	{ID: "duckduckgo_light", Group: "DuckDuckGo", Name: "DuckDuckGo Light", Required: [][]string{{"q"}}},
	{ID: "duckduckgo_maps", Group: "DuckDuckGo", Name: "DuckDuckGo Maps", Required: [][]string{{"q"}}},
	{ID: "duckduckgo_news", Group: "DuckDuckGo", Name: "DuckDuckGo News", Required: [][]string{{"q"}}},
	{ID: "brave_ai_mode", Group: "Brave", Name: "Brave AI Mode", Required: [][]string{{"q"}}},
	{ID: "ebay", Group: "eBay", Name: "eBay Search", Required: [][]string{{"_nkw", "category_id"}}},
	{ID: "ebay_product", Group: "eBay", Name: "eBay Product", Required: [][]string{{"product_id"}}},
	{ID: "ebay_seller", Group: "eBay", Name: "eBay Seller", Required: [][]string{{"seller_id"}, {"type"}}},
	{ID: "walmart", Group: "Walmart", Name: "Walmart Search", Required: [][]string{{"query", "cat_id"}}},
	{ID: "walmart_product", Group: "Walmart", Name: "Walmart Product", Required: [][]string{{"product_id"}}},
	{ID: "walmart_product_reviews", Group: "Walmart", Name: "Walmart Reviews", Required: [][]string{{"product_id"}}},
	{ID: "walmart_product_sellers", Group: "Walmart", Name: "Walmart Sellers", Required: [][]string{{"product_id"}, {"store_id"}}},
	{ID: "home_depot", Group: "Home Depot", Name: "The Home Depot Search", Required: [][]string{{"q"}}},
	{ID: "home_depot_product", Group: "Home Depot", Name: "The Home Depot Product", Required: [][]string{{"product_id"}}},
	{ID: "home_depot_product_reviews", Group: "Home Depot", Name: "The Home Depot Reviews", Required: [][]string{{"product_id"}}},
	{ID: "amazon", Group: "Amazon", Name: "Amazon Search", Required: [][]string{{"k", "node"}}},
	{ID: "amazon_autocomplete", Group: "Amazon", Name: "Amazon Autocomplete", Required: [][]string{{"k"}}},
	{ID: "amazon_product", Group: "Amazon", Name: "Amazon Product", Required: [][]string{{"asin"}}},
	{ID: "youtube", Group: "YouTube", Name: "YouTube Search", Required: [][]string{{"search_query"}}},
	{ID: "youtube_video", Group: "YouTube", Name: "YouTube Video", Required: [][]string{{"v"}}},
	{ID: "youtube_video_transcript", Group: "YouTube", Name: "YouTube Video Transcript", Required: [][]string{{"v"}}},
	{ID: "youtube_channel", Group: "YouTube", Name: "YouTube Channel", Required: [][]string{{"channel_id"}}},
	{ID: "apple_app_store", Group: "Apple", Name: "Apple App Store Search", Required: [][]string{{"term"}}},
	{ID: "apple_product", Group: "Apple", Name: "Apple App Store Product", Required: [][]string{{"product_id"}}},
	{ID: "apple_reviews", Group: "Apple", Name: "Apple App Store Reviews", Required: [][]string{{"product_id"}}},
	{ID: "apple_maps", Group: "Apple", Name: "Apple Maps", Required: [][]string{{"query"}, {"center", "location"}}},
	{ID: "apple_maps_places", Group: "Apple", Name: "Apple Maps Places", Required: [][]string{{"muid"}}},
	{ID: "naver", Group: "Naver", Name: "Naver Search", Required: [][]string{{"query"}}},
	{ID: "naver_ai_overview", Group: "Naver", Name: "Naver AI Overview", Required: [][]string{{"query", "page_token"}}},
	{ID: "yelp", Group: "Yelp", Name: "Yelp Search", Required: [][]string{{"find_loc"}}},
	{ID: "yelp_place", Group: "Yelp", Name: "Yelp Place", Required: [][]string{{"place_id"}}},
	{ID: "yelp_reviews", Group: "Yelp", Name: "Yelp Reviews", Required: [][]string{{"place_id"}}},
	{ID: "tripadvisor", Group: "Tripadvisor", Name: "Tripadvisor Search", Required: [][]string{{"q"}}},
	{ID: "tripadvisor_place", Group: "Tripadvisor", Name: "Tripadvisor Place", Required: [][]string{{"place_id"}}},
	{ID: "tripadvisor_reviews", Group: "Tripadvisor", Name: "Tripadvisor Reviews", Required: [][]string{{"place_id"}}},
	{ID: "airbnb", Group: "Other", Name: "Airbnb Search", Required: [][]string{{"q", "map_bounds"}}},
	{ID: "zillow", Group: "Other", Name: "Zillow Search", Required: [][]string{{"region_id", "map_bounds"}}},
	{ID: "open_table_reviews", Group: "Other", Name: "OpenTable Reviews", Required: [][]string{{"rid"}}},
	{ID: "facebook_profile", Group: "Other", Name: "Facebook Profile", Required: [][]string{{"profile_id"}}},
	{ID: "instagram_profile", Group: "Other", Name: "Instagram Profile", Required: [][]string{{"profile_id"}}},
	{ID: "search_index", Group: "Other", Name: "SerpApi Search Index", Required: [][]string{{"q"}}},
}
