{{- if and .Values.customerRelationshipService.env.company.signKeyPEM .Values.customerRelationshipService.env.company.signCertPEM }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.customerRelationshipService.name }}-company-seal
type: Opaque
stringData:
  seal.key: |
    {{- .Values.customerRelationshipService.env.company.signKeyPEM | nindent 4 }}
  seal.pem: |
    {{- .Values.customerRelationshipService.env.company.signCertPEM | nindent 4 }}
{{- end }}
