{{- if not .Values.carRentalService.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.carRentalService.name }}-secret
type: Opaque
stringData:
  postgresPassword: {{ .Values.carRentalService.database.password | quote }}
{{- end }}
