package dto

import "github.com/JIeeiroSst/workflow-service/pkg/excel"

type SeattleWeatherRequestDTO struct {
	Date          string
	Precipitation string
	TempMax       string
	TempMin       string
	Wind          string
	Weather       string
}

func FormatSeattleWeather(generated []excel.AutoGenerated) (seattleWeathers []SeattleWeatherRequestDTO) {
	for _, value := range generated {
		var seattleWeather SeattleWeatherRequestDTO
		for i := 0; i < len(value.Values); i++ {
			switch i {
			case 1:
				seattleWeather.Date = value.Values[i].UserEnteredValue.StringValue
			case 2:
				seattleWeather.Precipitation = value.Values[i].UserEnteredValue.StringValue
			case 3:
				seattleWeather.TempMax = value.Values[i].UserEnteredValue.StringValue
			case 4:
				seattleWeather.TempMin = value.Values[i].UserEnteredValue.StringValue
			case 5:
				seattleWeather.Wind = value.Values[i].UserEnteredValue.StringValue
			case 6:
				seattleWeather.Weather = value.Values[i].UserEnteredValue.StringValue
			}
		}
		seattleWeathers = append(seattleWeathers, seattleWeather)
	}

	return
}
