apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysqlRiver.name }}-config
data:
  river.toml: |
    my_addr = "{{ .Values.mysqlRiver.mysql.addr }}"
    my_user = "{{ .Values.mysqlRiver.mysql.user }}"
    my_pass = "{{ .Values.mysqlRiver.mysql.password }}"
    my_charset = "{{ .Values.mysqlRiver.mysql.charset }}"

    es_addr = "{{ .Values.mysqlRiver.elasticsearch.addr }}"
    es_user = ""
    es_pass = ""

    data_dir = "/var/lib/river"

    stat_addr = "0.0.0.0:{{ .Values.mysqlRiver.service.port }}"
    stat_path = "/metrics"

    server_id = {{ .Values.mysqlRiver.serverId }}

    flavor = "mysql"

    mysqldump = "mysqldump"

    skip_master_data = true

    bulk_size = 128

    flush_bulk_time = "200ms"

    skip_no_pk_table = true
    {{- range .Values.mysqlRiver.sources }}

    [[source]]
    schema = "{{ .schema }}"
    tables = [{{ range $i, $t := .tables }}{{ if $i }}, {{ end }}"{{ $t }}"{{ end }}]
    {{- end }}
