apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-river-config
data:
  river.toml: |
    my_addr = "mysql-svc:80"
    my_user = "river"
    my_pass = "riverPassword"
    my_charset = "utf8"

    es_addr = "elasticsearch-service:9200"
    es_user = ""
    es_pass = ""

    data_dir = "/var/lib/river"

    stat_addr = "0.0.0.0:12800"
    stat_path = "/metrics"

    server_id = 1001

    flavor = "mysql"

    mysqldump = "mysqldump"

    skip_master_data = true

    bulk_size = 128

    flush_bulk_time = "200ms"

    skip_no_pk_table = true

    [[source]]
    schema = "banking_service"
    tables = ["*"]

    [[source]]
    schema = "basket_service"
    tables = ["*"]

    [[source]]
    schema = "notification_service"
    tables = ["*"]
