apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysqlRiver.name }}
  labels:
    app: {{ .Values.mysqlRiver.name }}
spec:
  replicas: {{ .Values.mysqlRiver.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mysqlRiver.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysqlRiver.name }}
    spec:
      containers:
        - name: {{ .Values.mysqlRiver.name }}
          image: "{{ .Values.mysqlRiver.image.repository }}:{{ .Values.mysqlRiver.image.tag }}"
          imagePullPolicy: {{ .Values.mysqlRiver.image.pullPolicy }}
          args: ["-config=/etc/river/river.toml"]
          ports:
            - containerPort: {{ .Values.mysqlRiver.service.port }}
          resources:
            {{- toYaml .Values.mysqlRiver.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/river
            - name: data
              mountPath: /var/lib/river
      volumes:
        - name: config
          configMap:
            name: {{ .Values.mysqlRiver.name }}-config
        - name: data
          emptyDir: {}
