apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlRiver.service.name }}
spec:
  ports:
    - port: {{ .Values.mysqlRiver.service.port }}
      targetPort: {{ .Values.mysqlRiver.service.port }}
      nodePort: {{ .Values.mysqlRiver.service.nodePort }}
  type: NodePort
  selector:
    app: {{ .Values.mysqlRiver.name }}
