apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongo.name }}-data
  annotations:
    # Keep the databases when the release is removed.
    helm.sh/resource-policy: keep
spec:
  {{- with .Values.mongo.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.persistence.size }}
