apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mongo.service.name}}
spec:
  ports:
    - port: 80
      targetPort: {{.Values.mongo.image.port}}
  selector:
    app: {{.Values.mongo.name}}-deployment   