apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.geoservicePostgres.name }}-persistent-volume
  labels:
    type: local
    app: {{ .Values.geoservicePostgres.name }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.geoservicePostgres.storage.size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.geoservicePostgres.storage.hostPath | quote }}
