apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.geoservicePostgres.name }}
  labels:
    app: {{ .Values.geoservicePostgres.name }}
spec:
  ports:
    - port: {{ .Values.geoservicePostgres.service.port }}
      targetPort: {{ .Values.geoservicePostgres.service.targetPort }}
  selector:
    app: {{ .Values.geoservicePostgres.name }}
