apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.geoservicePostgres.name }}-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.geoservicePostgres.storage.size }}
