apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.drawImageService.service.name }}
  labels:
    app: {{ .Values.drawImageService.name }}
spec:
  type: {{ .Values.drawImageService.service.type }}
  selector:
    app: {{ .Values.drawImageService.name }}
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.drawImageService.image.port }}
