apiVersion: v2
name: notifyhub-service
description: A Helm chart for notifyhub-service, notification hub - email, SMS and push delivery with a worker pool

type: application

version: 0.2.0
appVersion: "1.0.0"

dependencies:
  - name: common
    version: "0.1.0"
    repository: file://../common
