basePath: /api/v1
definitions:
  model.Login:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  model.Role:
    properties:
      id:
        type: integer
      name:
        type: string
      users:
        items:
          $ref: '#/definitions/model.Users'
        type: array
    type: object
  model.Token:
    properties:
      encodeToken:
        type: string
    type: object
  model.RoleItem:
    properties:
      roleId:
        type: integer
      usersId:
        type: integer
    type: object
  model.Users:
    properties:
      address:
        type: string
      checked:
        type: boolean
      create_time:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      roles:
        items:
          $ref: '#/definitions/model.Role'
        type: array
      sex:
        type: string
      update_time:
        type: string
      username:
        type: string
    type: object
host: localhost:1235
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: User Service API
  version: "1.0"
paths:
  /api/v1/authentication:
    post:
      consumes:
      - application/json
      description: Authentication account
      parameters:
      - description: token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/model.Token'
      - description: username
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Authentication Account
  /api/v1/lock_user:
    post:
      consumes:
      - application/json
      description: LockAccount account
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: LockAccount Account
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: login account
      parameters:
      - description: user in json
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Login Account
  /api/v1/role:
    delete:
      consumes:
      - application/json
      description: Delete Role
      parameters:
      - description: id role
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Delete Role
    get:
      consumes:
      - application/json
      description: Roles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Roles
    post:
      consumes:
      - application/json
      description: Create Role
      parameters:
      - description: name in role
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create Role
    put:
      consumes:
      - application/json
      description: Update Role
      parameters:
      - description: id role
        in: query
        name: id
        required: true
        type: string
      - description: name in role
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update Role
  /api/v1/role-item:
    delete:
      consumes:
      - application/json
      description: login account
      parameters:
      - description: user-id
        in: query
        name: user-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Login Account
    post:
      consumes:
      - application/json
      description: AddRoleItem
      parameters:
      - description: user role in json
        in: body
        name: user-role
        required: true
        schema:
          $ref: '#/definitions/model.RoleItem'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: AddRoleItem
    put:
      consumes:
      - application/json
      description: UpdateUser Role
      parameters:
      - description: user-id
        in: query
        name: user-id
        required: true
        type: string
      - description: role-id
        in: query
        name: role-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: UpdateUser Role
  /api/v1/role/:id:
    get:
      consumes:
      - application/json
      description: Role
      parameters:
      - description: id role
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Role
  /api/v1/sign-up:
    post:
      consumes:
      - application/json
      description: SignUp account
      parameters:
      - description: user in json login
        in: body
        name: user
        schema:
          $ref: '#/definitions/model.Users'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: SignUp Account
  /api/v1/update/profile:
    put:
      consumes:
      - application/json
      description: UpdateProfile account
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: id in json login
        in: path
        name: id
        type: integer
      - description: user in json
        in: body
        name: user
        schema:
          $ref: '#/definitions/model.Users'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: UpdateProfile Account
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
