kafkaUi:
  name: kafka-ui-deployment
  replicas: 1

  image:
    repository: provectuslabs/kafka-ui
    tag: latest
    pullPolicy: Always

  clusterName: "K8 Kafka Cluster"
  bootstrapServers: kafka-service:9092

  service:
    name: kafka-ui-service
    nodeportName: kafka-ui-service-nodeport
    port: 80
    targetPort: 8080
    nodePort: 30001

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"
