apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.service.name }}
spec:
  ports:
  - port: {{ .Values.kibana.service.port }}
    targetPort: {{ .Values.kibana.service.targetPort }}
    nodePort: {{ .Values.kibana.service.nodePort }}
  selector:
    app: {{ .Values.kibana.name }}
  type: NodePort
