apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheus.name }}
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prometheus.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.prometheus.name }}
    spec:
      serviceAccountName: {{ .Values.prometheus.name }}
      automountServiceAccountToken: true
      securityContext:
        runAsGroup: 65534
        runAsUser: 65534
        runAsNonRoot: true
      containers:
        - name: {{ .Values.prometheus.name }}
          image: {{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - '--storage.tsdb.retention.time={{ .Values.prometheus.retention }}'
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus/data/'
          ports:
            - containerPort: {{ .Values.prometheus.service.port }}
              name: http
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: data-volume
              mountPath: /prometheus/data
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.prometheus.name }}
        - name: data-volume
          emptyDir:
            sizeLimit: {{ .Values.prometheus.dataVolumeSize | quote }}
