kafka:
  name: kafka-deployment
  replicas: 1

  image:
    name: bitnamilegacy/kafka
    tag: "3.3.2"

  service:
    name: kafka-service
    port: 9092

  zookeeperConnect: zookeeper-service:2181
  advertisedListener: PLAINTEXT://kafka-service:9092
  brokerId: "1001"

  resources:
    requests:
      cpu: "1"
      memory: "1G"
    limits:
      cpu: "2"
      memory: "2G"
