apiVersion: v1
kind: Service
metadata:
  name: {{.Values.redis.service.name}}
spec:
  ports:
  - port: 80
    targetPort: {{.Values.redis.image.port}}
  selector:
    app: {{.Values.redis.name}}-deployment