name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  authorize_service:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd authorize_service && docker build . --file Dockerfile --tag authorize_service:$(date +%s)

  user_service:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd user_service && docker build . --file Dockerfile --tag user_service:$(date +%s)
  
  post_service:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd post_service && docker build . --file Dockerfile --tag post_service:$(date +%s)

  shop_service:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd shop-service && docker build . --file Dockerfile --tag shop_service:$(date +%s)

  keikibook:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd keikibook && docker build . --file Dockerfile --tag keikibook:$(date +%s)