name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  authorize_service:
    name: authorize_service
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd authorize_service && go build -v ./...

    - name: Test
      run: cd authorize_service && go test -v ./...

  build:
    name: user_service
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd user_service && go build -v ./...

    - name: Test
      run: cd user_service && go test -v ./...
  
  build:                                                                                                                                                                                                                                                                      
    name: post_service                                                                                                                                                                                                                                                        
    runs-on: ubuntu-latest                                                                                                                                                                                                                                                    
    steps:                                                                                                                                                                                                                                                                    
    - uses: actions/checkout@v3                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                              
    - name: Set up Go                                                                                                                                                                                                                                                         
      uses: actions/setup-go@v3                                                                                                                                                                                                                                               
      with:                                                                                                                                                                                                                                                                   
        go-version: 1.18                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                              
    - name: Build                                                                                                                                                                                                                                                             
      run: cd post_service && go build -v ./...                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                              
    - name: Test                                                                                                                                                                                                                                                              
      run: cd post_service && go test -v ./...
