name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  job1:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: cd authorize_service && go build -v ./...

      - name: Test
        run: cd authorize_service && go test -v ./...
  job2:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: cd user_service && go build -v ./...

      - name: Test
        run: cd user_service && go test -v ./...
