name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  authorize_service:
    name: authorize_service
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd authorize_service && go build -v ./...

    - name: Test
      run: cd authorize_service && go test -v ./...

  user_service:
    name: user_service
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd user_service && go build -v ./...

    - name: Test
      run: cd user_service && go test -v ./...

  post_service:
    name: post_service
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd post_service && go build -v ./...

    - name: Test
      run: cd post_service && go test -v ./...

  payment_service:
    name: payment_service
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd payment_service && go build -v ./...

    - name: Test
      run: cd payment_service && go test -v ./...
    
  notification_service:
    name: notification_service
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd notification_service && go build -v ./...

    - name: Test
      run: cd notification_service && go test -v ./...

  upload_service:
    name: notification_service
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd upload_service && go build -v ./...

    - name: Test
      run: cd upload_service && go test -v ./...
